### ISSUE TITLE
hard crop

### ISSUE THREAD

**Issue by 3052** [pdfarranger/pdfarranger#1004]
the current cropping is reversible, it would be nice if crops could be made permanent

**Comment by 3052** [comment]
in my case, I was able to just manually remove the text I was concerned about like this:

~~~sh
qpdf --stream-data=uncompress a.pdf b.pdf
# remove text
qpdf b.pdf c.pdf
~~~

**Comment by dreua** [comment]
To clarify: qpdf did not automatically remove the text, you just needed it to bring the PDF in human editable form and used a text editor to remove the text. (Maybe I was the only one who didn't get this on the first read :shrug: )

**Comment by dreua** [comment]
Note that for some (maybe the majority of) users it would be easier to use Libreoffice Draw to open the page and remove the unwanted parts. No need to uncompress it and grep through large cryptic text files. Redacting / hard cropping PDFs is hard, I would rather have a FAQ about it (maybe directly in the readme) than adding features which are likely to cause confusion.

Even Google managed to [get this wrong it its crop tool](https://arstechnica.com/gadgets/2023/03/google-pixel-bug-lets-you-uncrop-the-last-four-years-of-screenshots/) on the pixel, and here we are talking about plain PNGs, not PDFs which are much more complex.

**Comment by 3052** [comment]
> To clarify: qpdf did not automatically remove the text, you just needed it to bring the PDF in human editable form and used a text editor to remove the text. (Maybe I was the only one who didn't get this on the first read 🤷 )

yeah sorry if I was not clear - what you said is correct
