### ISSUE TITLE
Option to uncompress streams 

### ISSUE THREAD

**Issue by 3052** [pdfarranger/pdfarranger#1005]
Is it possible to uncompress PDF? similar to:

~~~sh
# uncompress
qpdf --stream-data=uncompress a.pdf b.pdf
# compress
qpdf b.pdf c.pdf
~~~

https://github.com/qpdf/qpdf/releases

**Comment by dreua** [comment]
I don't think that is currently possible.

What would be the use case for this in PDF Arranger? I would assume everyone needing this can just use the qpdf cli.

**Comment by dreua** [comment]
I see #1004 now but in my opinion that is too specific for inclusion in PDF Arranger, even if it were easy to implement (which I currently don't know). Looking forward for more opinions though, I don't mean to have the final say in this.

**Comment by jeromerobert** [comment]
I agree, let's close it. qpdf is the right tool for those who want to hack in a PDF file. And manually editing a PDF file as a text file is really a corner case.
