### ISSUE TITLE
Correct a Chinese translation

### ISSUE THREAD

**Issue by liangjiancang** [pdfarranger/pdfarranger#1006]
![Snipaste_2023-11-28_16-52-18](https://github.com/pdfarranger/pdfarranger/assets/42267675/6e76d65c-a51e-4962-b27b-3bd34e07290c)

`Export All Pages to Individual Files...` should be `所有页面导出到个体文件(A)...`.

**Comment by dreua** [comment]
Could you review https://github.com/pdfarranger/pdfarranger/pull/1008 if I got this right?
