### ISSUE TITLE
Print from PDF Arranger ignores page orientation

### ISSUE THREAD

**Issue by akallabeth** [pdfarranger/pdfarranger#1015]
Describe the bug
----------------

To Reproduce
------------

Print a PDF from within PDFarramger with portrait and landscape pages

Expected behavior
-----------------

Pages are printed with the orientation like in the PDF

Actual behaviour
-----------------

Landscape oriented pages are cut and printed in portrait orientation

System and Versions
-------------------

-   1.10.1 (flatpak)
-   debian 12

**Comment by dreua** [comment]
Is this reproducible with some virtual or "to PDF" printer or is it just some specific hardware printer? I don't want to waste a lot of paper trying to reproduce it.

It could also be an issue in the driver, some driver dialogues even used to havea checkbox for "Auto rotate pages", if that is unchecked your results are expected.

Does it work if you print the resulting PDF in any other way?

**Comment by akallabeth** [comment]
@dreua 
* did reproduce with the cups-pdf printer on debian 12
* did print just fine with default gnome document viewer (evince?)

**Comment by jeromerobert** [comment]
This can also be reproduced without cups by clicking *Preview* in the print dialog, and with current master, and without snap. We need something more here https://github.com/pdfarranger/pdfarranger/blob/3240edc/pdfarranger/exporter.py#L659-L675.

**Comment by kbengs** [comment]
If noone is working on this I can do it.

**Comment by jeromerobert** [comment]
@kbengs please go head 🙏
