### ISSUE TITLE
Does not respect umask permissions when saving files

### ISSUE THREAD

**Issue by zkeng** [pdfarranger/pdfarranger#1023]
Describe the bug
----------------

When a PDF-file is saved with PDF-arranger the resulting file will have restrictive permissions:
-rw-r--r-- when saving a file with a new file name and
-rw------- when overwriting an existing file.

Note that I am pretty sure this is a new bug. Since I share most of my work with others on a file server I think we would have noticed earlier if this bug was present several months/versions back i PDF Arranger.

To Reproduce
------------

1. Make sure your umask is 'umask 002', so that new files are expected to have permissions -rw-rw-r--
2.  Open a PDF file in PDF Arranger.
3.  Add a new page to the document and save it to overwrite the original file and notice the new restrictive permissions (-rw-------) on the file.
4.  Then save the file with a new file name and notice the new restrictive permissions (-rw-r--r--).

Expected behavior
-----------------

I have 'umask 002' set in both '~/.bashrc' and  '~/.xsession' files and permissions on new files should be -rw-rw-r--

The saved output file from PDF arranger should apply permissions on new files as set by the current user umask, or if overwriting an existing file; then the permissions of the existing file should be respected.

Input files
-----------

The bug appears consistently for all PDF files saved with the tested version of PDF Arranger.

Screenshots
-----------

N/A

System and Versions
-------------------

-   PDF Arranger version 1.10.1 flatpak from Flathub on Debian 11.

**Comment by dreua** [comment]
Maybe this could be a workaround: https://superuser.com/questions/181159/can-i-set-the-umask-on-a-specific-directory?rq=1

**Comment by dreua** [comment]
Or maybe you'd rather help us out and try to check whether this is actually a regression and when it was introduced. Hopefully this guide  helps: https://docs.flathub.org/docs/for-users/bisecting/

**Comment by dreua** [comment]
I don't think this is a change in PDF Arranger by the way but it could come from the dependencies or the flatpak environment. Given that it worked in a previous flatpak at all.

**Comment by jeromerobert** [comment]
I tried with pikepdf 8.11.2 installed using pip and cannot reproduce the issue. What are the version of pikepdf and qpdf in the 1.10.1 flatpak ?

**Comment by jeromerobert** [comment]
https://github.com/flatpak/flatpak/issues/4007

**Comment by dreua** [comment]
> I tried with pikepdf 8.11.2 installed using pip and cannot reproduce the issue. What are the version of pikepdf and qpdf in the 1.10.1 flatpak ?

I usually publish new flatpak builds whenever dependencies get updates. Currently it looks like this:
 
> It uses libqpdf 11.7.0, pikepdf 8.11.2, GTK 3.24.38 and Python 3.11.7.

**Comment by zkeng** [comment]
Thank you for the fast feedback and thank you for pointing me to issue 4007.

You are right; when I do more testing the issue does not seem to be related to PDF Arranger, but related to the flatpak package installed on my system. We are still on Debian Buster (sorry bu non-techy creatives like my team just want a rock-solid stable release to run as long as possible without dist-upgrades) and recently upgraded the flatpak package.

On Debian the issue that permissions are not correctly set according to the user umask when flatpak apps are saving files was not present when using the default Debian 10 Buster flatpak version 1.2.5, but the issue seems to have appeared when upgrading to Buster backports flatpak version 1.10.7. I don't know if it has been resolved in the Debian 11 Bullseye flatpak version 1.10.8, or the Debian 12 Bookworm flatpak version 1.14.4.

I am marking this issue as solved.
