### ISSUE TITLE
Program won't start:  No module name 'deprecated'

### ISSUE THREAD

**Issue by mr-tug** [pdfarranger/pdfarranger#1026]
I've used PDF Arranger for years with no issues.  Tonight I tried opening it and nothing happened.  When I run it in the terminal, I get the following:

```
  File "/usr/lib/python3.10/site-packages/pdfarranger/pdfarranger.py", line 38, in <module>
    import pikepdf
  File "/usr/lib/python3.10/site-packages/pikepdf/__init__.py", line 55, in <module>
    from .models import (
  File "/usr/lib/python3.10/site-packages/pikepdf/models/__init__.py", line 17, in <module>
    from .matrix import PdfMatrix
  File "/usr/lib/python3.10/site-packages/pikepdf/models/matrix.py", line 10, in <module>
    from deprecated import deprecated
ModuleNotFoundError: No module named 'deprecated'
```
I tried removing and re-installing; same outcome.

Solus 4.5, installed via Software Center over 5 years ago.  System is fully updated.  Linux kernel 6.6.8-268.current, Pikepdf 8.9.0-29.  PDF Arranger worked as expected several months ago.

Any suggestions?  Thanks.

**Comment by jeromerobert** [comment]
You pikepdf package depends on `deprecation` instead of `deprecated`. This should be reported to Solus. See https://github.com/pikepdf/pikepdf/commit/b3d07a8da139450a3399fdde3025dc18ff41e564

Workaround: install the `python-deprecated` package.

**Comment by jeromerobert** [comment]
@algent-al

**Comment by mr-tug** [comment]
That worked.  Thank you very much for the help and for alerting Solus.
