### ISSUE TITLE
White Border Not removed

### ISSUE THREAD

**Issue by lucasalavapena** [pdfarranger/pdfarranger#1028]
Describe the bug
----------------

I have noticed that in a small number of cases that the crop white border button ignored non trivial amount of white borders that often in my opinion should be able to be removed (as above or below or to the right or to the left there are only white pixels).

To Reproduce
------------

1.  Select All Pages
2.  Split the pages evenly _vertically_ into 2
3.  Select All Pages
4.  Split the pages evenly _horizontally_ into 2
5. Select All Pages
6.  Select Crop White Border

Expected behavior
-----------------

White border/space would be removed.

See the screenshot below, I would not expect the white space at the bottom of the last page, there is not text in that white space. 

The video shows the state after having cropped all relevant pages but some pages seem to be ignored and even if you manually press crop on them it does not seem to work (note this a huge file 4k pages). 

Input files
-----------

1. https://arxiv.org/pdf/2401.01314.pdf
2. https://sites.math.rutgers.edu/~zeilberg/akherim/PCM.pdf

Screenshots
-----------

First example:
![image](https://github.com/pdfarranger/pdfarranger/assets/17073410/7a172845-aa50-4226-86e3-8eee3f4598e9)

Second example:
https://www.youtube.com/watch?v=6oJPnOLQLB0

Note for this example the steps were a bit more complicated as I skipped the first few pages before doing any splitting and had none even vertical splits since the book is not split in the middle (it has a preference for the a specific side depending on if it is an odd or even number). I think I split it vertically for the left hand sides of the books by these percentages 54 % and 46 %, and the right hand side the same values but flipped. Vertically the splits were still even.

System and Versions
-------------------

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)
-   pikepdf version and where you get it (distro package, pip, git, ...)
```
pdfarranger --version
PDF Arranger-1.10.1
pikepdf-8.9.0
libqpdf-11.6.4
```
I installed it using pacman, so from https://archlinux.org/packages/extra/any/pdfarranger/.

-   OS name and version (e.g.: Windows 10, Fedora 33, ...)
```
(Linux) 7.6.7-arch1-1
```

I also wanted to say thank you for creating and maintaining this app, it has been immensely useful. I can also try to help with figuring out the source of the problem if someone points me in the right direction.

**Comment by dreua** [comment]
> if you manually press crop on them it does not seem to work

Does that mean that even a manual crop by some percentage is nor working?

Help is always appreciated but I can't give you any pointers from the top of my head. Could be some invisible pieces on the PDF or a bug in pur code somewhere. You could try the same running from the CLI to see if it prints any errors.

**Comment by lucasalavapena** [comment]
> > if you manually press crop on them it does not seem to work
> 
> Does that mean that even a manual crop by some percentage is nor working?
> 
> Help is always appreciated but I can't give you any pointers from the top of my head. Could be some invisible pieces on the PDF or a bug in our code somewhere. You could try the same running from the CLI to see if it prints any errors.

Apologies for the imprecise language. I meant that after selecting all the pages and selecting crop white border, I clicked on an individual page and try to use crop white border again (as can be seen in the video example).

If pdfs can have invisible text, wouldn't it be useful to have a regular crop allowing specific dimensions that one could perform on selected pages? I at least do not see a regular cropping option, only the cropping of white border. Or is that out of the scope of this tool?

Furthermore, regarding invisible items on PDFs, do you have any recommendations on how to check that for it for my documents. I tried using [pdfux](https://pdfux.com/inspect-pdf/) and reading https://gendignoux.com/blog/2016/10/04/pdf-basics.html to understand and figure out more. However, raw PDF documents are a bit overwhelming to read. Perhaps you would know better what to look for? Should I look for a specific characteristic or could you give me an example if you have had experience with it before.

**Comment by dreua** [comment]
I think regular crop is hidden in page format. It was there before crop white borders came. Makes me wonder if our ui is still understandable.

**Comment by kbengs** [comment]
The issue seems to have been introduced with 34f74d6. I am working on a possible fix.

**Comment by lucasalavapena** [comment]
> I think regular crop is hidden in page format. It was there before crop white borders came. Makes me wonder if our ui is still understandable.

I can use that as a temporary solution. 

Regarding usability, I can see how it currently makes sense but on the other hand if rotate left, rotate right and crop white borders have their own higher levels options then I thought a regular crop would also be there. One solution could be to have an option simply named crop that splits (like paste special gives you multiple options) into the crop currently under page format and crop white border
