### ISSUE TITLE
Transfer the snap to the official dev team

### ISSUE THREAD

**Issue by soumyaDghosh** [pdfarranger/pdfarranger#1039]
The snap manifest is already served from the pdfarrange organisation. I would like to transfer the snap also, to the upstream in the store. Can upstream kindly make an account in the store, so, that I initiate the process of transfer?

**Comment by dreua** [comment]
That sounds like the responsibility and maintenance burden would be ours in the end and that should have been discussed in the first place before offering a snap to the users not afterwards. I'm not interest in learning snap and won't create such an account.

Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.

**Comment by soumyaDghosh** [comment]
> That sounds like the responsibility and maintenance burden would be ours in the end and that should have been discussed in the first place before offering a snap to the users not afterwards. I'm not interest in learning snap and won't create such an account.
> 
> Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.

I am sorry, if that's what got hinted by my words. What I meant to say is, the snap package can be shown in the store under the name of the upstream and not mine. I'll maintain it as a part of the organization. My apologies for the miscommunication.

**Comment by jeromerobert** [comment]
@soumyaDghosh If you look for the name of an individual or a company to set in snap store, I can find only one and it's yours. The only other way to identify PDF Arranger "upstream" is this URL: https://github.com/pdfarranger/pdfarranger

**Comment by soumyaDghosh** [comment]
> @soumyaDghosh If you look for the name of an individual or a company to set in snap store, I can find only one and it's yours. The only other way to identify PDF Arranger "upstream" is this URL: https://github.com/pdfarranger/pdfarranger

Sorry, I didn't understand this correctly, but my intention is to show that this app is from the upstream. This can be achieved by transferring the snap name under an account named `pdfarranger` or `jeromerobert` or whatever you want. 

like here, this snap is named under nlogozzo, 

https://snapcraft.io/tube-converter

But, I still maintain their snaps.

**Comment by jeromerobert** [comment]
You can create a "pdfarranger" account on snap if you want, but leaving the snap under your name seems also good to me.

**Comment by dreua** [comment]
> my intention is to show that this app is from the upstream

But it actually isn't so that would seem misleading to me :thinking:

**Comment by soumyaDghosh** [comment]
> You can create a "pdfarranger" account on snap if you want, but leaving the snap under your name seems also good to me.

Can anyone of the devs join in as a collaborator?

> But it actually isn't so that would seem misleading to me 🤔

There has not been any issue related to the snap in particular that has caused problems. So kindly think about making it.
