### ISSUE TITLE
Split and reorder booklet to pages

### ISSUE THREAD

**Issue by souslaplage** [pdfarranger/pdfarranger#1067]
There is the option to put several pages in booklet format. Can there be reverse options (re-format page by page)?
Integrate different bookletimposer options?

thank you to you

**Comment by dreua** [comment]
Would that be a combination of split (we have that) and reorder (would currently be manual work I think)?

**Comment by dreua** [comment]
In general that would be possible but it is the question if someone invests the time to implement and maintain it. On my first thought this seems like a niche use case and therefore unlikely to be implemented, but I'm in no way authority on that.

**Comment by souslaplage** [comment]
Yes, that's the right combination: the 1st page cut becomes the last, the 3rd the penultimate and so on. It's true that you can do it manually, but on large documents it can be time-consuming.

In terms of needs, I don't know how many people use it. I was thinking that as you already have the great page-by-page option to booklet, having the reverse would be very beneficial for reworking with a single program in one direction or another. I was also talking about booklet impose, which I don't think is developed any more, but which a lot of people who do paper distribution still use. It's present by default on the tails system, for example, so I imagine that it's used a lot, and reinstating its options will ensure that it's also functional in the long term. I've already noticed that some documents that can't be put in booklet format on bookletimposer work on pdfarranger. 

It's up to you to see what you think.

**Comment by m93a** [comment]
Hey! I've been semi-active in the DIY zine community and we've been using PDF Arranger to create booklets to print our zines! I just wanted to let you know that having an inverse operation would be great help for rescuing old zines (eg. those which can only be downloaded in booklet form).

**Comment by selfhoster1312** [comment]
Thanks to @dreua and @kbengs reviewing #1157 there should be unimposition available in the next PDFArranger release in the "Booklet->Split" menu action.

If someone would like to test before release, let me know and we can give instructions on how to try it out!

Let the DIY zines flourish :fire:

**Comment by kbengs** [comment]
Implemented in #1157
@selfhoster1312 Thanks!
