### ISSUE TITLE
Printing clips out the right/bottom sides when PDF's page size is bigger than the paper size.

### ISSUE THREAD

**Issue by HubKing** [pdfarranger/pdfarranger#1068]
Describe the bug
----------------
The PDF file's property says that the paper size is JB4, Portrait (257 × 364 mm). If I print the file on A4 sheets with PdfArranger (PA), the right/bottom sides are clipped out. Evince prints it correctly. If I compare the print dialogues of the two apps, there are some missing features in PA's. 

My system's printer is like the capture below.I have only one printer, but two printers appear in the dialogues. I think this is because I enabled CUPS network printer. No matter which of the two I choose, it prints to the same printer.

![image](https://github.com/pdfarranger/pdfarranger/assets/10900489/8c2b6cd5-3436-414c-9673-d8e0da24c72e)

In Evince's dialogue, for "Print to LPR", there is this "page handling" tab
![image](https://github.com/pdfarranger/pdfarranger/assets/10900489/b4286d19-36c2-4012-90d1-a915db0c9b63)

and I can change paper size.

![image](https://github.com/pdfarranger/pdfarranger/assets/10900489/8ec055a3-8c1f-4b01-85e7-fbb3b5efe80b)

In PA's dialogue, for "Print to LPR", there is no "page handling" tab and paper size option is disabled
![image](https://github.com/pdfarranger/pdfarranger/assets/10900489/2fd9bbdb-72bd-4633-9787-76dcd3c982e8)

Also, if I use the printer item with location, Evince remembers the choice and selects that printer as the default one next time. But PA always selects Print to LPR as the default, even if I used the printer with location last time.

To Reproduce
------------

Print a PDF whose paper size is not A4 on A4 sheets.

Expected behavior
-----------------
Printed page fits the paper.

Input files
-----------
Try a PDF file whose paper size is not A4, for example, this: 
[sample.pdf](https://github.com/pdfarranger/pdfarranger/files/14481285/sample.pdf)

System and Versions
-------------------

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...): 1.10.1, Arch official repo.
-   pikepdf version and where you get it (distro package, pip, git, ...) 8.1.3.0
-   OS name and version (e.g.: Windows 10, Fedora 33, ...) Arch Linux, Gnome

**Comment by kbengs** [comment]
Thank you for the bug report. This was recently fixed in https://github.com/pdfarranger/pdfarranger/pull/1042 That should fix all except that it does still not remember the printer settings from last time. If I remember correctly I did not add it to the PR because it did not work on Windows.

The fix will be in next release.

**Comment by dreua** [comment]
@HubKing Thanks for taking the time for this detailed bug report, even with screenshots, I love that! Unfortunately/Fortunately this bug was already reported and thankfully fixed by @kbengs !
