### ISSUE TITLE
Include an option for "size standardization" with differently-formatted pages

### ISSUE THREAD

**Issue by MMachado05** [pdfarranger/pdfarranger#1070]
Describe the bug
----------------

Sometimes I'll have various PDFs of different "sizes," but all of the same dimensions. Saving it as such makes some pages bigger than others, and printing to PDF always cuts off everything that isn't in the top-right.

To Reproduce
------------

Simply add various PDFs of the same dimensions but different sizes (for me, I exported a PDF from RNote and printed to PDF from Kate) into PDF Arranger, then either save or print to PDF.

Expected behavior
-----------------

Something that I feel would be incredibly useful for this use case is an option in the menu like "Apply global format," wherein you would select from some common PDF printing presets, and the pages that you have would be fit to that preset. Pages that already fit the correct dimensions would simply be resized to all be the same on that front, and pages that *don't* fit the correct dimensions would have padding added where necessary to include it (for example, if I wanted to format everything to be letter-sized, and I included a square PNG, white padding on the top and bottom would be added to the top and bottom (or just one, it's kind of immaterial) so that it appeared to have been "drag-and-drop"ped into the pre-existing PDF format.

System and Versions
-------------------

-   PDF Arranger 1.10.1 Flatpak
-   pikepdf 8.11.2
-   Kubuntu 22.04.3 LTS

**Comment by kbengs** [comment]
This sounds very much like #1066 !  This would allow you to fit selected pages to a paper. If you are able to test the open PR and give feedback it's appreciated. Also see #1042 about printing

**Comment by MMachado05** [comment]
I hadn't seen that PR! I'm a bit uninitiated in the ways of testing open PRs, and unfortunately my only available machine is one that I use rather consistently. However, if you can point me in the direction of a guide on how to see this work in action without necessarily breaking the app (it's really useful for assignments!) I'd be more than happy to do so! 😁

**Comment by kbengs** [comment]
This was implemented in #1066
