### ISSUE TITLE
Fatal error on Save

### ISSUE THREAD

**Issue by raph82** [pdfarranger/pdfarranger#1076]
Describe the bug
----------------

The application silently exits on save, without saving.

To Reproduce
------------

1. save attached files locally then select files 25032404.PDF and 25032405.PDF in your file browser
2. right click > Open with PDF Arranger
3. don't even modify anything, just click Save As...
4. enter any valid filename
5. click Save 
6. See error

Expected behavior
-----------------
The two opened files are saved as one under the filename provided. The application stays open.

Input files
-----------

_Check if the bug appear only with some PDF or image files. If the bug is specific to some files please attach one to the issue._
The bug does not appear with only one of these files. It appears with 2 or 3 files put together.
The attached files come from a brother printer.
[25032404.PDF](https://github.com/pdfarranger/pdfarranger/files/14746017/25032404.PDF)
[25032405.PDF](https://github.com/pdfarranger/pdfarranger/files/14746019/25032405.PDF)

Screenshots
-----------
Nothing visual but the console output might be helpful:
```
$ pdfarranger 
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  AttributeError: 'pikepdf._qpdf.Pdf' object has no attribute 'open_outline'

At:
  /usr/lib/python3/dist-packages/pdfarranger/exporter.py(183): check_content
  /usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py(1228): save
  /usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py(1135): choose_export_pdf_name
  /usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py(1211): on_action_save_as
  /usr/lib/python3/dist-packages/gi/overrides/Gio.py(44): run
  /usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py(2605): main
  /usr/bin/pdfarranger(33): <module>

Abandon (core dumped)
$ /usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
It stops right there, the last characters seem to be missing.
I don't know where to find the dumped core. I could provide it with instructions.

System and Versions
-------------------
[Capture d’écran du 2024-03-25 16-28-49](https://github.com/pdfarranger/pdfarranger/assets/14821707/6bf9421e-9390-4cf8-8711-84955a1da77d)
_-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)_
1.10.1, installed in synaptic, probably from the distro package?
_-   pikepdf version and where you get it (distro package, pip, git, ...)_
pikepdf 1.10.3+dfsg from distro?
_-   OS name and version (e.g.: Windows 10, Fedora 33, ...)_
Linux Mint 20.3 based on Ubuntu 20.04 LTS

**Comment by dreua** [comment]
Hi and thanks for the bug report. Just adding some observations for now:
- Could not reproduce with the Fedora Flatpak 1.10.0 (libqpdf 11.6.4, pikepdf 8.8.0, GTK 3.24.41 and Python 3.12.2)
- Could not reproduce with the Flathub Flatpak 1.1.0.0 (libqpdf 11.7.0, pikepdf 8.11.2, GTK 3.24.41 and Python 3.11.8)

I did open those file through PDF Arranger however. Does it matter how you open the files or add it to the PDF Arranger window?

**Comment by kbengs** [comment]
PDF Arranger 1.10.1 does not support that old version of pikepdf. I guess this is either a problem with the deb you have installed (from some PPA?) or you have some kind of configuration issue on your machine. 

PDF Arranger is also available as flatpak on linux mint. Maybe that could be a option for you.

**Comment by raph82** [comment]
_Does it matter how you open the files or add it to the PDF Arranger window?_
No it doesn't matter.

_PDF Arranger is also available as flatpak on linux mint. Maybe that could be a option for you._
Good idea but... that's a 1.1 GB download and a 3.7 GB install, so a not-really-interesting option :wink: (gnome dependency on a Cinnamon desktop I guess).
I installed python3-pip and upgraded pikepdf to version 8.14.0 and the bug disappeared. A few MB each, much more reasonable size.

_Should we add a check for the pikepdf version to catch issues like this earlier in the future?_
If I may, the wording of the README also led to think it should be checked:
_PDF Arranger requires [pikepdf](https://github.com/pikepdf/pikepdf) >= 6_

Thanks a lot for the fast and useful answers :+1:

**Comment by dreua** [comment]
> If I may, the wording of the README also led to think it should be checked:
> _PDF Arranger requires [pikepdf](https://github.com/pikepdf/pikepdf) >= 6_

https://github.com/pdfarranger/pdfarranger/blob/b1aaec95d325a15e1f939093ec89997c96b3e323/setup.py#L124

We have that in the metadata so either pip or apt should have checked that a package satisfying that requirement is installed. This might indicate that the packaging on ubuntu or somewhere is slightly broken, but I don't have time to look further into that tbh. You could raise this as a bug against your distro's package though, maybe the package maintainer can have a look.

We could add an additional runtime check for convenience but that is actually not common practice as it would duplicate the metadata in setup.py and is generally not necessary if all the packaging tools work as expected.

**Comment by dreua** [comment]
On another thought: Is is possible that you had two pikepdfs installed, one as apt package and one via pip (maybe in the user home)? In this case the user installed version may be used rather than the system installed version but apt of course only checks the provides of the deb package, i.e. the system installed version.
