### ISSUE TITLE
Add color filters

### ISSUE THREAD

**Issue by MG-LSJ** [pdfarranger/pdfarranger#1080]
It would be nice to have image/color filters for pdfs like greyscale.

**Comment by dreua** [comment]
I don't feel like investing time on this, as it sounds too specific for me. I wouldn't even expect this software to have such a feature as a user. Let's see if someone else is interested. Thanks for suggesting it, anyway.

As usual:
Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.
