### ISSUE TITLE
How to use "include in the output" and "crop selections" ?

### ISSUE THREAD

**Issue by RENANZG** [pdfarranger/pdfarranger#1081]
Example of scanned book, how to keep the first and last page intact and crop the two irregular sequences (2-3[50%] and 4-5[30%]) separately in batch? How to configure "include in output" and "crop selections" in this case ?

┌─────┐
│ㅤFront │
│ㅤㅤㅤㅤ│
│ㅤㅤㅤ1 │
└─────┘
┌──────────────┐
│ㅤㅤㅤ50%│ㅤㅤㅤㅤㅤ│
│ㅤㅤㅤㅤㅤ│ㅤㅤㅤㅤㅤ│
│ㅤㅤㅤㅤ2 │ㅤㅤㅤㅤ3 │
└──────────────┘
┌──────────────┐
│ㅤ30%│ㅤㅤㅤㅤㅤㅤㅤ│
│ㅤㅤㅤ│ㅤㅤㅤㅤㅤㅤㅤ│
│ㅤㅤ4 │ㅤㅤㅤㅤㅤㅤ5 │
└──────────────┘
┌─────┐
│ㅤBack │
│ㅤㅤㅤㅤ│
│ㅤㅤㅤ6 │
└─────┘

Thanks.

**Comment by RENANZG** [comment]
The magic is to do something like:

![screen-03-04-2024--23h-02m](https://github.com/pdfarranger/pdfarranger/assets/53377291/93777bbf-8478-4413-abe6-b1f9372c9005)

![screen-03-04-2024--23h-03m](https://github.com/pdfarranger/pdfarranger/assets/53377291/e6ae09f1-eb71-4dd9-bdf7-ef527e814c3a)

**Comment by kbengs** [comment]
You can do it by selecting page 2-3 and crop. Then select 4-5 and crop. There is no way to do it in a batch.
