### ISSUE TITLE
Add ability to export single/multiple pages as images

### ISSUE THREAD

**Issue by archisman-panigrahi** [pdfarranger/pdfarranger#1090]
Describe the bug
----------------

Right now, pdfarranger can only export as pdf. Sometimes one has to extract a single file from a pdf and use it in image format.
For that, right now one has to extract the page(s) as pdf and then manually convert them to image format.

Having the option to export as png/jpg will reduce the last step.

To Reproduce
------------

1.  Select some pages
2.  Right click, and click export.
3.  All the exported pages are saved in pdf format. Even if I try to save as `filename.png`, it saves as `filename.png.pdf`.

Expected behavior
-----------------

Step 3 should have some way to produce png/jpg.

Input files
-----------

NA

Screenshots
-----------

NA

System and Versions
-------------------

-   PDF Arranger version and where you get it - 1.10.1, Ubuntu 24.04 APT package
-   pikepdf version and where you get it - 8.7.1 APT package
-   OS name and version - Ubuntu 24.04

**Comment by dreua** [comment]
Hi and thanks for the suggestion! I, however, think that this is a rather niche use case. If you do this on a regular basis there are probably better ways to automate this with some scripting. If anyone wants to work on this feature please let us know :wink: 

As per our usual procedure with such feature requests: Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.

**Comment by dreua** [comment]
Another request in discussions: https://github.com/pdfarranger/pdfarranger/discussions/1145
Feel free to use the :+1: reaction to show interest and Subscribe to get notifications in case there should be any development.

**Comment by mak448a** [comment]
Please reopen this

**Comment by dreua** [comment]
@mak448a Reopening this wouldn't change a thing but clutter the list of "open" features. There are projects with hundreds of open features but most of them are never actually care taken care of, therefore I don't understand the request to "reopen" this. Anyone can comment or leave their :+1:  here, no matter if it is open or closed. For implementation we need someone to implement and maintain the feature on all supported platforms. If someone willing to do that turns up or a relevant discussion takes place here I'm happy to reopen this feature :wink:

**Comment by Heavygrass** [comment]
Hi,
I'd like to request export to PNG/JPG also.
It would be a very usefull feature!
Thanks
