### ISSUE TITLE
First Save on opened file without confirmation

### ISSUE THREAD

**Issue by joef42** [pdfarranger/pdfarranger#1091]
Hello,

In my workflow with documents I frequently open a PDF file, remove or rotate some pages, and then save and close it again. When saving (not with Save As) my changes I always get a File Save dialog and when saving under the same name I have to confirm overwrite. The intuitive behavior when opening a file would be that save just overwrites the already existing file without confirmation, the vast majority of programs behave in that way.

I guess when opening an existing PDF file with PDF Arranger it is rather handled as import into an empty workspace, so on the first Save a filename has to be provided. However, then why are there two options in the Menu for Open and Import? For me they seem to work exactly the same.

Would it be possible to change the behavior so that when opening an existing PDF file, a Save just overwrites the file without confirmation? 

Thanks,
Joerg

**Comment by dreua** [comment]
Please use the search function: See https://github.com/pdfarranger/pdfarranger/issues/65 and https://github.com/pdfarranger/pdfarranger/issues/100

**Comment by dreua** [comment]
Open and import differ aa soon as you have any pages
