### ISSUE TITLE
Failure when generating booklet since pikepdf v9 update

### ISSUE THREAD

**Issue by sotirismorf** [pdfarranger/pdfarranger#1094]
Describe the bug
----------------

When using the "generate booklet" button under edit, nothing happens.
This is because of this error:

```txt
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pdfarranger/pdfarranger.py", line 476, in generate_booklet
    booklet = exporter.generate_booklet(self.pdfqueue, self.tmp_dir, pages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pdfarranger/exporter.py", line 452, in generate_booklet
    file.pages.append(newpage)
TypeError: only pikepdf.Page can be appended to PageList
```

pikepdf v9 release notes: https://pikepdf.readthedocs.io/en/latest/releasenotes/version9.html

Quote from the release notes:

> Pdf.pages no longer coerces PDF dictionaries to page objects. You must explicitly insert/add pikepdf.Page objects

To Reproduce
------------

1.  Open pdfarranger
2.  Open any pdf file suitable for pdf creation (here is a test one: https://api.printnode.com/static/test/pdf/multipage.pdf)
3.  Select all pages with ctrl+a
5.  Click on Main Menu > Edit > Generate Booklet

Expected behavior
-----------------

The pages should be converted to a booklet layout.

Input files
-----------

I have checked with multiple pdf files. Even ones that I remember working in the past.

Screenshots
-----------

N/A

System and Versions
-------------------

`pdfarranger --version` output:

```txt
PDF Arranger-1.10.1
pikepdf-9.0.0
libqpdf-11.9.0
```

Distro: Arch Linux

**Comment by dreua** [comment]
That looks very much like current PDF Arranger is not compatible with the breaking change in pikepdf 9, thanks for the very detailed bug report and further research!

**Comment by dreua** [comment]
The fix was quite simple, you could just edit the export.py file in the meantime if you need a quick fix.
