### ISSUE TITLE
cannot save, export , print on  Ubuntu 22.04.4

### ISSUE THREAD

**Issue by tulliog** [pdfarranger/pdfarranger#1098]
Describe the bug
----------------

cannot save, export , print  a pdf file

To Reproduce
------------

open a  file, try to save, or export or print. 
Nothing happens. 

System and Versions
-------------------

-   1.10.1  from Ubuntu snap
-   pikepdf 7.2.0  (installed via Ubuntu GUI)
-   Ubuntu 22.04.4

**Comment by kbengs** [comment]
Can you start from a terminal and see if you have anything printed there?

**Comment by tulliog** [comment]
> Can you start from a terminal and see if you have anything printed there?

Do you mean , launch  pdfarranger from a terminal ?

**Comment by soumyaDghosh** [comment]
https://github.com/pdfarranger/pdfarranger/issues/1037#issuecomment-1902179875


This seems to be the same issue. This is the fix.
