### ISSUE TITLE
Virustotal Report

### ISSUE THREAD

**Issue by LinuxOpa** [pdfarranger/pdfarranger#1104]
See Screenshot

![Bildschirmfoto vom 2024-06-21 05-48-47](https://github.com/pdfarranger/pdfarranger/assets/41851582/a77f209d-fb27-46e9-b81d-e8fa19dec2aa)

**Comment by kbengs** [comment]
Apparently some of the pdfs that are used in tests that it does not like. Any ideas what to do about that?

**Comment by dreua** [comment]
Please use the search feature here, there are false positives every now and then. Its a waste of time for us, please report that to the antivirus vendors.

> Any ideas what to do about that?

Nothing
