### ISSUE TITLE
Scale pages to fit common page sizes

### ISSUE THREAD

**Issue by moritz89** [pdfarranger/pdfarranger#1109]
Feature Request
----------------

It would be very helpful to have common scale presets when resizing pages. A common occurrence is having scanned images of documents as PDFs without the proper sizing of A4 sheets. The pages can be scaled with the current version, but it is necessary to look up the width/height of A4 and then scale the width/height according to that copied length in mm.

**Comment by kbengs** [comment]
This is under development. See #1066
