### ISSUE TITLE
ModuleNotFoundError: No module named 'dateutil'

### ISSUE THREAD

**Issue by Asbjorn88** [pdfarranger/pdfarranger#1111]
The application does not start.
Initially, I installed it from the app store. Nothing happens at startup in kde. Outputs the following via the terminal:

```
$ pdfarranger 
Traceback (most recent call last):
  File "/usr/bin/pdfarranger", line 5, in <module>
    from pdfarranger.pdfarranger import main
  File "/usr/lib/python3.12/site-packages/pdfarranger/pdfarranger.py", line 118, in <module>
    from .config import Config
  File "/usr/lib/python3.12/site-packages/pdfarranger/config.py", line 25, in <module>
    from .exporter import PrintSettingsWidget
  File "/usr/lib/python3.12/site-packages/pdfarranger/exporter.py", line 30, in <module>
    from . import metadata
  File "/usr/lib/python3.12/site-packages/pdfarranger/metadata.py", line 25, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'
```

reinstalling pdfarranger did not help

System and Versions
-------------------
fedora 40 (kde)

pdfarranger-1.11.0-1.fc40.noarch

installed dependence packages:
poppler-glib python3-pip python3-gobject gtk3 python3-cairo  python3-wheel python3-pikepdf python3-img2pdf python3-dateutil libhandy

**Comment by kbengs** [comment]
I tried Fedora 40 + KDE + pdfarranger in Gnome Boxes and pdfarranger did start fine.
If I run `sudo dnf remove python3-dateutil` I see the same issue as you.
Then if I run `sudo dnf install python3-dateutil` it works again.

How about if you remove and reinstall python3-dateutil ?

**Comment by dreua** [comment]
Tried the same with an older F40 iso, it would not allow me to remove dateutil without also removing pdfarranger. (That is with PDF Arranger installed as Fedora RPM, kbengs might have installed it differently.) Therefore the dependencies look okay to me unless something changed that in the meantime. `rpm -qR pdfarranger` explicitly lists dateutil so I don't think this is an issue with PDF Arranger or the packaging but rather something broken in your installation. Check the directories listed in `python -m site` for missing entries or broken installations. For me in F39 it looks like this:
```
]$ python -m site
sys.path = [
    '/home/da',
    '/usr/lib64/python312.zip',
    '/usr/lib64/python3.12',
    '/usr/lib64/python3.12/lib-dynload',
    '/home/da/.local/lib/python3.12/site-packages',
    '/usr/lib64/python3.12/site-packages',
    '/usr/lib/python3.12/site-packages',
]
USER_BASE: '/home/da/.local' (exists)
USER_SITE: '/home/da/.local/lib/python3.12/site-packages' (exists)
ENABLE_USER_SITE: True
```

**Comment by Asbjorn88** [comment]
> I tried Fedora 40 + KDE + pdfarranger in Gnome Boxes and pdfarranger did start fine. If I run `sudo dnf remove python3-dateutil` I see the same issue as you. Then if I run `sudo dnf install python3-dateutil` it works again.
> 
> How about if you remove and reinstall python3-dateutil ?

It worked. A bunch of dependencies have just been removed:
```
Removal:
python3-dateutil noarch 1:2.8.2-13.fc40 @fedora 878 k
Removing dependent packages:
dnf-plugins-core noarch 4.9.0-1.fc40 @updates 24 k
 pdfarranger                                noarch                   1.11.0-1.fc40                      @updates                   1.1 M
 plasma-drkonqi                             x86_64                   6.1.4-1.fc40                       @updates                   3.3 M
 python3-boto3                              noarch                   1.34.162-1.fc40                    @updates                   2.0 M
Removing unused dependencies:
keditbooks x86_64 08/24/00-1.fc40 @updates 1.4 M
keditbooks-libs x86_64 08/24/00-1.fc40 @updates 126 k
 konsole                                    x86_64                   24.08.0-1.fc40                     @updates                   6.0 M
 python3-botocore                           noarch                   1.34.162-1.fc40                    @updates                    93 M
 python3-dnf-plugins-core                   noarch                   4.9.0-1.fc40                       @updates                   1.2 M
 python3-jmespath                           noarch                   1.0.1-6.fc40                       @fedora                    149 k
 python3-psutil                             x86_64                   5.9.8-1.fc40                       @fedora                    1.4 M
 python3-pygdbmi                            noarch                   0.11.0.0-3.fc40                    @fedora                    139 k
 python3-s3transfer                         noarch                   0.10.2-1.fc40                      @updates                   624 k
 python3-sentry-sdk                         noarch                   2.13.0-2.fc40                      @updates                   2.3 M
```

**Comment by dreua** [comment]
Slightly off topic fedora support: It would have been better to use `dnf reinstall python3-dateutil` because it does not remove any dependent packages or unused dependencies. If in doubt it is safer to say "no" when dnf asks you if you are sure to uninstall all those packages and look for a better way. You may or may not have removed some useful or necessary packages here: dnf-plugins-core sounds quite useful, I don't know what drkonqi and boto3 is. You may want to install those again. The cleanest and safest way might be to undo the your remove operation: Use `sudo dnf history` to find the ID of the operation and then `sudo dnf history undo your_id`. PDF Arranger should continue to work because dateutil is still effectively reinstalled.

Btw did you use `sudo pip` or any other Python managing tools as root (with sudo)? I would strongly recommend against doing any pyhon package managing with sudo and leaving the system python packages to be installed only through dnf. (It is a bit of a learning curve, I admit, but in the end everything makes more sense and works better if you do it the right way.)
