### ISSUE TITLE
Unable to change intial page view property

### ISSUE THREAD

**Issue by tuaris** [pdfarranger/pdfarranger#1113]
Describe the bug
----------------

When merging PDF files, sometimes it will open to the incorrect page.  We need a way to adjust this property.

To Reproduce
------------

1.  Using the UI, open at least 2 PDFs
2.  Drag pages from one file into the other to merge as a single file
3.  Save as new PDF
4.  Open PDF with Adobe Reader, observe it open to a page other than the first.

Expected behavior
-----------------

There should be an option in the UI to select which page the PDF should open to.  Or the property should be reset when merging files.

System and Versions
-------------------

-   PDF Arranger version and where you get it: 1.11.0 Github
-   pikepdf version: It uses libqpdf 11.6.2, pikepdf 8.5.0, GTK 3.24.39 and Python 3.11.6.
-   OS name and version: Windows 10 LTSB 2021

**Comment by dreua** [comment]
I never saw this issue, could it be that this is a property specific to Adobe reader and ignored / unsupported by most other PDF viewers? (I won't install Adobe Reader just to try and reproduce this, sorry.) Furthermore, does it happen with all PDFs or just specific ones?

As it stand now I don't feel inclined to work on this but if someone were to provide a simple PR addressing it - I guess just clearing the property should be fine - we could consider it.

Let's give this 4 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.
