### ISSUE TITLE
pikepdf >=3 needed for overlay/underlay/merge support

### ISSUE THREAD

**Issue by lsces** [pdfarranger/pdfarranger#1130]
(try again ...)
Describe the bug
----------------

When trying to merge two pages I get a complaint about pikepdf

To Reproduce
------------

Steps to reproduce the behaviour:
1.  Select two pages to join
2.  Right click and select 'Merge Pages'
3.  See warning

Expected behaviour
-----------------

Two A4 pages become one A3 page ...

Input files
-----------

Have not found any change in response based on source file used.

Screenshots
-----------

![PDFArrangerPopup](https://github.com/user-attachments/assets/acb59398-3aa0-451b-a6cc-7128628e2373)

System and Versions
-------------------
Had a little panic here ... checking things out I found the link to load 1.11.1, but that stopped it working at all. pip does not show it as installed currently as I've used version 1.10.0 in the openSUSE package manager. 

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)
1.10.0 from openSUSE-Leap_15.6-1 ... while some apps are from flatpak I don't think this is
-   pikepdf version and where you get it (distro package, pip, git, ...)
pip is reporting version 9.3.0 and showing it located in my .local/lib/python3.11/site-packages
-   OS name and version (e.g.: Windows 10, Fedora 33, ...)
openSUSE-Leap_15.6 with KDE Plasma 5.27.11, KDE Framework 5.27.11 and Qt 5.15.12 

I have had to install a number of libraries out of kilter with openSUSE-Leap 15.6 in order to get some other parts working, but ocrmypdf uses pikepdf and is running nicely as is PDF Arranger on the whole.

**Comment by dreua** [comment]
Thanks for the bug report!

As you are on Linux, could you try running `pdfarranger` from a command line and see if it it prints any additional information when the error occurs?

If you just want a quick workaround, the flatpak should just work.

Please check the "About" screen (bottom of the burger menu) if it shows the same pikepdf version. We had our share of issues due to multiple pikepdf versions being installed. While you're at it please also post the libqpdf version listed there.

**Comment by dreua** [comment]
This error message has been removed in 51dd9634e774092054c19c67a7dfd34bcb2fd281 because support for pikepdf < 6 has been dropped. It would be helpful if you could try this with 1.11, maybe ask the package maintainers if they can updte the package for opensuse.

**Comment by lsces** [comment]
OK now know what is wrong but not how to fix it :)
pdfarranger is running with python3.6 which is hitting an older version of pikepdf 
From about box "It uses libqpdf 10.3.1, pikepdf 2.12.1, GTK 3.24.39 and Python 3.6.15"

Just for the record command line give
(pdfarranger:9765): Handy-WARNING **: 15:29:10.028: Using GtkSettings:gtk-application-prefer-dark-theme together with HdyStyleManager is unsupported. Please use HdyStyleManager:color-scheme instead.
But it runs ...
/usr/lib/python3.6/site-packages/pdfarranger/

So when I tried to install 1.11.1 via pip it then stopped working but I would have thought that pip should install in python 3.11 setup and it should still be possible to run the 3.6 copy. I just need to be in the right folder when running it? 

NOW that I know where things are I'll reload 1.11.1 again ...

**Comment by lsces** [comment]
OK have pdfarranger 1.11.1 running on openSUSE Leap 15.6 ... and the 1.10 version is still running ... so just need to get the menu to use the right copy. 
From about box - It uses libqpdf 11.9.1, pikepdf 9.3.0, GTK 3.24.39 and Python 3.11.10 

The error that stopped it running first time I tried was to do with 'gi.repository.Gdk', and adding python3.11-gobject-Gdk proved a winner. Not sure that I totally understand what is going on, but I have two off four A4 page inserts. Alignment could be better but it's close enough. 

Thanks for the pokes ...

**Comment by dreua** [comment]
Alright, sounds like your environment was a bit messed up. I'd remove those old Python versions altogether if possible (2 years out of security support and no point having them around). And my guess would be that your default python (check `python --version`) just points to Python 3.6. PDF Arranger uses whatever "python" is default on your system. Please get in touch with the openSUSE community if you need more help with that or check the documentation.
