### ISSUE TITLE
Inconsistent handling of password-protected PDFs 1.11.x vs 1.10.0

### ISSUE THREAD

**Issue by digidigital** [pdfarranger/pdfarranger#1144]
Describe the bug
----------------

Up until version 1.10.0 we used PDF Arranger to decrypt encrypted PDF documents. 
Open encrypted file with password -> Export file / Save as = Exported PDF is not encrypted 

Since version 1.11.0, PDF Arranger saves PDF files with the password of the first imported/opened file if the first imported file was encrypted. I did not see this mentioned in the release notes. This “magical” behavior may be useful when working with only one document, but it can be confusing when working with different documents, wanting to save unencrypted documents or wanting to change the password / PDF restrictions of a PDF document, as there are no settings to configure the export settings.

To Reproduce
------------
Please always restart PDF Arranger 1.11.1 prior to testing any of the following scenarios: 
-> If you import an **unencrypted file first** the exported documents are not encrypted even if you import encrypted documents later.
-> If you import two encrypted documents, the **password of the document imported first is used for the export,** even if you change the order of the pages so that the pages of the document imported later appear first.
-> If you import a unencrypted PDF document first and encrypted documents later the export is always not encrypted
-> If you add a blank page to an empty PDF Arranger window, delete it and then import an encrypted PDF the export has no encryption 
-> Open document that is not encrypted and delete all pages - import an encrypted document in the now empty PDF Arranger window. Exported document is encrypted and has the password of the first document you opened  

Expected behavior
-----------------

Same as 1.10.x: Saved PDFs are not password protected.

Future feature: Add password settings (and maybe file restrictions) to document settings / options menu (or at least an option "Keep encryption / document restrictions of first imported document) 

System and Versions
-------------------

-   PDF Arranger Portable Windows versions 1.10.0 + 1.11.0 + 1.11.1 (Github releases)
-   Windows 10

**Comment by dreua** [comment]
Probably a side effect of #462 that was unintended. I never work with encrypted PDFs.

**Comment by digidigital** [comment]
Maybe the lines following the comment "We are treating files [0] as the main document"?

pdfarranger/exporter.py

458-461

                   "range": str(page.npage)}
    if len(files[page.nfile - 1][1]) > 0:
        pages_entry["password"] = files[page.nfile - 1][1]
    json["pages"].append(pages_entry)


462-476

    def _create_job(files: List[List[str]], pages: List[Page], files_out: List[str], quit_flag=None,
                    test_mode: bool = False):
        """ Same as _copy_n_transform, except it use the pikepdf Job interface. Requires pikepdf >= 8.0 """
        # Generate the output PDF file including temporary overlay/ underlay pages. We don't need to call
        # _append_page as the Job interface copies pages / annotations as necessary. We can also delay getting
        # our MediaBoxes until the transformation stage.
        json = dict(outputFile=files_out[0], pages=[], removeUnreferencedResources="yes")
        if test_mode:
            json.update(qdf="", staticId="", compressStreams="n", decodeLevel="all")
        if len(files) > 0 and len(files[0][0]) > 0:
            json["inputFile"] = files[0][0]  # We are treating files [0] as the main document
            if len(files[0][1]) > 0:
                json["password"] = files[0][1]

**Comment by m-holger** [comment]
Preserving encryption is qpdf's default behaviour. If this is not desired, it can be disabled by adding a line
```python
json["decrypt"] = ""
```
to `_create_job` in exporter.py. This qpdf functionality is not intended to be used for bypassing copyright restrictions or other restrictions placed on files by their producers.

**Comment by dreua** [comment]
Thinking some more about PDF encryption (see https://github.com/pdfarranger/pdfarranger/issues/257#issuecomment-2461743241) I'd argue that we should go back to the 1.10 behavior. I see no point in PDF encryption in general but allowing people to import encrypted PDFs may stay as a courtesy since it doesn't cost us anything to keep it. Export should be always unencrypted because you could bypass it anyway (start with a different PDF and add the encrypted one to it).

**Comment by m-holger** [comment]
One thing to keep in mind when deciding whether to remove encryption unconditionally is that it will also remove all access restrictions, which may not be what the user wants, e.g when modifying their own document.

If making removal optional, e.g. by displaying a popup dialogue, careful wording is important, as many users associate encryption with password protection, and assume that a messages about encryption for a file that can be read without a password must be a bug.

**Comment by digidigital** [comment]
The current behavior is definitively not intuitive and therefore should be changed back to the previous state. 

The suggested popup would not solve the issues with:
- Import of two password protected documents
- Import of not encrypted file first - encrypted file(s) later

I assume that you would have to implement dialogs for those cases as well. When I think about the average users I know that would lead to frustration (if they read popups & understand what's written in the popups at all).

There are use cases for encryption and I think it would be a great addition to PDF Arrangers feature set.
Since the functionality of encryption / decryption is already there -> If you keep it it should be supported by proper configuration settings in the main menu. Then you could popup-ask to update the encryption settings with the settings of the file that the user is about to open/import if he opens/imports any encrypted PDF.
The "document restrictions" are not enforceable anyway and it is up to the application that displays the document to follow them or not. 
https://github.com/pdfarranger/pdfarranger/issues/257#issuecomment-2466161747

**Comment by m-holger** [comment]
> The suggested popup 

To clarify, I am not suggesting an approach. I am merely raising considerations that I feel may not be immediately obvious.

> The suggested popup would not solve the issues with:
> 
> - Import of two password protected documents
> - Import of not encrypted file first - encrypted file(s) later

Afaik, pdfarranger takes the encryption settings from the first file only. The first file is treated as the file being edited, and pages are imported into this file from other files. This is the reason why, for example, bookmarks/outlines from the first file are preserved but currently lost from the imported pages (although hopefully this will change mid-2025). 

> The "document restrictions" are not enforceable anyway and it is up to the application that displays the document to follow them or not.

PDF works largely because it is a standardised format. By definition, every compliant reader enforces the document restrictions.

**Comment by StefRe** [comment]
I added a config option to restore the old behavior of 1.10.0:
![grafik](https://github.com/user-attachments/assets/0a8c9fa4-337c-42d0-a3a2-daf774f0ab8a)

Default is unticked; if ticked saving works as in version 1.10.0. This checkbutton is only present if pikepdf version is 8 or newer.

@dreua @kbengs : if you like it I will make a PR. A menu item to just remove passwords at saving (but keeping outlines etc.)  can be added later if someone needs it (see https://github.com/pdfarranger/pdfarranger/pull/1150#issuecomment-2495446019).

**Comment by kbengs** [comment]
I think a PR for that would be fine. Maybe remove the word "Don't" and have it checked by default.

Related to this is #257 How about a GUI where you could set a password or set to reuse the password from first document? Maybe just keep it simple and not implement all the options suggested in 257. I haven't looked into it at all so I don't know how much work it would be. Just mentioning in case you @StefRe are interested.

**Comment by rugk** [comment]
Thanks a lot. Thanks to this issue, I found out how to solve that actual use case aka "How to remove a password from a PDF". I knew, this must be available with PDF Arranger. 🙃 

That said, I think if you have that use case finding [that really technically worded option](https://github.com/pdfarranger/pdfarranger/issues/1144#issuecomment-2499125622) (that does not even mention the word "password"), is not really obvious. 🙃

**Comment by kbengs** [comment]
Current main has a "Password" dialog. You can reuse password from first document, set a new or remove the password.
