### ISSUE TITLE
cannot open xsane scans

### ISSUE THREAD

**Issue by itcsh** [pdfarranger/pdfarranger#1159]
pdfarranger (1.10.0) cannot read xsane (0.999) scans
----------------

The bug is: 
Since my last openSuse Leap version update, pdfarranger (1.10.0) cannot read xsane (0.999) scans any more. In former installations this issue did not occur.

Instead of opening a file, that was created by xsane, pdfarranger displays a message box, telling the file be damaged.

Ocular instead can display those files.
Maybe xsane has format errors, some pdf readers can deal with?
Or it produces a new format, not (yet) supported by pdfarranger / pikepdf ?

To Reproduce
------------

1. Create a pdf scan with xsane 0.999 in OpenSuse Leap 15.6, KDE environment.
2. Double click on the file to open it with your standard PDF reader.
3. The file should be displayed correctly.
4.  Tell pdfarranger to open that file (e.g. by drag and drop).
5.  See error message.

Expected behavior
-----------------

Pdfarranger should display the file like it does with files from other origins.

Input files
-----------

Check if the bug appear only with some PDF or image files. If the bug is specific to some files please attach one to the issue.
The pdf file I attached, is the scan of an empty page, created as described above:
[2024.12.04.testFileForPdfArranger.pdf](https://github.com/user-attachments/files/18007864/2024.12.04.testFileForPdfArranger.pdf)

Screenshots
-----------

The attached image shows pdfarranger's error message.
![Screenshot_20241204_131227](https://github.com/user-attachments/assets/e09115e8-90fa-4c59-8e9c-766a2589585e)

System and Versions
-------------------

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)
1.10.0-bp156.1.1, distro package from download.opensuse.org

-   pikepdf version and where you get it (distro package, pip, git, ...)
python3-pikepdf 2.12.1-bp156.3.5, distro package from download.opensuse.org

-   OS name and version (e.g.: Windows 10, Fedora 33, ...)
openSuse Leap 15.6 with KDE plasma desktop

**Comment by dreua** [comment]
```
$ file 2024.12.04.testFileForPdfArranger.pdf 
2024.12.04.testFileForPdfArranger.pdf: PNG image data, 2448 x 3422, 8-bit grayscale, non-interlaced
```

This looks like a png file with a pdf filename. Try changing it to png then the image import logic should kick in.
My firefox and the gnome pdf viewer also had issues with it.

**Comment by itcsh** [comment]
@dreua 
Thanks a lot. Should have had the Idea to use _file_ on my own. In my version, pdfarranger can't read image files, but that's no issue, as there are conversion tools...

**Comment by dreua** [comment]
You probably just need to install something like python3-img2pdf and it should work. Ideally that would be a dependency or at least an optional dependency of the pdfarranger package on opensuse. Forwarding this information to the package maintainers there would improve the packaging and user experience on opensuse :wink:
