### ISSUE TITLE
PDF Arranger becomes the default application for other users to open PDF in Ubuntu24

### ISSUE THREAD

**Issue by vepain** [pdfarranger/pdfarranger#1160]
Describe the bug
----------------

Since I have installed PDFArranger, it becomes the default PDF application for other users on Ubuntu24

Note: I first think it was related to VSCode, but I did'nt find anything about VSCode default application for PDF, so I continue to investigate. I'm not sure it is related to PDFArranger from flatpak.

To Reproduce
------------

Steps to reproduce the behaviour:
1. Install PDFArranger from flatpak
2. Install VSCode
3. Install pandoc vscode extension 
4. Create a new markdown file
5. Export this MD file with pandoc in PDF
6. Wait the produced PDF file opens in PDFArranger

You can also observe this behaviour if you use the LaTeX workshop VSCode to open CTAN documentation with `texdoc --view package_name`, it will use  PDFArranger, while if you call this command directly via a terminal, it will open your default application for PDF (evince). 

Expected behavior
-----------------

I expect my default application (evince) still opens PDF by default

System and Versions
-------------------

```sh
$ flatpak list | grep arranger
PDF Arranger	com.github.jeromerobert.pdfarranger	1.11.1	stable	system
```
-   Ubuntu 24.04

**Comment by vepain** [comment]
Temporary fix: change default application for all the users.

```sh
sudo touch /etc/xdg/mimeapps.list
sudo open /etc/xdg/mimeapps.list
```

Write in `/etc/xdg/mimeapps.list`

```ini
[Added Associations]
application/pdf=org.gnome.Evince.desktop
```

Save.

**Comment by dreua** [comment]
PDF Arranger's metadata advertises that it can open PDFs of course, that is intentional and important so that it can show up in the "open with" list of PDF files. It becoming the default is not in our control and probably a bug somewhere else (flatpak, VS Code...?).
I haven't heard of this issue before. As a workaround you could try installing the flatpak as a user `flatpak install --user ...` instead of system wide.

**Comment by vepain** [comment]
Thank your for your answer, I will close this issue.
