### ISSUE TITLE
`Right-Click on PDF > Open With` is not showing "PDF Arranger"

### ISSUE THREAD

**Issue by Lonniebiz** [pdfarranger/pdfarranger#1170]
I installed PDF Arranger (version 1.11.1) on Windows 11 (for all users of a workstation) with this winget command, in an (admin) Powershell:

`winget install PDFArranger.PDFArranger --scope machine --source winget`

While this did successfully install PDF Arranger, when a user right-clicks on a PDF file and goes to the `Open With` context-menu option, PDF Arranger isn't listed there by default for my users. To remedy this I copied and pasted this into a Powershell as admin:

```
# Define the application path for PDF Arranger
$appPath = "C:\Program Files\pdfarranger\pdfarranger.exe"

# Define the registry path for adding the "Open with PDF Arranger" option for PDF files
$RegistryPath = "HKLM:\SOFTWARE\Classes\PDFArranger.PDF\shell\Open with PDF Arranger\command"

# Create the registry keys if they do not exist
if (-not (Test-Path $RegistryPath))
{
    New-Item -Path $RegistryPath -Force | Out-Null
}

# Set the default value for the command to open PDF files with PDF Arranger
$Command = "`"$appPath`" `"%1`""
Set-ItemProperty -Path $RegistryPath -Name "(Default)" -Value $Command

# Register the new handler under the .pdf file association
$FileAssociationPath = "HKLM:\SOFTWARE\Classes\.pdf\OpenWithProgids"
if (-not (Test-Path $FileAssociationPath))
{
    New-Item -Path $FileAssociationPath -Force | Out-Null
}

# Add the new file association for PDFs with PDF Arranger
New-ItemProperty -Path $FileAssociationPath -Name "PDFArranger.PDF" -PropertyType String -Value "" -Force | Out-Null

```

**This issue requests that the PDF Arranger installer automatically register itself as a PDF file handler during Windows installation.**

This issue also requests that the application's menu entry be changed:

![2024-12-19_04-32](https://github.com/user-attachments/assets/88b37bb7-2a7c-49a1-a36b-7e166ad4a502)

See where it says: "A simple application for PDF Merging, Rearranging, and Splitting" ?

That should probably be either "PDF Arranger" (by itself) or "PDF Arranger: A simple application for PDF Merging, Rearranging, and Splitting". Typically, (as you can see from other entries in that menu) it would just be the application's name alone.

The commands I provided above do not control the text shown in the screenshot above. That's likely coming from a registry entry added by the PDF Arranger installer or by the [package metadata provided to winget](https://github.com/microsoft/winget-pkgs/issues/199790).

Personally, I don't mind the length of the entry you're seeing in the menu above, but I do think that it should first say "PDF Arranger:" prior to that pertinent description.

In closing, I want to thank the developers of PDF Arranger. I've been using it for years on Linux, but only recently discovered it was cross-platform, and I'm very happy to extend its goodness to all my users. In my opinion, the application was very well done and ought to be on every business computer in the world!

**Comment by StefRe** [comment]
I installed the portable version 1.11.1 on Windows 10 by just unzipping it into a user folder. This of course doesn't register anything. If I then manually add the file exension association (not sure what's the correct term here) by:
![grafik](https://github.com/user-attachments/assets/bfe43810-9c4b-4e7a-88ae-a46f39bf4a86)  

I get the same verbose entry:  

![grafik](https://github.com/user-attachments/assets/ad477018-d25f-48eb-984a-d819f68373ec)

So it doen't seem to be a matter of the installer but of the package metadata itself. Will try to find out later where exactly the menu entry is taken from.

**Comment by StefRe** [comment]
What is shown here (on Windows) is the `.FriendlyAppName` from the MUI cache. This name is obviously taken from the [`StringFileInfo`  `BLOCK`](https://learn.microsoft.com/en-us/windows/win32/menurc/stringfileinfo-block) of the `VERSIONINFO` resource. So maybe in `setup_win32.py` we should put the existing description into [`long_description`](https://cx-freeze.readthedocs.io/en/stable/keywords.html) and change `description` to `PDF Arranger`.

**Comment by StefRe** [comment]
This indeed does the trick:
![grafik](https://github.com/user-attachments/assets/509a229e-30ff-4228-bbf4-a9a34527b984)

**Comment by dreua** [comment]
I just created #1190 which should fix the rest of this.

**Comment by dreua** [comment]
Maybe I just mixed up Linux and Windows and it was never in the Windows "Open with" menu to begin with 🤔  At least I couldn't find an older version where it shows up nowadays but it could still be a change in Windows we are not aware of.
