### ISSUE TITLE
Simple enhancements

### ISSUE THREAD

**Issue by darkdragon-001** [pdfarranger/pdfarranger#13]
I have some simple adjustments but it would take me some time to get to know Gtk framework to implement this myself.

1. ~Shift+click consecutive pages instead of rectangular selection _([sf](https://sourceforge.net/p/pdfshuffler/bugs/45/))_
   _[explanation with images](https://gitlab.gnome.org/GNOME/gtk/issues/1227)_~
2. Drag should move ALL selected pages _([sf](https://sourceforge.net/p/pdfshuffler/bugs/46/), [savannah](https://savannah.nongnu.org/bugs/index.php?54822))_
   _Select multiple pages, drag to different position -> should drag all selected pages and not only one._
3. Option to duplicate page(s) _([sf](https://sourceforge.net/p/pdfshuffler/bugs/47/), [savannah](https://savannah.nongnu.org/bugs/index.php?54823))_
   _Add a right-click option to duplicate selected page(s)._

**Comment by jeromerobert** [comment]
* shift click is implemented in 704af98380b5c86977bb870159c015cb406d8f39 by @julianfoad
* please don't put multiple feature requests in the same issue
