### ISSUE TITLE
Duplicate Buttons in Hamburger Menu

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#168]
First of all I have to say, that the new design looks really cool, great work!

I first noticed it with the Zoom buttons but actually I think all function buttons of the top bar are duplicated in the "hamburger menu", is this intentional? Some of those are also in the context menu, I don't think "Three time's the charm" applies in this case :wink: 

Just had a quick glance at Evince and Gedit and they don't seem to have duplicate function buttons at all.

**Comment by jeromerobert** [comment]
Yes that was intentional, but I had my doubts about it, so thank you for raising that issue. I suggest to remove the edit menu entirely as all function are also in the context menu.

The actions in the toolbar does not show the shortcuts so I think they should be also in a menu. So I would keep zoom in the hamburger menu because it's the only way to know about the +/- shortcuts. 

Evince and Gedit have a ShortcutsWindow so they don't have that constrains. I prefer to see shortcuts in the menu.

**Comment by dreua** [comment]
> I prefer to see shortcuts in the menu.

I totally agree and that of course explains the duplicated entries.

Just had the idea to display the shortcuts in the mouse over tool tip, have you considered this? (I think I saw that in PyCharm.)

For the edit sub-menu: For me personally it can go, but I'm not sure if it is a wise idea. I'm afraid that there might be people who don't come up with the idea to right-click and therefore miss out on some critical functions. Looking closer at Gedit, Evince and Nautilus, I see that the context-menus usually contain a mix of power-user functions that you don't necessarily need and - correction of my previous statement - duplicates of functions that are otherwise accessible (e.g. Move to Trash in Nautilus can be done by dragging to trash).

**Comment by jeromerobert** [comment]
Ok let's keep this open for now. I will let it as it is for 1.5.0. I'll just remove the Quit menu item.

Having accelerators in the toolbar tooltips is a good idea. I should be able to implement it programmatically so we do not have to change .ui and translation files. But that will also be for 1.5.x or 1.6.0.

**Comment by jeromerobert** [comment]
Well gedit and evince have a Ctrl+Q shortcut so I'll keep the Quit menu item for now.

**Comment by dreua** [comment]
@jeromerobert After your explanation and realizing that duplication is common in Gnome apps I don't see the need for action here any more. Do you still want to implement accelerators in tooltips and this issue as a reminder or is this just a stale issue that we can get rid of?

**Comment by jeromerobert** [comment]
It's a stalled issue.
