### ISSUE TITLE
Handle setlocale failing with "locale.Error: unsupported locale setting"

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#196]
In cases where setlocale fails pdfarranger does not start at the moment. Examples for this happening:
 - https://github.com/jeromerobert/pdfarranger/issues/193 (KDE allows the user to set a locale that works in KDE/Qt apps but it is not available for other frameworks like C, Python, the `locale` command, Bash...)
 - https://github.com/flatpak/flatpak/issues/3514 (Flatpak does not install the .Locale subpackage for all needed locales if you have a mixed locale.)

I'm undecided if we should catch this error and fall back to a default (C or en_US or don't set anything at all?) or leave it as is. 

**Disadvantage of current behavior**
User can't use pdfarranger at all until locale issue is fixed.

**Disadvantage of catching and going with default**
User does not notice that their locale is messed up.
User gets an untranslated UI despite translation being available. User will assume that there is no translation and might be unable to use the application due to language barrier.

**Comment by dreua** [comment]
> I'd really appreciate if someone could fix this at the source (KDE's locale selection I think) but until then I'd say we just do it like everyone else and go with a try/except, print a warning message if setlocale fails and be done with it.

*- me on #304*

**Comment by darkdragon-001** [comment]
@jeromerobert Would be awesome if this could be packaged into a release such that I can finally start using the Flatpak version without hacks on my system...

**Comment by jeromerobert** [comment]
@darkdragon-001 1.7.0 will be released soon. Please test master if you can.
