### ISSUE TITLE
img2pdf does not allow images with alpha channel

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#226]
> Input images with alpha channels are not allowed. PDF only supports transparency using binary masks but is unable to store 8-bit transparency information as part of the image itself. But img2pdf will always be lossless and thus, input images must not carry transparency information.
*https://gitlab.mister-muffin.de/josch/img2pdf*

This image is both, result of this limitation and resource to reproduce it (drag and drop into pdfarranger >= 1.6):
![Screenshot from 2020-07-16 14-30-16](https://user-images.githubusercontent.com/15114715/87690826-36fa2980-c78a-11ea-90f0-4454987404d4.png)

Most JPEGs don't have an alpha channel but many if not most PNGs do.

**Comment by mimi89999** [comment]
What's exactly the issue here? What should pdfarranger do in this case?

**Comment by dreua** [comment]
I'm worried that users will be unhappy if they want to add images to PDFs and it just won't work in many cases. You can't easily tell if an image has an alpha channel and I suspect that not all users will even know what an alpha channel is let alone how to remove it.

Ideally pdfarranger could offer users a solution in this case by removing the alpha channel. If we wanted to go this route there are two options: Keep the pixel colors (may reveal formerly hidden information) or set a background color that shines through the alpha. I'd assume most pdfarranger users intend to print on white paper, so merging the image with a white background in order to remove alpha would be reasonable. That being said, we could also got with whatever is easier to implement.

**Comment by jeromerobert** [comment]
This is what Josh explains here https://gitlab.mister-muffin.de/josch/img2pdf/issues/54 . Hopefully we'll find a way to do it without creating any intermediate files. The issue is that we need PIL[low] to remove the alpha channel and that img2pdf does not seems to exhibit in it's APO that it's using it internally.

**Comment by jeromerobert** [comment]
Done by @rpbritton (thanks !) in ed030e0
