### ISSUE TITLE
Reverse order by pack of n

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#236]
Hi.

Your application has nice feature to split (divide) page(s) at middle vertically. This is very useful with scanned PDF with each tow faced pages being scanned together per each scanned image.

However, currently, it has no "Right to Left" support ! This make this nice feature useless with Arabic & Hebrew language PDF ...

Kindly, can you add support for "Right to Left" arrangement ?

**Comment by jeromerobert** [comment]
Would a "reverse order 2 by 2" action be enough ? If not please provide an example of what you expect.

**Comment by Nokia808** [comment]
@jeromerobert 
I did not understood what you mean by "reverse order 2 by 2". Can you, kindly, explain ?

**Comment by jeromerobert** [comment]
page 1, page 2, page 3, page 4, page 5 => page 2, page 1, page 4, page 3, page 5.

**Comment by Nokia808** [comment]
@jeromerobert 
You mean introducing a master (global) right to left arrangement option ? If this what you mean then it is okay & may be better because it will be more global as the thumbnail will appearing so that page 1 on right then page 2 to it's left & so on ..... Is this what you mean ?

**Comment by Nokia808** [comment]
@jeromerobert 
Dear the needed from this issue is the following:
suppose I apply vertical split at page A then the output will be - currently - page A1 (left half of A) & A2 (right half of page A) arranged as A1, A2. This is okay for Latin PDF not for Arabic or Hebrew. For Arabic & Hebrew output should arranged as A2, A1

**Comment by jeromerobert** [comment]
Ok so that what I mean. Adding a new action "reverse order 2 by 2" (I'm not sure about the actual wording) which you may call after splitting would solve you issue.

**Comment by Nokia808** [comment]
@jeromerobert 
Dear why you like to name it as "reverse order 2 by 2" ? This may be okay technically but it is not clear for almost all end users !
The best is to name it as "Split Page Right to Left" & should be bellow the current "Split Page" option, so that the right click list will be as following:

- Delete
- Cut
- Copy
- Past After
- Past Special
- Rotate Left
- Rotate Right
- Crop
- Duplicate
- Reverse Order
- Split Page
- Split Page Right to Left
- Export Selection...

This way, it will be very clear !

**Comment by jeromerobert** [comment]
No because "reverse order 2 by 2" would be a new action which would be used after "split page" in your case but may also be used in other cases. This approach is more generic that having a "Split Page Right to Left".

**Comment by Nokia808** [comment]
@jeromerobert 
Okay if it has other case to be used in.
But please keep in mind that user may need to apply "Split page" for selected page(s) not for all pages of the PDF. So, the new option of "reverse order 2 by 2" should be designed so that user can apply it on selected page(s) also.

By the way, is the "Split Page" option currently present a real split of page into 2 or just a visual play in the way by which visible area of PDF is seen by the viewer ?

Thank you for your patient with me.

**Comment by jeromerobert** [comment]
"Split page" currently duplicate the page and change each page boundary so they look as if they were splitted. So, unfortunately, the PDF is expected to double in size.

**Comment by jeromerobert** [comment]
To be confirmed but I guess that it's already possible to do that with select odd/even and past interleaved.

**Comment by angsch** [comment]
@jeromerobert  I agree with you if you want to restrict the feature to work on all pages, not just a selection.

**Comment by Nokia808** [comment]
@jeromerobert 
You are aggressive & of bad ethics. I will delete your dirty application & will never install it again.
Also, I will close all feature request that I opened on this repository.

You are make like new nazi

**Comment by Nokia808** [comment]
@jeromerobert 
The last comment from me in this repository before leave it.
You said "I don't trust you when it comes to asking for useful feature requests."

I recommend you to visit a provisional psychiatrist to treat your paranoid personality disorder !!!
