### ISSUE TITLE
Add "Export selection to individual files"

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#240]
Hi. Currently the "Export selection" option working to export all selected page into single output PDF.

Can you, kindly, added option to "Export selection" into individual PDF files (each selected page should exported into independent PDF file) ?

**Comment by jeromerobert** [comment]
Again a pdfmixertool feature. Probably easy to implement.

**Comment by jeromerobert** [comment]
Done in 53448e9

**Comment by Nokia808** [comment]
@angsch
@jeromerobert 
Thank you too much for your efforts !
