### ISSUE TITLE
"Edit properties" window is minimized by default without "maximize" option at it's upper right corner

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#242]
As title saying ... 

It will be more convenient to add "maximize/restore down" icon option to upper right corner of this windows, so that will have 3 icons: - + x

Even the current minimized default windows should be increased in size ...

**Comment by jeromerobert** [comment]
There is no maximize/restore buttons in Gtk.Dialog, that's life. The default window size is calculated to display the content of all properties, so it's big enough.
