### ISSUE TITLE
Allow to change white (empty) margine areas within already visible area of page

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#247]
Kindly, do not confuse this with cropping feature !

I'm talking about empty areas at margins of page WITHIN visible area of page that can be determined by cropping functionality ...

The user should be able to determine the following:

-  Top,
- Bottom,
- Left,
- Right

in cm/mm/inch/ppt units

**Comment by jeromerobert** [comment]
Any idea on how to do that with pikepdf or qpdf ?

**Comment by Nokia808** [comment]
@jeromerobert 
Hi. I answer this - see https://github.com/jeromerobert/pdfarranger/issues/246

**Comment by jeromerobert** [comment]
We should allow negative crop (i.e extends), and crop/extends by mm percentage. Is that what you want ? (please be **SHORT**)

**Comment by Nokia808** [comment]
@jeromerobert 
Dear I'm not a programmer & I do not know by what I should answer you about your last question !

**Comment by Nokia808** [comment]
@jeromerobert 
I think this feature is already implemented in PDF Mix Tool, isn't it ? - see bellow screenshot (red elliptic marker) :

![white-margins](https://user-images.githubusercontent.com/25375330/89255248-c7e95580-d610-11ea-91b2-95a62ce27041.png)

**Comment by Nokia808** [comment]
@jeromerobert 
You are aggressive & of bad ethics. I will delete your dirty application & will never install it again.
Also, I will close all feature request that I opened on this repository.

You are make like new nazi

**Comment by Nokia808** [comment]
@jeromerobert 
The last comment from me in this repository before leave it.
You said "I don't trust you when it comes to asking for useful feature requests."

I recommend you to visit a provisional psychiatrist to treat your paranoid personality disorder !!!
