### ISSUE TITLE
Check metadata (dektop, metainfo) in CI

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#254]
To avoid stuff like #253 in the future a CI check for those files would be great. I could probably work on that, but if you, Jérôme, want to do this yourself that is probably easiest. I'm also wondering if full builds (Flatpak or maybe Copr) in CI or as nightlies would be worth the effort.

**Comment by jeromerobert** [comment]
> Jérôme, want to do this yourself that is probably easiest

Yes I'll do it today or tomorrow.

> if full builds (Flatpak or maybe Copr) in CI

I expect that RPM build will be easier to run in Docker than Flatpak. We could actually replace the current image by a Fedora based one, and build the RPM instead of simply running pip install. I'm not that familiar with rpm build but I guess it would be light enough the be run on each push. Flatpak build is much heavier.

**Comment by jeromerobert** [comment]
https://github.com/jeromerobert/pdfarranger-docker-ci/commit/2c1b61ce3fbf38481ab317cdd67187f91ccacbc1 & c0ac21728977a6440592ceb1975fe7fbe7b99b4c. Issue kept open for the RPM build.

**Comment by dreua** [comment]
I finally found the time to dive into Docker and Github Actions and got the RPM-Build set up:
Docker image: https://github.com/jeromerobert/pdfarranger-docker-ci/pull/1
Spec file: https://github.com/pdfarranger/pdfarranger/pull/344

I added the rpm spec file to this repository because it makes sense to update it along with the code in case dependencies change. Do you think it should go in some directory to be not that visible? If yes, which? On the other hand I've seen rpm specs and flatpak recipes in the root of other projects so for me both is fine.

> We could actually replace the current image by a Fedora based one

I didn't re-read your comment before starting my work and now I have it set up as an additional image only for the rpm build, do you think it's worth the effort to put it all in one image or would it be also fine to just run both?

**Comment by dreua** [comment]
Already running and building like it should: https://github.com/pdfarranger/pdfarranger/runs/1543565510?check_suite_focus=true

**Comment by jeromerobert** [comment]
Thanks !

> Do you think it should go in some directory to be not that visible?

That's fine to keep it as it's in your PR for now.

> Do you think it's worth the effort to put it all in one image or would it be also fine to just run both

It's fine to run both. I'll maintain the Alpine/Dogtail one and you'll maintain the Fedora one.

**Comment by jeromerobert** [comment]
ea6e39b #344
