### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_enabled'

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#264]
Hi,

I got an error from line 1414, which is part of the routine window_focus_in_out_event
~~~
self.window.lookup_action("paste").set_enabled(data_available)
AttributeError: 'NoneType' object has no attribute 'set_enabled'
~~~
GTK version 3.22.30, Ubuntu 18.04.

I can't recall what exactly I did to get this error. I hope that one of you spots the issue or can reproduce it.

Best,
angsch

**Comment by kbengs** [comment]
Hi,

I also noticed this. It can at least be triggered if you open the application, then close it immediately with Alt+F4.
Was working on a fix yesterday but didn't have time to finish it. I can do it soon.
