### ISSUE TITLE
Warn about loss of attributes like table of contents and links

### ISSUE THREAD

**Issue by htsmi** [pdfarranger/pdfarranger#265]
Using 1.4.2 from Debian. Please ignore if this is not relevant to latest versions.

Recently I tried to crop and rearrange a few pages in an ebook. When I saved it, the table of contents and links were gone in the resulting file. Thankfully, you don't automatically overwrite the original file, so I was able to go back to it.

I realize that these more complex PDF features are not within the scope of this project. But I suggest that you warn users if these exist in the original file and will be lost when saving. Some people may not check this before they delete the original file or send the new one to others.

**Comment by jeromerobert** [comment]
This is still relevant but unfortunately we cannot make everyone happy. Some would like pdfarranger to silently overwrite the original file as if there was no data loss (see #65 and #100). The current situation where we do not overwrite the original file by default is in between. I'm sure that if we add a popup which warn user on each save (there is always data loss) we'll have many requests to remove it.

As solution could be to have a general warning popup saying that pdfarranger does not make any warranty about removing (crop feature) or keeping data (form, TOC, ...) in the pdf, **only the first time** the user start pdfarranger.

**Comment by htsmi** [comment]
I understand the concern about too many popups, and I think you have reached a good compromise with the current save behavior.

My only suggestion is display a warning popup when importing the file _if_ that specific file has data (like links, TOC, forms) that will be lost upon saving... if you can easily determine that. It wouldn't necessarily cover all the data that could be lost but at least some of the more common ones.
