### ISSUE TITLE
Merge/Append/Unsplit Pages - Feature Wish

### ISSUE THREAD

**Issue by klartext** [pdfarranger/pdfarranger#275]
Splitting a page works fine.
After rearranging the pages it would be good to have a merge function, to get back a full page after changing it.

**Comment by klartext** [comment]
Usecase: splitting DIN-A4 into DIN-A5-pages, rearranging them and creating DIN-A4 pages again.
(Or creating bigger pages (A3,...) directly.)

**Comment by jeromerobert** [comment]
How is it different from #246 ?

**Comment by klartext** [comment]
> How is it different from #246 ?

I don't want to change the layout.
But to put together the tiles that are available.

Is there some kind of long time goals, on what to achieve/provide, and how?
Maybe my wishes go into a different direction than what the developers have in mind?

My use case that was in the beginning of this issue was:
Tiling a pdf into seperate pages and tile the pages.
Then remove some parts and put the stuff back again.
And when I started with A4 I wanted to have A4 again.

And I had in mind "reverse splitting".
More general it would be "put these tiles together".

**Comment by jeromerobert** [comment]
> More general it would be "put these tiles together".

That's what #246 is about
