### ISSUE TITLE
Allow to edit creation and modification date

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#283]
Hi.

As title saying:  it is possible to edit date of creation & date of modification of PDF so that to make them empty ?

I think that at least date of modification is possible to make it some thing like this 00:00:00:00:00

Best.

**Comment by jeromerobert** [comment]
We can even edit them with just:
```patch
--- a/pdfarranger/metadata.py
+++ b/pdfarranger/metadata.py
@@ -39,6 +39,8 @@ _LABELS = {
     PRODUCER: _('Producer'),
     _CREATOR: _('Creator'),
     '{http://ns.adobe.com/xap/1.0/}CreatorTool': _('Creator tool'),
+    '{http://ns.adobe.com/xap/1.0/}CreateDate': _('Created'),
+    '{http://ns.adobe.com/xap/1.0/}ModifyDate': _('Modified'),
 }
```
But before commiting that change we must think about a way to manage the case of badly formatted user input (input which is not a valid date).

**Comment by angsch** [comment]
dateutil.parser captures date formats.

~~~
from dateutil.parser import parse

def is_valid_date(string):
  try:
    parse(string)
    return True
  except ValueError:
    return False
~~~

**Comment by Nokia808** [comment]
@jeromerobert 
@angsch 
Many thanks !

**Comment by jeromerobert** [comment]
pikepdf/qpdf expect a ISO-8601 formatted date. May be validation can be implemented in the `_EditedEventHandler` class.
