### ISSUE TITLE
Add Ctrl+o as accelerator of import action

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#289]
Hi,

Currently, the only accelerator for importing files is the insert key. What do you say about adding Ctrl+o and having two accelerators (the insert key and Ctrl+o) for the import action? Even after using pdfarranger for quite some time, I still try Ctrl+o, realize that this is the wrong accelerator and then use the import button (rather than the proper accelerator key). I browsed over the currently defined accelerators and Ctrl+o appears to not be in use.

**Comment by jeromerobert** [comment]
Indeed `insert` is unusual for such action. Gimp and Inkscape use Ctrl+I so I would prefer that we replace `insert` with `ctrl+I`.

**Comment by angsch** [comment]
Ctrl+I sounds intuitive to me as well. Would you keep the old accelerator (and have two accelerators in total) or would you replace it?

**Comment by kbengs** [comment]
Applications seems to have varying action for Ctrl+I. (indent, invert, information, import, filter, properties..) Could Ctrl+O still be better as it is well known?
