### ISSUE TITLE
Problems with editing if not saving after each operation

### ISSUE THREAD

**Issue by msdobrescu** [pdfarranger/pdfarranger#291]
Hello, first, it is a great tool! It saves my time! a lot, I use it every day for my boy at school! It's brilliant! A must have!

I edit files scanned by my copier that is able to generate them directly, but I must rotate, delete, interleave pages etc..
During these operations I have noticed that can't be copied properly from one instance to another if the source was not saved first. Regardless the state, if pages are marked and copied from a source file that was edited, they are sent to clipboard in the state they are in the file on the disk, not in memory (as being edited). As effect, pasting them to a new document will bring only the pages existing in the source, in their state in the file on disk. This is misleading. Please copy the pages as they are in memory, in the edited source file or clarify the behaviour.
Same for cutting.

I use version 1.6.2 on Sabayon Linux.

Operating System: Gentoo Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.0
Kernel Version: 5.7.0-sabayon
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7 CPU 920 @ 2.67GHz
Memory: 23,5 GiB of RAM
Graphics Processor: GeForce GTX 1060 6GB/PCIe/SSE2

Thank you.

**Comment by kbengs** [comment]
That was interesting. It is something that I can't reproduce. Does drag and drop to another instance work as it should? Would you be able to test run the application from a git clone:

git clone https://github.com/pdfarranger/pdfarranger.git
cd pdfarranger
pip install -e .
./setup.py build
python3 -m pdfarranger

Then we could add some debug printing to the code.

**Comment by kbengs** [comment]
I installed Sabayon and did a git clone. But I couldn't see any problem when running pdfarranger this way. Also if I go back to the stage when 1.6.2 was released it works fine: if I rotate a page and copy-paste it to another instance it will be rotated also on the other instance.
@msdobrescu How did you install pdfarranger?

**Comment by msdobrescu** [comment]
Hi, sorry for the delay, I was busy, I won't let you down, but I need time.
I was installing it through the regular package manager.
I'll test some more, maybe there is something related to specific PDFs.

**Comment by kbengs** [comment]
No problem. I was also curious about what Sabayon is, so I tested it. :-)

**Comment by msdobrescu** [comment]
I love Sabayon, I prefer it over all distros. I love Mageia too. Ubuntu is kind of messy in my experience.
I'll come back with a case with clear samples, if that happens again.

**Comment by kbengs** [comment]
I realized what this is about. To reproduce this problem:

* Open a pdf and rotate a page
* Save and overwrite the pdf
* Copy-paste the rotated page (to same or other instance) -> the page will not be rotated as it is in iconview

Reason is that copy-paste takes the page from the newly saved file and then apply rotate once more to it.
It does also affect drag and drop to other instance.

**Comment by dreua** [comment]
@kbengs good spot, it becomes worse if you delete the first page instead of rotating it: For some reason I don't understand you can still save the new instance just fine but copy & pasting a page just to duplicate it in the 2nd instance results in a different page (due to changed page numbers in the original file) in icon view and export.

**Comment by kbengs** [comment]
> it becomes worse if you delete the first page

Yes.. I don't see any easy fix here. I can think of two approaches to fix this:

Approach 1:
Include nfile when copying a page. This way it is possible to keep track of what version of a file a page comes from. If copying to another instance the paste-instance would need to get access to the copy-instances temporary stored files. 
I have this working when using a single instance.


Approach 2:
When pdfarranger overwrites a file it would reload that file. Then also clear clipboard. Pages in iconview and pages on disk would then be the same. With this approach it would still be a problem if a file was externally overwritten.

Does anyone have any thoughts about this?

**Comment by angsch** [comment]
If we think of large pdfs, Approach 2 is probably noticeably slower.

**Comment by jeromerobert** [comment]
I vote for a kind of approach 1. Is keeping nfile enough to copy across instances ? They can access each other temporary folder but not `pdfqueue`. May be we should serialize/deserialize PDFDoc.copyname instead of Page.filename.

**Comment by dreua** [comment]
Just a high level thought, since I can't dive into the code now: If we share the temporary files between instances, who is responsible of the cleanup? Do we clean our tmp files at all? If yes I see the danger of one instance cleaning a file that another is still using. (The good old garbage collection problem, we could implement pdf-shared-pointers similar to those in C++ but as I said, just high level thinking here for now...)

**Comment by kbengs** [comment]
> Is keeping nfile enough to copy across instances ? 

No we need to include copyname as you say.
> who is responsible of the cleanup?

If we include copyname when copying then the new instance can make its own copy of the file. And yes the files are removed from /tmp when the app closes.

I did continue on approach 1 yesterday but I am not satisfied with it yet.
