### ISSUE TITLE
Change meaning of file filter 'all files' to 'all supported files'

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#292]
Hi,

pdfarranger supports PDF files and, if img2pdf is available, a variety of image formats. In the import dialog, the default file filter is set to PDF files. Alternative file filters are 'all files' and 'supported image files'. I suggest to change the meaning of 'all files' from literally all files to all supported files and make this the default filter. I wonder how many users are actually aware that images are supported when the default filter is PDF files.

Other considerations:
* For software on Ubuntu, the proposed change appears rather standard. For example, evince uses 'all documents' as default to list all supported file formats. 'all files' is also available and lists all files.
* The file opener dialog of the default PDF viewer on Mac lists all files, but grays out all non-supported files. I find this solution neat, but I could not find any Gtk feature that would enable this.
* It is not clear to me what the default behavior on Windows is.

**Comment by jeromerobert** [comment]
> I suggest to change the meaning of 'all files' from literally all files to all supported files

I would prefer the filter "all supported files" to be added in addition to the "all files" filter. This is what evince do.

> and make this the default filter.

+1

> It is not clear to me what the default behavior on Windows is.

It should go well
