### ISSUE TITLE
Microsoft Defender SmartScreen treats the msi file as a threat

### ISSUE THREAD

**Issue by Stanimo** [pdfarranger/pdfarranger#293]
Although I reported it as safe, windows 10 ver2004 defines the msi as a threat after downloading and once again before installing.

**Comment by jeromerobert** [comment]
I'm afraid there's not much we can do about it. Whatever antivirus software raises this alarm is a black box. We can't find out why it's raising the alarm. So unless someone has something constructive to add, I'm going to close this bug.

**Comment by jeromerobert** [comment]
@Stanimo For the record could you provide a screenshot or tell us which component/software is triggering the threat warning ? Could you also confirm that there is no warning with the zip file ?

**Comment by Stanimo** [comment]
The portable zip files doesn't trigger any threat warnings, works fine.

**This is the message right when the browser (edge) finished the download:**
![image](https://user-images.githubusercontent.com/48218276/95672909-12f18d00-0bad-11eb-957d-c5dc6dff6b42.png)

**File options:**
![image](https://user-images.githubusercontent.com/48218276/95672970-7d0a3200-0bad-11eb-9cf6-a9ea8eda59ca.png)

**Trying to keep the file:**
![image](https://user-images.githubusercontent.com/48218276/95672986-9ad79700-0bad-11eb-8a2b-59d12545a065.png)

**Reporting on Microsoft website:**
![image](https://user-images.githubusercontent.com/48218276/95672944-61069080-0bad-11eb-8b87-8dd6fba884e9.png)

**Downloading and Running on Chrome**
![image](https://user-images.githubusercontent.com/48218276/95673059-15a0b200-0bae-11eb-9e7f-90234ce1253c.png)

**Comment by jeromerobert** [comment]
Thanks. So this probably happen because the `.msi` is not signed. I can signed it with a self generated certificate but it should not help. I won't buy a certificate for pdfarranger so this issue will remain unfixed.
