### ISSUE TITLE
"Could not find xref table at specified location" error on save

### ISSUE THREAD

**Issue by oddhack** [pdfarranger/pdfarranger#295]
I get this error when loading a few PDFs into pdfarranger, shifting some pages around, and trying to save. I'm using an old version of pdfarranger packaged for Debian buster (pdfarranger 1.1.1); is it worth building the most current version from scratch myself in the hope that would resolve this error?

**Comment by jeromerobert** [comment]
pdfarranger 1.1.1 was based on PyPDF2. The current version is using pikepdf so yes it worth building it. It should be straightforward with `pip` (see README) unless you get problems with a too old `libqpdf-dev` package. There is also a Flatpak package.
