### ISSUE TITLE
Selection using navigation keys

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#296]
Hi,

I want to extract the last few pages from a document. 1) Select the start page through a mouse click, 2) hold Shift 3) press end key. The selection encloses all pages in the rectangle defined by the start page and the last page. If the last page is not in the bottom right corner the selection is view-dependent.

Example:  The start page is 1, depending on the window geometry, Shift + End gives different selections.

![image](https://user-images.githubusercontent.com/17718454/95654551-fdbf2480-0b00-11eb-9ff2-6d657c196ec3.png)

Scrolling to the last page and clicking on it, gives a contiguous selection. This is what I assumed would happen when using the end key. The home key produces the same issue.

I suggest do change the behavior for the home/end key to either of the two:

- The navigation keys (home, end, page up, page down) are a replacement for scrolling. Then it would make sense that the navigation keys only focus the first (home) or last (end) page, but _not_ select it. Page up/down works like this already, the keys change the focus, but do not select anything.
- The home/end keys are a replacement for scrolling _and_ clicking. Then the selection should be contiguous.

Personally, I prefer the first option.

**Comment by kbengs** [comment]
Nautilus works as the second option.. I am not sure what I would prefer, I never use home/end, but as Page up/down works as it works maybe it makes more sense that home/end would work as the first option also.

**Comment by kbengs** [comment]
What do you think about shift + keyboard arrows selection behavior, should it be as it is now or should it do a continuous selection like for example Nautilus do? (select all pages between first selected page and page where cursor is)

**Comment by angsch** [comment]
Being consistent with Nautilus makes sense, both for the navigation keys and the arrow keys.

We could add a "go to page <page number>" option later to ease navigation and support the semantics of the second option. Simple navigation makes sense if the information is scattered, but the position is known. For example, to extract all figures whose page numbers are known from a table of figures. Not sure though how many users need this.

**Comment by kbengs** [comment]
>Being consistent with Nautilus makes sense, both for the navigation keys and the arrow keys.

Do you want to do this issue @angsch ?

**Comment by angsch** [comment]
@kbengs I am not really familiar with the iconview and also a bit short on time until the next weekend. If you have time and want to take over, I would be very glad.

**Comment by jeromerobert** [comment]
3bd8a23
