### ISSUE TITLE
Snap assist doesn't work in Windows 10

### ISSUE THREAD

**Issue by kbengs** [pdfarranger/pdfarranger#297]
This is a gtk issue that we can't do anything about but I put the info here if somebody search for it.

Windows 10 has features that:
 * Resize windows when they are dragged to edges
 * Suggest companion windows when a window is dragged to left or right side
 * Minimize other windows when a window is shaken
 * Move windows with Win + Left or Right
 
This does not work for pdfarranger. The issue came with 1.5.0 when the application changed to GtkHeaderBar.
 
It is a open issue on gitlab:
https://gitlab.gnome.org/GNOME/gtk/-/issues/2785

Don't know if this issue should be left open or be closed.

**Comment by kbengs** [comment]
Setting os.environ['GTK_CSD'] = '1' will enable "client side decorations". In pdfarranger it will change the look of dialogs titlebar, and as a positive side effect, moving application window with Win + Left or Right will work. 
In picture below: GTK_CSD disabled to left, enabled to right. 
![GTK_CSD_1](https://user-images.githubusercontent.com/60842129/100536557-2ecaf400-322a-11eb-843d-680c75ff3b1e.png)

**Comment by dreua** [comment]
Any reason not to apply that fix and close this issue? It sounds good to me and not being able to "edge-drag" pdfarranger sounds annoying to me. Fortunately I seldomly use Windows :smile: 

I'd even say the right version is the better choice for styling, it's not native but at least the dialog and main window have the same styling.

**Comment by jeromerobert** [comment]
Well I was not that critical so I did not tested it for 1.7.0. But as it's a minor change we could have it in 1.7.1.

**Comment by dreua** [comment]
Sorry my wording was unclear: I didn't mean to say getting this out asap is important, I just went through some older issues, adding tags and wondering if they are still useful. This can wait for 1.8, I don't really care tbh.

**Comment by kbengs** [comment]
The fix is only for the win + left/right case. All the other snap assist features still don't work. Looking at forums on internet people seem to have a lot of opinions weather CSD should be enabled or not. But we are only changing the look of dialogs titlebar here 
so I also think we should apply this fix. (1.8.0 is fine)
