### ISSUE TITLE
GtkFileChooserDialog have some issues

### ISSUE THREAD

**Issue by icf20** [pdfarranger/pdfarranger#301]
![image](https://user-images.githubusercontent.com/17784575/95867647-abcd0780-0d69-11eb-8faa-c75340962f1a.png)

you can see here that the save as dialog is not performing like expected

here same dialog from atril
![image](https://user-images.githubusercontent.com/17784575/95867874-ea62c200-0d69-11eb-88d8-240290704f47.png)

**Comment by jeromerobert** [comment]
I don't see the differences. Could you elaborate ?

**Comment by icf20** [comment]
@jeromerobert  > I don't see the differences. Could you elaborate ?

GtkFileChooserDialog covers the side panel so the first 4 items on the side panels are not there
