### ISSUE TITLE
Selection as wordprocessor - not as graphics program

### ISSUE THREAD

**Issue by ole-tange** [pdfarranger/pdfarranger#305]
Given this page layout
~~~
1 2 3 4
5 6 7 8
~~~
If you select the rectangle 2..7 using the mouse you currently select 2 3 6 7 because
they are in a rectangle. But what you typically want is to select is 2 3
4 5 6 7.

So I propose changing the selection algorithm to behave like a word processor instead of a graphics program.

(And thanks for a wonderful tool).

**Comment by ole-tange** [comment]
When using CTRL-V pdfarranger already use the word processor algorithm: Pasting 4 pages are not pasted as a rectangle but instead like a text in a word processor.

**Comment by boythere** [comment]
I see pages 2 3 4 5 6 7 selected.

Version 1.6.2

**Comment by ole-tange** [comment]
Version 1.6.1:

![image](https://user-images.githubusercontent.com/778812/97193040-d88d1000-17a8-11eb-9363-34a1f8344e66.png)

**Comment by kbengs** [comment]
When selecting with mouse click + drag a rectangle, it will work as ole-tange describes.  The current selection behavior is same as file managers use. Maybe we could try to change it and see how it feels.. It might not be easy to do though.
When using shift + mouse click it will do a continuous selection. #303 will change the selection behavior when using shift + keyboard arrows so that it also does a continuous selection.

**Comment by kbengs** [comment]
It seems to be possible to do it with something like this:

    self.iconview.connect('event_after', self.event_after)

    def event_after(self, _iconview, event):
        if event.type == Gdk.EventType.MOTION_NOTIFY:
            if event.state & Gdk.ModifierType.BUTTON1_MASK:
                selection = self.iconview.get_selected_items()
                if selection:
                    selection.sort(key=lambda x: x.get_indices()[0])
                    start_p = Gtk.TreePath.get_indices(selection[0])[0]
                    end_p = Gtk.TreePath.get_indices(selection[-1])[0]
                    with GObject.signal_handler_block(self.iconview, self.id_selection_changed_event):
                        for page_nr in range(start_p, end_p):
                            path = Gtk.TreePath.new_from_indices([page_nr])
                            self.iconview.select_path(path)
                    self.iv_selection_changed_event()
