### ISSUE TITLE
Have "Split Page" support n x m split instead of just 1 x 2

### ISSUE THREAD

**Issue by ole-tange** [pdfarranger/pdfarranger#306]
It is already possible to make a poor-man's poster with the program:

Edit > Split pages, followed by Rotate, followed by Edit > Split pages, followed by Rotate.

This way you get a 2x2 poster.

It is, however, not ideal: The overlap is minimal (around 1 mm on my printer).

But with very few changes this could be improved.

I hereby propose a menu for generating a poster. In the initial version it is fine, if you just do 2x2, 3x3 and 4x4. Those should be very easy to implement given the above tools. The poster should add a bit of overlap (say 3-5%), so it is easier to cut off a margin and make it fit. Therefore the pages should be scaled 1.9 (not 2), 2.85 (not 3), 3.8 (not 4) or similar.

For people using ISO-paper sizes (A4, A3, A2) it should also be easy to make a poster to 1x2 (Rotate, scale 1.4), 2x4 (Rotate, scale 2.8).

**Comment by boythere** [comment]
Very tricky!

After splitting, the size of pages can be re-cropped. 

For example,
L-R-T-B: 48% 48% 0% 0%

**Comment by angsch** [comment]
@ole-tange I don't think that pdfarranger will ever be the tool of choice for creating high end posters for printing. Fixing the margins for print for all sorts of formats and page tessellations is not entirely trivial. For the tasks that you give as examples, you may want to have a look at a specialized tool such as [pdfposter](https://pdfposter.readthedocs.io/en/stable/index.html).

**Comment by boythere** [comment]
@angsch 

1. I'll be glad to see that the pdfposter-like feature would be delivered in new pdfarranger someday.

2. Besides a poster, we always need a booklet as the output type so that lots of people just know clicking `Print` only.

**Comment by XanderLeaDaren** [comment]
By booklet, do you mean:

n, 1, 2, n-1,
n-2, 3, 4, n-3,
n-4, 5, 6, n-5,
…

so that you may fold all pages and staple them?

If so, I would support such an idea and we should create a feature issue for this. 😃

**Comment by boythere** [comment]
@XanderLeaDaren Yes, we like it.

**Comment by ole-tange** [comment]
> @ole-tange I don't think that pdfarranger will ever be the tool of choice for creating high end posters for printing. Fixing the margins for print for all sorts of formats and page tessellations is not entirely trivial. For the tasks that you give as examples, you may want to have a look at a specialized tool such as [pdfposter](https://pdfposter.readthedocs.io/en/stable/index.html).

I did. But poster printing is *so* much easier, when you get visual feedback immediately.

Also `pdfposter` is written in Python. The core files (https://pypi.org/project/pdftools.pdfposter/#files) are around 20 Kbytes, so I would imagine it would be reasonably easy to copy. It is GPLv3, so the license is compatible.

To me an acceptable first version could simply require`pdfposter` to be installed, and then have `pdfarranger` call that and present the output.

Also: This is not for high-end poster printing, but for exactly the opposite end of the market: Low-end DIY poster printing.

**Comment by jeromerobert** [comment]
We will not have pdfposter as a dependency of pdfarranger. That would mean write a GUI to generate a command line for pdfposter and having PyPDF2 back in pdfarranger. pdfposter is just a single file with few functions:
https://gitlab.com/pdftools/pdfposter/-/blob/develop/pdftools/pdfposter/__init__.py
We already have most of them in pdfarranger thanks to pikepdf.

This issue collide with #246, #204, #247 and #267 because all of these issues will share some code and some of them will also share the same dialogs. Implementing those 5 features with PikePDF is probably not difficult (I have good ideas on how to do it). But I have no idea how to put all this to music around a GUI, without it becoming too complicated for users and developers.

Anyway I don't want a "make poster" feature as it's too specific. Let's decompose to:
* split n x n
* manage scale and margins

This is issue will be for split n x n only which is the easiest of both to implement. It will replace/extends the current split page feature.

IMHO the second one is currently not clear nor well specified and will need the maturation of the existing scaling/croping feature.

**Comment by ole-tange** [comment]
As mentioned, you pretty much got split covered: Using 'Split pages' and 'Rotate' I can get 1x1 => 1x2, 1x2 => 2x2, 2x2 => 2x4, 2x4 => 4x4.

I do not think I have every made a poster that was not covered by that.

In theory I might want 3x3, but I don't think I ever used that in practice.

In other words: I do not need better m x n split functionality than you already have.

You could make it easier for other users by having two menu items:

Edit > Poster > to 2 pages (Run: Rotate Left, Split Pages, Rotate Right)
Edit > Poster > to 4 pages (Run: Rotate Left, Split Pages, Rotate Right, Split Pages)

But functionality-wise you are already at the goal regarding spllitting.

**Comment by jeromerobert** [comment]
For the record, this how it now looks like:
![sc](https://user-images.githubusercontent.com/160365/103300357-fd973c80-49fe-11eb-8e07-b6aeffb5e1dc.png)

**Comment by ole-tange** [comment]
UI looks OK. I would probably have chosen default values that would make sense (i.e.: No one will split a page to 1x1), but this is not critical for the use.

But the result has no overlap. This means if you print the result on a printer which has a printable area that is smaller than the physical page (all my printers have this), you will not be able to make it into a poster.

This might be have been possible to mitigate if you could adjust the individual Height/Width in percent: It might be OK if all were, say, 55%. But if I change a value to 55% then the others change automatically making it impossible to make the sum > 100%.

I can force the overlap with this work-around, but it is awfully cumbersome (2x2 poster):

- Duplicate page 3 times.
- Gird split page 1 with ((55%,45%),(55%,45%)). Throw away all the small pages.
- Gird split page 2 with ((55%,45%),(45%,55%)). Throw away all the small pages.
- Gird split page 3 with ((45%,55%),(45%,55%)). Throw away all the small pages.
- Gird split page 4 with ((45%,55%),(55%,45%)). Throw away all the small pages.

I would much prefer if the dialog box had a field: "Number of mm overlap" which should calculate the percentages automatically. I think an overlap of 8 mm would work on all printers I have ever had, so to me that would be a reasonable default value for the field.

See #327 for calculation.

**Comment by jeromerobert** [comment]
> No one will split a page to 1x1

Right and this will be fixed by the #370 PR.

> But the result has no overlap.

Yes, this will be for >=1.8.0.

To be continued in #327.
