### ISSUE TITLE
CTRL-+ and CTRL-- as short cut for zoom-in and zoom-out

### ISSUE THREAD

**Issue by ole-tange** [pdfarranger/pdfarranger#307]
More and more programs support using CTRL-+ and CTRL-- as a shortcut for zoom-in and zoom-out.

I am clearly so used to using those that I cannot help pressing them when wanting to zoom in pdfarranger.

It seems you are not using the short-cuts so nothing is going to break, if you add those, too.

**Comment by angsch** [comment]
The current shortcuts for zooming are + and - or, alternatively, CTRL+mousewheel. Evince supports all three combinations, + and CTRL++ and CTRL+mousewheel.
