### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by radujica** [pdfarranger/pdfarranger#316]
I used the installer link from the README, i.e. pdfarranger-1.6.2-windows-installer.msi

![Screenshot 2020-11-05 225301](https://user-images.githubusercontent.com/8166962/98300694-f08b3d80-1fb9-11eb-9a2b-3da1b50bb4a0.jpg)

Am I maybe missing some dependency? Or something odd in my Python setup?

`python --version` is 3.6.1

Note that the Z: drive is an existing but disconnected SAMBA drive on my PC.

**Comment by pine1212** [comment]
creat shortcut manually or set shortcut start location to installation folder

**Comment by jeromerobert** [comment]
Related: #300 #176
Setting the shortcut start location should let pdfarranger use it's own python, GTK,... instead the one you have installed in `z:\mingw64`.

**Comment by radujica** [comment]
Alright, @pine1212's solution worked, thx!

More detailed steps for others:
- press windows key and search for "pdf arrange"
- right click and "open to file location" <- this should open explorer and bring you to shortcut location
- right click "PDF Arranger" shortcut and "properties"
- copy the path in "Target:" to "Start in:" (which should initially be empty) and update it point to the folder (e.g. if path is "C:/folder/arranger.exe", start in should be "C:/folder")

**Comment by dreua** [comment]
I just pinned this because it seems to be common. Is this fixable in the installer for the future?

**Comment by jeromerobert** [comment]
Unpinning to give more visibilitity to 1.7.0rc1

**Comment by dreua** [comment]
> Is this fixable in the installer for the future?

I wasn't aware there was already a fix attempted and it seems to work according to #380 , great :rocket: !
