### ISSUE TITLE
pdfarranger does not run on Windows 10

### ISSUE THREAD

**Issue by sbstn87** [pdfarranger/pdfarranger#321]
Hi, 

unfortunately pdfarranger does not run for me on Win 10. Here are the error dialogs I get:

![csrss_2020-11-09_18-27-11](https://user-images.githubusercontent.com/37237675/98575332-fa11ef80-22b0-11eb-9399-dbed37af6865.png)
![pdfarranger_2020-11-09_18-26-43](https://user-images.githubusercontent.com/37237675/98575340-fc744980-22b0-11eb-913f-3e3cd3dba501.png)

**Comment by dreua** [comment]
Please try this workaround: https://github.com/pdfarranger/pdfarranger/issues/316#issuecomment-723506390

@ other maintainers: Sorry I lost track about the Windows stuff, is this fixable / already fixed?

**Comment by sbstn87** [comment]
It solves the issue. Thank you.

Also, the portable version works fine.

**Comment by dreua** [comment]
Great, I'll close this because the other issue contains more information & workaround.
