### ISSUE TITLE
Scaling and moving for poster

### ISSUE THREAD

**Issue by ole-tange** [pdfarranger/pdfarranger#327]
In #306:

> IMHO the second one is currently not clear nor well specified and will need the maturation of the existing scaling/croping feature.

I do not think you can separate the process into two parts without making it overly complicated.

Let me try to specify the process of making an n x n poster. I will focus on on the x axis, but y axis will be similar.

```
// A border of 1cm will work for all printers I have used in my life - thus this does not need to be configurable
border = 1cm
// Make a 1cm border used for overlap (and non-printable areas) in both sides
page_center_width = page_width - 2*border
// generate n x n poster
// the resulting poster (after printing and putting it together with overlaps) will measure poster_width
poster_width = border + page_center_width*n + border
// the original page should be scaled by this much
scale_factor = page_center_width * n / page_width 
poster = original_page * scale_factor
// move the poster so that the original x=0 is moved to start of the page_center area
page 1 = move(poster,border - page_center_width*0)
// move the poster so that start of the page_center area will be the end of the page_center area of page 1
page 2 = move(poster,border - page_center_width*1)
// move the poster so that start of the page_center area will be the end of the page_center area of page n-1
page n = move(poster,border - page_center_width*(n-1))
```
The corresponding calculations should be done for the y values.

This should be enough for converting a single page into an n x n poster - no matter the aspect ratio of the paper.

To make a n x 2n poster (portrait to landscape) is similar (assuming page_height = sqrt(2)*page_width as it is for ISO 216 paper sizes):

```
// A border of 1cm will work for all printers I have used in my life - thus this can be fixed
border = 1cm
// Make a 1cm border used for overlap (and non-printable areas) in both sides
page_center_width = page_height - 2*border
// generate n x 2n poster
// the resulting poster (after printing and putting it together with overlaps) will measure poster_width
poster_width = border + page_center_width*n + border
// the original page should be scaled by this much
scale_factor = page_center_width * n / page_height
poster = original_page * scale_factor
// move the poster so that the original x=0 is moved to start of the page_center
page 1 = rotate(90,move(poster,border - page_center_width*0))
// move the poster so that start of the page_center will be the end of the page_center of page 1
page 2 = rotate(90,move(poster,border - page_center_width*1))
// move the poster so that start of the page_center will be the end of the page_center of page n-1
page n = rotate(90,move(poster,border - page_center_width*(n-1)))
```

Similar calculations for y values. The widest direction will not go to page n, but to page 2n.

Thanks again for a cool tool.

**Comment by dreua** [comment]
This sounds doable but it is also a niche use case. From the lacking feedback so far I suspect no one is going to work on this in the foreseeable future (raise your hand to indicate otherwise).

Do I understand correctly that we'd need to cut a page to pieces according to the math you laid out and then add a white border around it? I'm asking, because I think the white border could actually be the hardest part here.

General question: Should we keep such issues open indefinitely or would it be appropriate to close them after a while? A special tag could be applied to make them findable, for example "stale feature request".

**Comment by jeromerobert** [comment]
I already printed posters so I understand what it's about. But it's definitely not my priority. First because as you say it's a niche use case. Also because I think the way we manage margin (crop, format page) should be reworked before working on that issue.

I would be more confortable in doing a pure CLI tool dedicated to poster, based in pikepdf, which would only do the split and margin. The GUI make this more difficult to implement.

**Comment by jeromerobert** [comment]
It almost already exists https://pdfposter.readthedocs.io but that one is based on PyPDF2.

**Comment by dreua** [comment]
I agree on all points. Do you have an estimation how hard the white borders would be with pikepdf? How about porting pdfposter to pikepdf? (Suggest it or offer help.) They seem to have the same issues like we had back then.

If you want to create a new CLI tool we could simply ship it bundled with pdfarranger imo.

**Comment by angsch** [comment]
> Do you have an estimation how hard the white borders would be with pikepdf?

Adding additional white margins with pikepdf is easy. I will prepare an example on the weekend and post it here. The time-consuming part will be to figure out all the details.

**Comment by ole-tange** [comment]
In version 1.7 you are *sooo* close to have a working method. All you really need to do is to *not* enforce that the percentages add up to 100% when doing 'Split Pages'.

If I can do [53%,53%] or [35%,35%,35%] then it will pretty much do, what I describe above, and will probably be good-enough for making posters.

I tried disabling the "Fix the sum to match 100", but I can see the self.model is a bit too simple. It seems to store only the width of each slice. So when splitting [53%,53%] I get a large white portion at the last slice (probably 6% of the page).

But if the model is extended to instead storing start and end for each crop (e.g. crops[0].start=0%, crops[0].end=53%, crops[1].start=47%, crops[1].end=100%), then it should be a small change.

**Comment by angsch** [comment]
PDF uses the first quadrant of the Cartesian coordinate system as the coordinate system. See https://pikepdf.readthedocs.io/en/latest/topics/content_streams.html#editing-a-content-stream

```
import pikepdf

in_doc = pikepdf.open('in.pdf')
dictpage0 = in_doc.pages[0]
new_doc = pikepdf.Pdf.new()
page = new_doc.copy_foreign(in_doc.pages[0])
_, _, width, height = page.MediaBox

content_dict = pikepdf.Dictionary({})
content_dict['/Page1'] = pikepdf.Page(page).as_form_xobject()

margin = 500 # Something big to see the difference
new_mediabox = [0, 0, width + 2 * margin, height + 2 * margin]
x0 = margin
y0 = margin

# The first four number are the rotation matrix (identity matrix), the other two the displacement vector.
content_txt = f'q 1 0 0 1 {x0} {y0} cm /Page1 Do Q'

newpage = pikepdf.Dictionary(
    Type=pikepdf.Name.Page, 
    MediaBox=new_mediabox,
    Resources=pikepdf.Dictionary(XObject=content_dict),
    Contents=pikepdf.Stream(new_doc,content_txt.encode())
)
new_doc.pages.append(newpage)
new_doc.save('out.pdf')
```

**Comment by ole-tange** [comment]
I have made it work here:

[poster.txt](https://github.com/pdfarranger/pdfarranger/files/5976149/poster.txt)

**Comment by ole-tange** [comment]
It could probably be made more elegantly, but at least there is now a working prototype.
