### ISSUE TITLE
Making pdfarranger suitable for large PDFs

### ISSUE THREAD

**Issue by jeromerobert** [pdfarranger/pdfarranger#332]
Currently pdfarranger is not suitable to manage a several hundred page PDF for those reasons:
* All page thumbnails are kept in memory whatever they are visible or not. When zooming a lot pdfarranger needs several GiB of RAM.
* Thumbnails are rendered in order, and for all pages whatever they are visible or not. If you open a large PDF, zoom a bit and scroll to the end, you have to wait to get the thumbnails.
* When zooming/unzooming the thumbnails need to be re-rendered

Some ideas:
* the thumbnails should be cached to the disk (sqlitedb ?)
* the thumbnails should be rendered/loaded on demand (i.e. when they are visible).

**Comment by kbengs** [comment]
I could start to look at this. I guess we are aiming at 1.8. As step one I would try to make it load on demand in full page mode. It could preload for example +/- 5 pages (to ram). Then we see if caching to disk is necessary. I hope it would not be necessary because it could cause a lot of disk write. Also relevant would be to find out why the application does not always release ram as it should.

**Comment by jeromerobert** [comment]
> I could start to look at this

Great !

> I guess we are aiming at 1.8

Yes (or later)

> As step one I would try to make it load on demand in full page mode

You mean load on demand from Poppler without caching to disk ? I guess that's what Evince do and that would indeed be much better than caching thumbnail to disk. I had in mind that loading/rendering should be triggered from scrolling events and using the currently visible icons (`Gtk.TreeView.get_visible_range`).

> Also relevant would be to find out why the application does not always release ram as it should

My comment was only about expected high memory usage when loading large files and zooming, not about unexpected memory leaks. Do you mean you noticed that we have some memory leaks ? Related to Poppler ?

**Comment by kbengs** [comment]
> You mean load on demand from Poppler without caching to disk ?

Yes. It probably won't be fast enough when scrolling fast, but we will see.

> Do you mean you noticed that we have some memory leaks ?

Yes. I can open a new issue about that with steps to reproduce.
