### ISSUE TITLE
Automatic zoom as default

### ISSUE THREAD

**Issue by XanderLeaDaren** [pdfarranger/pdfarranger#333]
When launching the app, the zoom level is currently the same as last opening of the app.

It would be useful to have an auto-adjusting level at launch, showing all pages of a just opened pdf at glance. The user would then just have to zoom in/out as desired.

As a bonus, it allows for quick page ordering changes without zooming out first.

**Comment by grahamperrin** [comment]
I began drafting an issue: 

> If the initial page is larger than the window: automatically zoom out to fit

In the screenshots below, I imagined zooming out to fit the initial page _of any appended item_. 

After finding this issue, I might prefer what @XanderLeaDaren suggests – fit all pages – **however** the UX _might_ be slightly disorienting if, for example: 

* an initial append of a two-page item is followed by 
* an append of a ninety-page item
 
– _too much_ of an automated change in zoom, mid-workflow, might be disorienting. 

### Examples

A neat first impression: 

![ksnip_20210115-040744](https://user-images.githubusercontent.com/192271/104681042-4c282480-56e9-11eb-901a-89a03e3c19fe.png)

Without altering the zoom, the next new file has a view that is not immediately useful: 

![ksnip_20210115-040909](https://user-images.githubusercontent.com/192271/104681669-c907ce00-56ea-11eb-8818-d78258c74b5d.png)

Better after zooming out three or four times: 

![ksnip_20210115-041635](https://user-images.githubusercontent.com/192271/104681732-f5bbe580-56ea-11eb-96f7-80a35c46c63a.png)

**Comment by dreua** [comment]
I'm quite happy with Ctrl + Mousewheel. It does exactly what I want to do, when I want it and in a very non-disturbing way. But it could be a nice touch when implemented well. Anyone interested in working on this?

**Comment by jeromerobert** [comment]
It's still not clear to me what is to be implemented here. As grahamperrin said whatever the policy we implement it will not be good for all PDF and all users. Having multiple policy could be a solution but do we want to make pdfarranger that complicated ?

**Comment by dreua** [comment]
> Having multiple policy could be a solution but do we want to make pdfarranger that complicated ?

Fair point. I didn't go into details because it looks like no one is going to work on it anyway so with `who=None` the `how` didn't seem relevant.
