### ISSUE TITLE
allow to edit "initial view" of PDF

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#346]
Hi dear developers. 1st of all I would give my thanks for all cute peoples who working on this project for their very hard works to evolute it ! Really it seem that next releases will be something big !

One of the needed functionalities is to allow to edit the initial view of PDF. I will not go deeper, but kindly see this discussion:
https://github.com/pikepdf/pikepdf/issues/117
It seem that adding this feature is not difficult & something more or less straight forward (the speech is to @jbarlow83)

Kindly keep this request on your list of to do.

Best.

**Comment by Nokia808** [comment]
@jeromerobert 
You are aggressive & of bad ethics. I will delete your dirty application & will never install it again.
Also, I will close all feature request that I opened on this repository.

You are make like new nazi

**Comment by Nokia808** [comment]
@jeromerobert 
The last comment from me in this repository before leave it.
You said "I don't trust you when it comes to asking for useful feature requests."

I recommend you to visit a provisional psychiatrist to treat your paranoid personality disorder !!!

**Comment by mara004** [comment]
I'm not sure whether this is worth being added - the initial view preferences are rarely used, and I think most free PDF viewers disregard them anyway.
