### ISSUE TITLE
Please include OCR option

### ISSUE THREAD

**Issue by bilufe** [pdfarranger/pdfarranger#349]
I request a OCR option in PDFarranger.

Why I donate to pdfarranger for develop this function?

**Comment by jeromerobert** [comment]
> I request a OCR option in PDFarranger.

Duplicate #238. pdfarranger is a GUI for Poppler and PikePDF. It's not and won't be a GUI for tesseract. You may find what you are looking for here: https://tesseract-ocr.github.io/tessdoc/User-Projects-%E2%80%93-3rdParty.html

**Comment by Nokia808** [comment]
@bilufe 
Kindly look for this command line program:
https://pypi.org/project/ocrmypdf/
https://github.com/jbarlow83/OCRmyPDF

You can donate the author of OCRmyPDF to make a GUI for his program. The author made some commits to his program to make this process easier - see:
https://github.com/jbarlow83/OCRmyPDF/issues/399
Try to ask him to create GUI & ship it on FlatHub if you donate him enough money to cover hrs needed to create such GUI. To me it is not so important & I has other more important project to donate like:
https://gitlab.com/scarpetta/pdfmixtool/-/issues/36
&
https://gitlab.com/Monsterovich/protox/-/issues/20
PDF Mix Tool not open a donation way to donate him. But Protox developer open such ways, so I donate him & both PDF Mix Tool & Protox are of interest to me ..... If you are interested in creation of GUI for OCR PDF then I think OCRmyPDF is the best place to you to try .....

By the way, I think pdfarranger is in need to open a donation paths to allow community to support them in their work. I will open a request for that.
