### ISSUE TITLE
Allow community to support you by donations

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#350]
Hi dear developers of pdfarranger ! 
You are, currently, working very hard to add more & more features to your program. It seem that finally community will reach to nearly 90% support for PDF files on Linux by combination of powers of 3 programs, namely:
- Okular,
- OCRmyPDF
- either pdfarranger or PDF Mix tool

I would like to suggest on you to open a donations ways to allow community to support you. You can use PATREON for that:
https://www.patreon.com/

Look for example to Protox developer how he opened more than way to receive donations:
https://gitlab.com/Monsterovich/protox

Please do not misunderstand me !! I DO NOT OPEN THIS ISSUE TO ASK YOU TO IMPLEMENT A SPECIFIC FEATURE(S) FOR A DONATION ! All donations will be send to you will be to assist your general efforts.

**Comment by jeromerobert** [comment]
I need time and energy, not money so pdfarranger won't go that way. pdfarranger is a hobby and will remain a hobby. If someone want to make it more professional he should fork.

**Comment by Nokia808** [comment]
@jeromerobert 
I understand you when you say "it is a hobby & will remain a hobby" ! Not only your project but ALMOST ALL OPEN SOURCE projects are hobby ! Why you are always misunderstand us ! We want to help you no more no less ! When I see someone help me without know me & he/she is from other nationality & live far a way from me & all his work for free, then I like to thank him & assist him. That is it ! Almost always you misunderstand us ! I installed Protox & just when saw it's nice GUI in comparison to other Android tox program I donate it WITHOUT ASKING HIM FOR ADDING SPECIFIC FEATURE.

Anyway, I will never discuss you more & you are free to accept or refuse COMMUNITY (not a single person) support ....

Best regards, & many thanks for your hard efforts & for hard efforts of other peoples who working on the code of this program.
