### ISSUE TITLE
1.7.0 almost ready, please test !

### ISSUE THREAD

**Issue by jeromerobert** [pdfarranger/pdfarranger#358]
We now have many new and exciting stuff, it's time to release a new version. My TODO list:

- [x] Merge remaining PR
- [x] Regenerate translation files
- [x] Make a list of known translators and notify them that the floor is their
- [x] Call for testing the master branch
- [x] Write the release notes
- [x] Let the core team to review the release notes
- [x] Make a release candidates bundles for Windows
- [x] Bump version and tag
- [x] Create the Windows bundles

**Comment by jeromerobert** [comment]
@angsch @dreua @kbengs you should be able to see (and hopefully modify) the 1.7.0 release notes draft.

**Comment by jeromerobert** [comment]
@smarquespt, @Vistaus, @milotype, @volkov0aa, @sicklylife-jp, @ovari, @MichelePezza, @emintufan, @albanobattistella, @hahnavi, @juanma1980 Dear translator, PDF-Arranger has probably changed quite a bit since your last contribution. Now, the sources will be quite stable for the next 2-3 weeks, in order to prepare for version 1.7.0. This is a good time to update the translations if you can/want. The POT file is up to date.

**Comment by jeromerobert** [comment]
1.7.0rc1 Windows binaries are now available.

**Comment by angsch** [comment]
* Potential for confusion: The keyboard shortcuts in `config.ini` use capital/lowercase spelling inconsistently for the bool types, `maximized = False` vs `enable_custom = false` 
* Surprising: I import `foo1.pdf`, `foo2.pdf`, `foo3.pdf` through a multi-selection in the file chooser dialog. The iconview lists them in the order 1-2-3. The title bar says `untitled [foo2, foo1, foo3]`. Is the title bar supposed to have a specific order?

**Comment by Vistaus** [comment]
Thanks for tagging me so that I could update the translation in time :-) I just updated it and opened a PR :-)

**Comment by dreua** [comment]
> @angsch @dreua @kbengs you should be able to see (and hopefully modify) the 1.7.0 release notes draft.

Yes, I'm able to see and edit the release notes draft and it's massive! You, kbengs and angsch really did a lot of great work! Unfortunately I'm still very busy so I'll devote the time I can spare to the packaging (Flatpak, Fedora, openSuse) and the German translations if needed.

**Comment by smarquespt** [comment]
I have one question, whats are these used for?

Grid Split
Grid splitting
Horizontal Splits
Vertical Splits

"Invalid date format. Discard input." Should'n this be "Invalid date format. Discard**ed** input.

**Comment by jeromerobert** [comment]
@smarquespt Grid split is #306. It allow to split page to n (horizontal split) x m (horizontal) pages. *Grid splitting* is currently the title of the dialog box and *Grid split* the name of the action.

@angsch May I suggest that we remove the current "Split Page" action and rename "Grid split" to "Split Page". The default n x m values should also be changed from 1 x 1 to 2 x 1. It could also be remember but let's keep that for 1.8.0 as it's too much changes.

> "Invalid date format. Discard input." Shouldn't this be "Invalid date format. Input Discarded.

Ok I'll do the change ASAP.

**Comment by jeromerobert** [comment]
>> "Invalid date format. Discard input." Shouldn't this be "Invalid date format. Input Discarded.
>
> Ok I'll do the change ASAP.

Done: 8aff1b5 and 4011dc1cb2d4b1831afaaffc9fb5872c0279cf00

**Comment by jeromerobert** [comment]
I plan to tag the release today or tomorrow.

**Comment by jeromerobert** [comment]
Thank you all.

Now let pdfarranger and its developers rest for a month or two, i.e. have only PR for bug fix. In the meantime, I will look at the outline in PDF specification and pikepdf.

**Comment by dreua** [comment]
While building the flatpak I noticed a new dependency: python-dateutil>=2.4.0
Will add this to the RPMs, too.
