### ISSUE TITLE
[Windows] pikepdf's extension library failed to import

### ISSUE THREAD

**Issue by DavidQuartey** [pdfarranger/pdfarranger#380]
Hi all,

I installed pdfarranger (great features) but unfortunately, got this "pikepdf's extension library failed to import" error when I attempt opening it:
![image](https://user-images.githubusercontent.com/13510923/104075422-ad905500-520a-11eb-84bc-cc3e7ccb6267.png)

**I** noticed this [issue](https://github.com/pikepdf/pikepdf/issues/70) but not certain about how to go about using it to solve this issue. I will appreciate any help here. Thanks

**Comment by dreua** [comment]
How exactly did you install pdfarranger? (Msi, zip, pip, git?)
If you installed the msi please try this workaround first: https://github.com/pdfarranger/pdfarranger/issues/316#issuecomment-723506390

**Comment by jeromerobert** [comment]
You can also try with the 1.7.0rc1 release.

**Comment by DavidQuartey** [comment]
@dreua @jeromerobert I installed pdfarranger using the msi (pdfarranger-1.6.2-windows-installer). 

I installed the 1.7.0rc1 (through msi) release and it works fine. 

Appreciate the help and thanks for such a cool tool.

**Comment by jeromerobert** [comment]
Duplicate #316
