### ISSUE TITLE
Scaling, saving: loss of orientation in some cases

### ISSUE THREAD

**Issue by grahamperrin** [pdfarranger/pdfarranger#387]
### Steps

1. Take a PDF with a landscape page
2. scale the page to 50%
3. observe the scaled page, still landscape
4. save as …

### Expected

5. the page, landscape

### Actual result

5. the page, portrait

**Comment by jeromerobert** [comment]
I cannot reproduce this issue. Could you share the PDF file with which you observe this problem?

**Comment by grahamperrin** [comment]
Part of <https://github.com/pdfarranger/pdfarranger/issues/386#issuecomment-761231193> sparked a thought: 

> … pages can be already saved with a rotation in the PDF, e.g. when you rotate a page in pdfarranger or another application, save it and then load that file. …

You might make the issue reproducible with this file: 

[hello.pdf](https://github.com/pdfarranger/pdfarranger/files/5823805/hello.pdf)

1. open it
2. rotate clockwise
3. scale to 50%
4. save as …

----

https://github.com/pdfarranger/pdfarranger/issues/387#issuecomment-761180059

> … Could you share the PDF file with which you observe this problem?

I can not, sorry (copyright and other concerns). Now I wonder whether the three files that were provided to me were rotated prior to me receiving them. For one of the three: 

![image](https://user-images.githubusercontent.com/192271/104796798-59104b00-57b1-11eb-9ee7-d214af371b27.png)

The other two were created by PScript5.dll Version 5.2.2, produced by Acrobat Distiller 15.0 (Windows).
