### ISSUE TITLE
PDF optimizations for example reduce file size

### ISSUE THREAD

**Issue by grahamperrin** [pdfarranger/pdfarranger#388]
### Enhancement request

From <https://pikepdf.readthedocs.io/en/latest/index.html#id2>: 

> * …
> * Optimize PDFs similar to Acrobat’s features by downsampling images, deduplicating
> * …

**Comment by jeromerobert** [comment]
This is a meta issue as deduplication and downsampling are 2 differents stuff. I bet no one will work on this subject in the medium term, but let's give it a chance.

**Comment by dreua** [comment]
I think this is a stale feature request, let me know / reopen if you disagree.
