### ISSUE TITLE
MIME: allow PDF Arranger to be recognised as a handler for all types of file that it can handle

### ISSUE THREAD

**Issue by grahamperrin** [pdfarranger/pdfarranger#390]
Building upon https://github.com/pdfarranger/pdfarranger/pull/202

### Enhancement request

Please make the application recognisable for the purpose of opening PNG, JPEG and other types of file that it can handle. 

### Workarounds

With KDE Plasma 5 (on FreeBSD-CURRENT) I can remember an association, for example: 

![2021-01-15 05:14:46](https://user-images.githubusercontent.com/192271/104686242-b2667480-56f4-11eb-98b1-21956ff9ec20.png)

– however (unless I'm missing something) the remembrance can **not** be made without also setting the app as a default. 

So each such remembered association must be followed by demoting PDF Arranger, or (as shown below) promoting what was previously my preferred application: 

![2021-01-15 05:19:03](https://user-images.githubusercontent.com/192271/104686331-e5106d00-56f4-11eb-8788-3c2f843e5fb7.png)

**Comment by dreua** [comment]
I previously thought about this and wasn't sure we should do it since pdfarranger is not really a good program to open images in general, it's useful only for the special task of creating PDFs from images. On the other hand I don't see a big argument against it and since it is now requested we can just do it. Any thoughts from the other maintainers?

The implementation should be easily done by adding the correct mime-types in the desktop file. (PNG, JPEG/JPG, anything else?)

@grahamperrin Just to double-check, can you quickly confirm that this is only about the images and pdfarranger appears for opening PDFs by default (like it should)?

**Comment by grahamperrin** [comment]
The application is _not_ recognised as a recommended application by Firefox on (Tier-3) FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/104797009-cd97b980-57b2-11eb-873a-9274cb19c280.png)

– however I guess that a fix for this (if any) might be out of scope for https://github.com/pdfarranger/pdfarranger

It will be more meaningful for me to check with a cleaner installation of a desktop environment, with (say) Dolphin instead of Firefox. I'll do so as soon as I can.

**Comment by dreua** [comment]
@grahamperrin Let's try to stay on topic and with reproducible issues here, I'll hide your last comments since it's not adding value to this and the linked issue in my opinion.

**Comment by dreua** [comment]
For reference on MIME types here are excerpts from desktop files on my system:

Gimp:
`MimeType=image/bmp;image/g3fax;image/gif;image/x-fits;image/x-pcx;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-psd;image/x-sgi;image/x-tga;image/x-xbitmap;image/x-xwindowdump;image/x-xcf;image/x-compressed-xcf;image/x-gimp-gbr;image/x-gimp-pat;image/x-gimp-gih;image/tiff;image/jpeg;image/x-psp;application/postscript;image/png;image/x-icon;image/x-xpixmap;image/x-exr;image/webp;image/x-webp;image/svg+xml;application/pdf;image/x-wmf;image/jp2;image/x-xcursor;`

Excerpt from Evince:
`application/pdf;application/x-bzpdf;application/x-ext-pdf;application/x-gzpdf;application/x-xzpdf;` 
Note the `x-ext-pdf;` maybe we should add this. I couldn't really find a definition for the `x-ext` types but it surely sounds like a catch all for files with pdf extentsion.

eog aka "eye of gnome" aka "The Gnome image viewer":
`MimeType=image/bmp;image/gif;image/jpeg;image/jpg;image/pjpeg;image/png;image/tiff;image/x-bmp;image/x-gray;image/x-icb;image/x-ico;image/x-png;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-xbitmap;image/x-xpixmap;image/x-pcx;image/svg+xml;image/svg+xml-compressed;image/vnd.wap.wbmp;image/x-icns;`

img2pdf's [test files suggest it supports png, gif, tif and jpg extensions](https://gitlab.mister-muffin.de/josch/img2pdf/tree/master/src/tests/input), while the [source code lists even more](https://gitlab.mister-muffin.de/josch/img2pdf/blob/master/src/img2pdf.py#L2565):
`*.bmp *.eps *.gif *.ico *.jpeg *.jpg *.jp2 *.pcx *.png *.ppm *.tiff`

Getting this 100% right may be hard but we can probably do with a good estimate.
