### ISSUE TITLE
Remember window position on screen

### ISSUE THREAD

**Issue by pstein** [pdfarranger/pdfarranger#397]
Could you add an option to let PDF arranger remember its window position (not only size) on screen at exit.

**Comment by JATIN2111999** [comment]
Hey i did the changes as you needed my first PR happy to help :)

**Comment by dreua** [comment]
Welcome, unfortunately there was a misunderstanding, see my other comment. You can also force push to your feature branch to avoid creating new PRs

**Comment by JATIN2111999** [comment]
Got it Next time I will force push to feature branch
