### ISSUE TITLE
Does this new pikepdf feature has some impact on future enhancement for "Edit properties" ?

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#400]
Hi.

1st of all, I would to say thank you for new version 1.7.0 ! Really amazing ! 

I detected that new version of pikepdf has the following new features:
"The DocumentInfo dictionary can now be deleted with ``del pdf.docinfo``." - see:
https://github.com/pikepdf/pikepdf/commit/407b552ca7463a6d13e6763a3b0a17882ebf9ba2

Does the above has a future possible enhancement for the current "Edit properties" functionality ? In specific I know that there are 2 ways for editing such meta data: 1) real deletion & replacement of (author, keywords, title, creator tool, .........), & 2) just updating the meta data, where the old info still existing within pdf & can be detected by pdf analytical tools ...... I'm not sure what type of operation pikepdf perform (real deletion & replacement of data or just updating with maintaining old data). My concern is that: if pikepdf perform type (2) of operation, then can you use this new feature to allow real deletion & replacement of meta data ?? Also, is there other usefulness for this new feature ??

**Comment by jeromerobert** [comment]
I don't known. Please test and report.

**Comment by Nokia808** [comment]
@jeromerobert 
In this case the best thing is to ask upstream developer of pikepdf. As you see, I'm already opened a request on his repository asking him to help us because neither I'm nor you know !

**Comment by jeromerobert** [comment]
You test then we talk again. No need to ask pikepdf developer support. If you don't want to test I close the issue.

**Comment by Nokia808** [comment]
@jeromerobert 
Just understand me ! I'm simple desktop user & not strong with command line & libraries options. To be more clear: even QPDF, I'm using as a command line in only one process:

`$ qpdf --decrypt input.pdf output.pdf `

to remove encryption from certain pdf files. 

Other than this I do not use QPDF as a command line program because it is difficult on my & complex ...

Regarding pikepdf I do not used it before ..... Moreover, this issue is deep & I can not look to it because - again - I'm not programmer & for that I'm searching for GUI ..... Asked me about some thing beyond my ability ! I do not know how to test this issue because I'm GUI user .......

**Comment by jeromerobert** [comment]
Could you at least attach a PDF file with DocumentInfo inside ?

**Comment by Nokia808** [comment]
@jeromerobert 
Sure I can ! But please give me time till tommorrow since now is 11:50 PM in Baghdad time & I'm tired & it is time of my sleep.

Good bye.

**Comment by Nokia808** [comment]
@jeromerobert 
Look for this book:
https://b-ok.asia/book/846418/6cc987

It is of rich document info. Download it & examine.

**Comment by jeromerobert** [comment]
Damned you are so upsetting. I ask you to attached a PDF file, and you give a link to illegal content. Now I have to delete the whole discussion. Please don't ask again.

**Comment by Nokia808** [comment]
@jeromerobert 
You are aggressive & of bad ethics. I will delete your dirty application & will never install it again.
Also, I will close all feature request that I opened on this repository.

You are make like new nazi

**Comment by Nokia808** [comment]
@jeromerobert 
The last comment from me in this repository before leave it.
You said "I don't trust you when it comes to asking for useful feature requests."

I recommend you to visit a provisional psychiatrist to treat your paranoid personality disorder !!!
