### ISSUE TITLE
Scaling to different ratio

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#404]
Hi.

I noticed that new feature of change size of page does not allow user to change height of page without changing it's width & vase versa ! If I changed height then width also will changed, & if I changed width then height will changed also !

User should be able to change width independently from height & height independently from width.

Is this what were discussed about relative & absolute scale ? If yes, then I suggest on you to add new feature or sub-feature to allow for the missed feature .........

**Comment by jeromerobert** [comment]
We currently only support scaling to same ratio, so this is a feature request.

You alone are responsible for the majority of feature requests of PDF arranger. I don't trust you when it comes to asking for useful feature requests. I would only implement them if someone else requests them. So I close it.

**Comment by Nokia808** [comment]
@jeromerobert 
You are aggressive & of bad ethics. I will delete your dirty application & will never install it again. 
Also, I will close all feature request that I opened on this repository.

You are make like new nazi

**Comment by Nokia808** [comment]
@jeromerobert 
The last comment from me in this repository before leave it.
You said "I don't trust you when it comes to asking for useful feature requests."

I recommend you to visit a provisional psychiatrist to treat your paranoid personality disorder !!!
