### ISSUE TITLE
Adding a refresh/update button

### ISSUE THREAD

**Issue by A-DellN** [pdfarranger/pdfarranger#407]
Adding a refresh/update button to reopen/refresh the current pages so that if the PDF is modified by another program (typically annotated by an annotation software) it won't lose all the modifications.
It will be sufficient just adding _update the pages of one file_ and it would be easier I guess.

**Comment by dreua** [comment]
I don't see a big use case here but a lot of possible issues, for example: What happens if the number of pages of the input PDF changes? Handling this gracefully and in a way that satisfies all users may be impossible, therefore I'd vote to not add that option at all.

For your use case: Is there a reason you need to anotate the PDF after loading it in PDF arranger? 

Can you quickly confirm that your annotations are kept intact when saved first and arranged second? (I'm not sure we support those at all.)

**Comment by A-DellN** [comment]
Thank you for the quick response,
as for the first question: if the number of pages changes and I click refresh or re-open button the PDF file will be just re-opened that's it. It's just re-opening the file again using its path, nothing strange.

Of course there is a reason,before i describe it I want to evidence that it is not the only use case of that option but it just my case now and I believe that it will help in many other cases especially for professional use, I'm attending an online course and the professor uses a PDF slides aside his own digital-notes in a separated PDF so when i want to watch it(not in direct) i want to have one PDF containing 3 things:1) some chosen slides of the PDF slides 2)adding some pages of the professor's note  3)adding my own annotation on both notes in the same file, and here lies the whole thing.


My annotations are intact if saved first and arranged second in a two separated procedures, but if open a PDF file in pdfarranger and then adding annotation to the same file(with another software) saving it and trying to export/save the same file previously opened in pdfarranger  all the annotations will be lost.

I hope i was clear in answering the questions

**Comment by angsch** [comment]
I understand that you want to speed up the repeated arrangement of the same files. I agree that it can take some time to navigate through the file system if the files are not located in the same directory.

As for now, if the only changing document is your notes and no other modifications (rotations etc) are necessary, I would create auxiliary files for the selected PDF slides and then use the command line interface. Pass the file names in the order you want them imported as command line arguments. That essentially gives you a refresh functionality. The reason for the auxiliary files is that the import of a subset of pages through the command line is currently not possible.

**Comment by dreua** [comment]
@A-DellN please take the time to make your last post easier to read. Use Github's edit and preview functions and fix the grammar, capitalization (i VS I, start of sentence) and formatting (spaces, list items in single lines).

Make sure that there is a clear and concise answer to my question:

> Can you quickly confirm that your annotations are kept intact when saved first and arranged second? (I'm not sure we support those at all.)

I'll hide this comment once I'm satisfied with your edits, thanks!

**Comment by dreua** [comment]
As angesch already pointed out: Simple repetitive tasks are best automated via command line / scripts. Most functions from pdfarranger can be done with with the [qpdf cli](http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.invocation) (useful [examples in tldr](https://tldr.ostera.io/qpdf)).

**Comment by dreua** [comment]
Closing due to lack of feedback. Was my request for edits unreasonable or too harshly worded? Feel free to reopen.
