### ISSUE TITLE
Ctrl + drag & drop create referenced pages (operation done to one page will be applied to other pages)

### ISSUE THREAD

**Issue by kbengs** [pdfarranger/pdfarranger#410]
Found a interresting bug. To reproduxe:
* Drag & drop a page while ctrl is pressed -> page will be copied to new location
* Rotate one of theese two pages -> the other page will be rotated also 

Actually all operations done to one of the pages will be applied to all other pages that are created with ctrl + drag & drop.

Could of course be a feature. But I think it is unexpected.

**Comment by angsch** [comment]
I did a small mistake when I tried this out and got another strange behavior:
* Drag & drop a page while ctrl is pressed -> Now two pages are selected.
* Rotate once while having both pages selected ->Both pages are rotated by 180°.

**Comment by kbengs** [comment]
>  did a small mistake when I tried this out and got another strange behavior:

I guess what is happening here is that first the first page is rotated 90 degrees, but the second page is referenced, so it will be rotated also. Then it rotates the second page 90 degrees, and as the first page is referenced it will be rotated also. So result is a 180 degree rotation.
