### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#412]
@pdfarranger core contributors: How do you feel about switching to "main" as the default branch name? Many projects (including Github and Fedora) are doing this switch now and I personally think it's a good idea.

If we decide to do this, I can take care of all the code changes, but I don't have access to the repository settings to change the default branch. It's probably easiest if @jeromerobert woud just rename the branch in Github.

[github/renaming: Guidance for changing the default branch name for GitHub repositories](https://github.com/github/renaming)

**Comment by jeromerobert** [comment]
> How do you feel about switching to "main" as the default branch name

I have no opinion.

> I don't have access to the repository settings

You now have ;-)

**Comment by dreua** [comment]
@jeromerobert can you take care of codacy? It didn't pick up the new main branch and I have difficulties accessing the project in codacy.

**Comment by dreua** [comment]
> @jeromerobert can you take care of codacy? It didn't pick up the new main branch and I have difficulties accessing the project in codacy.

Resolved: Today I could change the branch in codacy.

I also changed the default branch in Codecov.

**Comment by dreua** [comment]
Alright I think I got everything updated and it looks good. Only loss is the Codecov history but I assume that this is not really needed by anyone and trying to fix it would be a waste of time, would that assumption be correct?

## Local clones

Github is quite helpful with commands to update you local clones, but I repeat them here in case you missed the message:

Replace `origin` with the remote name you chose for this repository (maybe `origin` is correct for you, but in my case it's `upstream`)

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
```

How I updated my fork:

1. Go to your fork, Settings, Branches, click the Pencil, rename to main.
2. Ignore the 500 error, I got this even with the main repository but it seems to have no effect :shrug:
3. `git remote update --prune` should get rid of all the old remote refs for all remotes.
