### ISSUE TITLE
CI: Windows builds

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#417]
> Should we give fully automated Windows builds another try? I think an exe build per PR would be useful for testing.

Yes ! Well I would prefere to have it for `main` (only or also ?). This way we could have a link in the wiki or even in the `README.md`. I think very few people will test binaries from PR but a bit more would test `main`.

_Originally posted by @jeromerobert in https://github.com/pdfarranger/pdfarranger/issues/416#issuecomment-777795410_

**Comment by dreua** [comment]
The PR should work for both PRs and main and I think it doesn't hurt to keep both. (Of course you are right, main is more useful for general testing.)

**Comment by dreua** [comment]
Note to self: compare #154 

Little update: I had a bit of a struggle with your win32 docker container: Still can't build it but the pre-build version works now when I run it with `--storage-opt ignore_chown_errors` (maybe podman specific and not sure if this has any negative side effects - we'll see). I'll building an exe as soon as I find the time and then it's only a matter of automating and uploading (I think). Maybe I'll need to fix the docker build.

**Comment by jeromerobert** [comment]
`jeromerobert/wine-mingw64` does not include requires software to run `./setup.py build` so I run it on the host system, not in the container. This probably not suitable for Github Action. May be it would be better to add `distutils-extra` in `jeromerobert/wine-mingw64` and run `./setup.py` in the container. Not that `./setup.py build` must always be ran outside of Wine (`distutils-extra` must be installed on Linux, not in Wine).

I always run the `bdist_xxx` targets in the containers as root. Files get created in `dist/` are owned by root. That's the default behavior with Docker and may be not with Podman.

**Comment by jeromerobert** [comment]
It will be a bit of a struggle to build pikepdf 2.9.1 with mingw64. Uncompatible Visual C++ options have appeared. This probably comes from `Pybind11Extension` which appeared in [2.0.0](https://github.com/pikepdf/pikepdf/commit/19b9b0391e8abc00905cea2df4ce0f1c6c0bb9c2). I'm on it.

**Comment by jeromerobert** [comment]
Still trying...
https://github.com/pikepdf/pikepdf/pull/184/commits/a23d0b49619c26f24aeff23abedc8ac04d877fc0
https://github.com/jeromerobert/pybind11/commit/96fbc5c95152c922aa4934361ae6690d2875bea3
