### ISSUE TITLE
Remove `pip install -e` from documentation

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#420]
I confirm that `pip install -e .` do not properly install `.ui` and translation files. You must not use the `-e` flag with pdfarranger.

_Originally posted by @jeromerobert in https://github.com/pdfarranger/pdfarranger/issues/381#issuecomment-778682003_

**Comment by dreua** [comment]
Have you considered `pip3 install .` without -e instead? (My issue title was misleading here, sorry.)

`pip install --user .` works quite well in my experience. It installs the desktop, ui, translations and `pdfarranger` entrypoint in the appropriate user directories. Upgrades and uninstalls without issues. (Only the icon is missing in the application menu, but that's probably not pip's fault but my Gnome's.) It's basically the pip3 installation we recommend in the Readme, just from your local source.

One just needs to realize that this creates copies of all the files and therefore you need to redo it for any changes to take effect.

**Comment by jeromerobert** [comment]
There is no need to use `pip` before running `python3 -m pdfarranger`, so no, I did not considered it.

**Comment by dreua** [comment]
Alright, so there was really no point in having a pip install there in the first place, that confused me. Thanks for the fix and clarification!
