### ISSUE TITLE
pikepdf breaks local hyperlinks (but not online ones)

### ISSUE THREAD

**Issue by Just-Another-Gnumer** [pdfarranger/pdfarranger#430]
My other bug was resolved.

LibreOffice allows me to create PDF files with local hyperlinks; when clicked they warp to a given page. Here is a example. Clicking should warp to page 2.
https://www.keepandshare.com/doc7/64792/test-pdf-11k?da=y    

This local hyperlink is preserved when edited in old versions of pdfarranger (1.3.1) but not in 1.70.  I identified pikePDF as the culprit. This is because 1.3.1 installed in a different directory had the exact same bug until I ran `pip3 uninstall pikepdf`. Local hyperlinks in PDF's are vital for my workflow and I hope this gets fixed.  This problem is also present in the flatpak version so I know it is not just my machine.

**Comment by dreua** [comment]
> My other bug was resolved.

Please leave a comment on this resolved bug, ideally with a short description of the solution, and close it.

**Comment by dreua** [comment]
And yes, I think this is a limitation of the underlying libraries, namely pikepdf and qpdf. You can use the old version with Pypdf2 but that has a lot of other issues that were never fixed.

**Comment by Just-Another-Gnumer** [comment]
I would like to know if there are future plans to fix this problem? As preserving local hyper links are vital for my workflow. I really do appreciate the new features and bug fixes in 1.70 and would love to update once this problem is resolved.

**Comment by dreua** [comment]
I'm not aware of such plans but we have similar feature requests for outlines and the qpdf maintainer is working on support for such features in general, I think.

I wonder if we could make it work for the special case when there is only one document with links and if it is loaded as the first file. At least qpdf cli can preserve links of the first document, but this needs more research in any case and would also be a workaround which is hard to explain to users. Not sure what you are doing but maybe you can achieve it with qpdf?

**Comment by jeromerobert** [comment]
Duplicate #339 (hyperlinks are *destinations*)
