### ISSUE TITLE
only pages can be inserted - can't save pdf

### ISSUE THREAD

**Issue by artofit** [pdfarranger/pdfarranger#431]
Manjaro XFCE 20.2.1(with latest updates) & Pdf Arranger 1.7.0.

Every time I try to save(or save as) a modified pdf it does not do prompt a window with following error:
only pages can be inserted

I never experienced this bug with Pdf Arranger before

**Comment by Lunarage** [comment]
Arch Linux & Pdf Arranger 1.7.0

Can confirm this behaviour.

This is the error message i get when trying:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 748, in choose_export_pdf_name
    self.save(only_selected, file_out)
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 210, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 796, in save
    exporter.export(self.pdfqueue, to_export, file_out, m)
  File "/usr/lib/python3.9/site-packages/pdfarranger/exporter.py", line 78, in export
    pdf_output.pages.append(new_page)
TypeError: only pages can be inserted
```

**Comment by jeromerobert** [comment]
Duplicate #427

**Comment by MSSProvenance** [comment]
I ahve the same problem. The only change to my system that I'm aware of is upgrading from Ubuntu 20.10 to 21.04, plus installing recommeded software updates.

**Comment by panosprotopapas** [comment]
> I ahve the same problem. The only change to my system that I'm aware of is upgrading from Ubuntu 20.10 to 21.04, plus installing recommeded software updates.

Exact same situation
