### ISSUE TITLE
TypeError: only pages can be inserted with libqpdf >= 1.2.0 **AND**  pikepdf < 2.7.0

### ISSUE THREAD

**Issue by m-holger** [pdfarranger/pdfarranger#434]
In some circumstances, pdfarranger fails to save files and displays a message box with the above message instead. Source installs of pdfarranger between 24 Feb and 27 Feb 2021 are likely to be affected by this problem.

The problem is due to a known issue in version 2.6.0 of pikepdf, a library used by pdfarranger.  Upgrading to the latest version of pikepdf should solve the problem, using whatever method your system uses to update Python package. For example,

pip install --user pikepdf==2.8.0

worked on my system.

More detail  can be found in the closed issue #427

**Comment by jeromerobert** [comment]
I prefer to keep stuff related this issue on #427.

> The problem is due to a known issue in version 2.6.0

Not exactly, this is more related to libqpdf.
