### ISSUE TITLE
Enhancement to "About" dialog

### ISSUE THREAD

**Issue by m-holger** [pdfarranger/pdfarranger#439]
Would it be possible to add something along the lines of

(PDF Arranger uses pikepdf vers. ??? and  libqpdf vers. ???)

to the "about" dialog? This information is relevant when reporting issues, and determining the versions (especially for libqpdf) is not all that intuitive.

Happy to have a stab at it myself if it helps.

**Comment by dreua** [comment]
Yes! I've thought about this a few times but never came around to do it, please go ahead! I'm happy to help, just create a PR or tag me in a comment on your fork's commit and I'll be there.

The code to get pikepdf and libqpdf versions is quite simple: `python3 -c 'import pikepdf; print("pikepdf:", pikepdf.__version__); print("libqpdf:", pikepdf.__libqpdf_version__)'`

Just those two versions would be a great start, I'd say that's our [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product).

If you are bored by those two versions, I already have Ideas for some additions on my mind:

- [ ] Include pdfarranger version
- [ ] Easy to copy and paste / copy button / create prefilled GH issue button (VS Code does this, probably just some URL parameters. I can have look if you want)
- [ ] Python file path:  `__file__` (Should tell us: Win/Linux, installed as admin or user, maybe even flatpak or not?)

**Comment by m-holger** [comment]
#445 implements the basic requirement, i.e. report libqdf and pikepdf versions.

With regard to the enhancements suggested by @dreua, I would suggest that the priority should be 
to provide additional useful information, leaving the niceties such as pre-filled GH issue pages for later.
Assuming this is accepted, I require some guidance on the what and how.

# What further information do we want to display?

@dreua identified the Python file path: `__file__ `(Should tell us: Win/Linux, installed as admin or user, maybe even flatpak or not?)

I would assume that part of `sys.implementation` would also be useful: `_multiarch, name, version`?

``` python
>>> sys.implementation
namespace(_multiarch='x86_64-linux-gnu', cache_tag='cpython-38', hexversion=50857456, name='cpython', version=sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0))
```


Is there anything else?

# How do we want to display the information?

I see 3 main options:

## 1. Repurpose the credits panel

Change the button label from "Credits" to, say, "More Info", and add an additional section (after the creator and contributor sections)
to hold the additional diagnostic info and perhaps (a link to) some instructions on how to report issues.

Main advantages:

* easy to implement 
  * no change to AboutDialog required
  * existing methods to add new sections
* easy to copy info to clipboard
* relatively easy to add buttons/automations later

## 2. Create a link to a local webpage

Create another link (below the link to the project website), say 'Reporting Issues', that point to a local webpage with some instructions 
and including all the additional  diagnostic info. There is an existing unused label underneath the link to the project website that can 
be repurposed    

## 3.Add new panel

Add a new button to the right of the license button to display a new panel with the diagnostic info.

This is the most flexible option, but also requires the most work



My preference would be option 1 - it is the easiest to implement and  achieves the purpose of providing all the diagnostic info. I feel that any additional effort would be better spend on adding additional capabilities to PDF Arranger

**Comment by dreua** [comment]
I think sys.implementation is actually not that interesting, can't remember any bugs where that mattered.
It's probably most efficient to wait for the next bug reports and see what information is missing, then we can decide what else would be interesting. I'll try to take note of missing information in this issue to collect some data.
