### ISSUE TITLE
Split pages

### ISSUE THREAD

**Issue by jcuenod** [pdfarranger/pdfarranger#442]
In 1.7.1, I'm using split pages and getting bizarre results (not what is displayed in the preview). I would upload the file I'm splitting but it's copyright). The first and last pages were different sizes and I was adding cropping to the split pages as well.

Maybe screenshots will illustrate:

This is the initial import

![Initial import](https://user-images.githubusercontent.com/4253884/112207362-02762180-8be5-11eb-8e72-f85d31bad8b7.png)

I deleted the first page, cropped the second and, after splitting the rest, added extra cropping (to get rid of black edges):

![After splitting, cropping and deleting](https://user-images.githubusercontent.com/4253884/112207369-05711200-8be5-11eb-92f2-139db9172959.png)

The output, however, looks like this (reopened with PDF Arranger):
![Screenshot from 2021-03-23 14-38-21](https://user-images.githubusercontent.com/4253884/112207714-77495b80-8be5-11eb-878e-d839582941f7.png)

**Comment by angsch** [comment]
Can you provide an instruction sequence to reproduce the problem? What crop did you use? What is the split pattern?

**Comment by jcuenod** [comment]
Ja, I wasn't sure how to provide sufficient details. Is the updated comment useful enough?
The method was:
1. Delete first page (first page is a random size)
2. Split pages after second page (second page is another random size)
3. Crop even set of split pages to 51% / 8% (left / right)
4. Crop odd set of split pages to 8% / 51% (left / right)
5. Cropp first page (i.e. original second page) 8% / 1% (left / right) [to try to get it similar to the other pages]

**Comment by angsch** [comment]
Thanks. The issue sounds like a saving/reloading problem similar to #291. Could you export to a new PDF file and open it with a classic PDF viewer? Do you get the intended output?

**Comment by jcuenod** [comment]
No. If I open the file, follow these steps, and save to a new location, it produces the same output.

**Comment by jcuenod** [comment]
Thanks! I'll test when I get the chance.

**Comment by dreua** [comment]
> Thanks! I'll test when I get the chance.

That would be great, looking forward to hear from your results.

**Comment by dreua** [comment]
I can build a flatpak with this change if that helps anyone with testing? Is this important enough for a 1.7.2?

**Comment by angsch** [comment]
> I can build a flatpak with this change if that helps anyone with testing? Is this important enough for a 1.7.2?

Let's wait for jcuenod's feedback. The scan appears to be special. I could not reproduce the problem until kbengs provided a PDF. The issue has been present in PDF Arranger since the first release, so it a really good catch.

**Comment by jcuenod** [comment]
Yes, just tested the latest commit on Arch. Works perfectly. Great job!
