### ISSUE TITLE
Split page + export with unexpected result (on certain pdf)

### ISSUE THREAD

**Issue by kbengs** [pdfarranger/pdfarranger#443]
![split issue](https://user-images.githubusercontent.com/60842129/112328656-39b90100-8cbf-11eb-811f-063c3c019535.png)

Steps to reproduce:
* Open [Input.pdf](https://github.com/pdfarranger/pdfarranger/files/6197960/Input.pdf)
* Split to 4 pieces
* Export  -> [Output.pdf](https://github.com/pdfarranger/pdfarranger/files/6197964/Output.pdf)

Borders that are not visible in input.pdf are visible in output.pdf

**Comment by angsch** [comment]
Interesting. The root cause appears to be the presence of additional boxes. `pdfinfo -box Input.pdf` gives

```
MediaBox:           0.00     0.00   627.00   825.00
CropBox:           20.95    21.02   605.98   804.05
BleedBox:          20.95    21.02   605.98   804.05
TrimBox:           20.95    21.02   605.98   804.05
ArtBox:            20.95    21.02   605.98   804.05
```
