### ISSUE TITLE
Bug reporting: Create issue templates

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#447]
@pdfarranger how do you feel about issue templates? I think we could have one for feature request and one for bug reporting, each providing some basic structure and information for the issue creator. I see those often around GitHub and I think it could be useful for reporters and improve the initial reports so that we need less back and forth.
Templates are just suggestions, nobody needs to follow them if they don't want to.

I'm looking for feedback from the regular contributers here. If some positive feedback comes in I'll start drafting those templates 

Related: #439 already improved access to debug information within PDF Arranger. I think we can extend that as needed.

**Comment by angsch** [comment]
I have seen the issue templates mostly in bigger projects, but I don't see any reason why PDF Arranger should not have one.

**Comment by dreua** [comment]
> I have seen the issue templates mostly in bigger projects [...]

OT: I think [we are growing](https://dreua.github.io/1616624000.html) :wink:

**Comment by kbengs** [comment]
Sounds like a good idea.

**Comment by jeromerobert** [comment]
Done for bug report: 16fba788aca408a39d5725f88ce038e446ed699f

I don't feel like making one for feature requests as it would be almost free form. I also wonder if the Github Issue Tracker is the best entry point for users who want to submit feature requests. May be we need a Gitter/Discord/Slack/Mattermost or whatever.

**Comment by dreua** [comment]
Thank you! I think think we can close this issue for now and see how that works in practice. I'm not sure about additional channels, keeping it all in one place has its advantages imo. I've never used Gitter though, maybe I'd need to look into that first.
