### ISSUE TITLE
JPG with embedded preview results in double import

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#457]
When I import this [JPG image](https://angelika-schwarz.net/nextcloud/index.php/s/ZAmq954deBPNKg6/download) via drag-and-drop, the import is slow and I get a double import with strange thumbnails

![image](https://user-images.githubusercontent.com/17718454/113015761-26ee7280-917e-11eb-8dd8-3f21cf13404d.png)

img2pdf version 0.4.0

**Comment by m-holger** [comment]
This appears to be an issue between  img2pdf/PIL and JPEG. Running

```
img2pdf -v -o DSC02306.pdf DSC02306.JPG
```
creates a 2 page 20.5MB pdf and produces the following diagnostics

```
DEBUG:root:imgformat = other
DEBUG:root:Converting frame: 0
DEBUG:root:input dpi = 350 x 350
DEBUG:root:rotation = 0°
DEBUG:root:input colorspace = RGB
DEBUG:root:width x height = 4912px x 3264px
DEBUG:root:Colorspace is OK: Colorspace.RGB
DEBUG:root:read_images() encoded an image as PNG
DEBUG:root:Converting frame: 1
DEBUG:root:input dpi = 350 x 350
DEBUG:root:rotation = 0°
DEBUG:root:input colorspace = RGB
DEBUG:root:width x height = 1616px x 1080px
DEBUG:root:Colorspace is OK: Colorspace.RGB
DEBUG:root:read_images() encoded an image as PNG
DEBUG:PIL.Image:Error closing: 'NoneType' object has no attribute 'close'
```
It very much looks like img2pdf does not recognise the file as a valid JPEG

(There does not seem to be anything seriously wrong with the JPEG - LibreOffice Writer manages to embed it in a pdf without any problems)

**Comment by angsch** [comment]
Interesting. That at the very least explains where the double import comes from. The JPG error check does not show anything suspicious.
```
jpeginfo -c DSC02306.JPG
DSC02306.JPG 4912 x 3264 24bit Exif  N 5668864  [OK]
```
@m-holger Do you want to open an issue at img2pdf?

**Comment by dreua** [comment]
Very interesting question, I'm quite sure that this file with JPG extension (!) somehow contains two images, one preview and the main image that should be used.
Couldn't find much about that on the internet but it seems to be a thing, albeit a rare one:
- [jpeg - Do jpgs have "layers"? - Photography Stack Exchange](https://photo.stackexchange.com/questions/9606/do-jpgs-have-layers/9608#9608)
- Looks like it could be the preview included in EXIF data: [The Metadata in JPEG files - Exiv2](https://dev.exiv2.org/projects/exiv2/wiki/The_Metadata_in_JPEG_files#21-Exif)

```
$ file DSC02306.JPG
DSC02306.JPG: JPEG image data,

Exif standard:
[TIFF image data, little-endian, direntries=12, description= [...], manufacturer=SONY, model=SLT-A37, 
orientation=upper-left, xresolution=204, yresolution=212, resolutionunit=2, software=SLT-A37 v1.02, 
datetime=2013:07:21 17:56:12],

baseline, precision 8, 4912x3264, components 3
# Added line breaks and shortened for readability
```

**Comment by m-holger** [comment]
img2pdf recognises that there are multiple image, and printing all of them is the default behaviour of img2pdf. To that extent there is no problem. (Whether PDF Arranger could/should recognise previews and eliminate them from the output is a different question)

Still leaves the problem that img2pdf converts the jpeg to png, increasing the size of the first frame to 18.1 MB

@angsch I assume the "do you want ..."  was a polite way of saying "please open ...". On that assumption, will do.

**Comment by m-holger** [comment]
img2pdf issue is at https://gitlab.mister-muffin.de/josch/img2pdf/issues/93

**Comment by m-holger** [comment]
The problem with the increase in file size will be fixed in the next release due out in the next few days.

img2pdf will continue to produce 2 pages, one with the main image and one with the preview image. PDF Arranger users will need to delete the page with the preview image manually. 

@angsch  Do you want to change the title to something like "JPEGs with embedded preview result in large file size (img2pdf<=0.4.0 only) and double import" and close the issue?

**Comment by dreua** [comment]
Let's see when imp2pdf > 0.4.0 comes out and hope it doesn't take too long on your distro of choice:
![repology](https://repology.org/badge/versions-matrix.svg?projects=pdfarranger,python:pikepdf%3E=1.7,pdfshuffler,img2pdf&header=pdfarranger%20packaging%20status)
