### ISSUE TITLE
Packaging for Alpine Linux

### ISSUE THREAD

**Issue by antonialoytorrens** [pdfarranger/pdfarranger#466]
Thank you very much for making this awesome utility that I use almost every day.
I'd like to package it for Alpine Linux (see here):
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/20565

However, I need to run the tests on a server (no GUI).
I've tried doing them with `xvfb-run python3 setup.py test`, without luck.
So, do you have any way to run these tests on a server environment?

Thank you very much in advance.

**Comment by dreua** [comment]
I think the tests are already running on alpine, see
https://github.com/pdfarranger/pdfarranger/blob/42ba479775a8474a3aad82d1b00f0d7d61580bb1/.github/workflows/install.yml#L19

and https://github.com/jeromerobert/pdfarranger-docker-ci/blob/master/ci/Dockerfile

Does this information help you fix the problem? @jeromerobert may have more in depth knowledge about this stuff.

Thanks for packaging and let me know if you need anything else, I'm package maintainer on Fedora and Flathub. Please leave this issue open as a reminder for me to edit the releases wiki page. (Or do that yourself if you like.)

**Comment by jeromerobert** [comment]
> I've tried doing them with xvfb-run python3 setup.py test, without luck.

Could you elaborate ? Logs, error messages ? Our tests are indeed running in an Alpine based Docker container.

**Comment by antonialoytorrens** [comment]
Sorry for the late response, that's exactly what I need!

`python3 -X tracemalloc -u -m unittest discover -v -f -s tests `
I was missing this command when running tests, as well as some packages required for it.

> Thanks for packaging and let me know if you need anything else, I'm package maintainer on Fedora and Flathub.

Thank you very much for helping @jeromerobert and @dreua, I really appreciate it.

> Please leave this issue open as a reminder for me to edit the releases wiki page. (Or do that yourself if you like.)

Well, first I'll merge it into the testing repository (edge). Nevertheless, it'll take some time for it to be included in the release versions of Alpine (community repository).

I'll leave this issue open. So if this package is finally merged into testing, I will update it to the wiki.

**Comment by dreua** [comment]
I just added Alpine to the wiki page.
Thanks again and please reopen if you need anything!
