### ISSUE TITLE
Windows 8.1 - "No Disk" error

### ISSUE THREAD

**Issue by emintufan** [pdfarranger/pdfarranger#467]
I am using a PC with genuine and updated Windows 8.1 Single Language in Turkish. I installed the latest (1.7.1) version of pdfarranger and I am having "Windows - No Disk" "Exception Processing Message 0xc0000013 - Unexpected parameters" error when trying to open files. After clicking 5-6 times to "Cancel" or "Continue" button it has gone and files become selectable.
![error](https://user-images.githubusercontent.com/10631784/115394112-1bc1bc00-a1eb-11eb-86cc-cee610560f2b.png)

**Comment by dreua** [comment]
I've never seen that. Have you considered upgrading to windows 10? It might just fix that issue along the way.

Does this message appear when starting pdf arranger or when trying to open a file?

**Comment by emintufan** [comment]
No, I didn't, cause it's already getting updates by Microsoft.

**Comment by angsch** [comment]
The issue is a Windows problem and not in PDF Arranger. 
https://answers.microsoft.com/en-us/windows/forum/all/windows-no-disk-exception-processing-message/caf10733-6b5d-433f-a57a-b1a2ddccaf29

For now I hope that the problem does not resurface and is due to not safely removed devices.

**Comment by dreua** [comment]
Yeah, I'm afraid there is nothing we can do here, sorry.
