### ISSUE TITLE
Keyboard shortcut to move pages around

### ISSUE THREAD

**Issue by csu333** [pdfarranger/pdfarranger#469]
Would it be possible to have a keyboard shortcut to move pages around? CTRL+arrows and SHIFT+arrows are used to select pages. ALT+arrows could be used to move pages from their current positions. The last selected page would be used as reference for the movement.

**Comment by dreua** [comment]
Possible: of course!

Should we do it? I don't think so.

Workaround: Use Ctrl+x/c/v

**Comment by dreua** [comment]
Out if curiosity: is there any comparable software with this feature? Is there a common UX pattern or a common shortcut? Ideally we would follow other Gnome apps regarding UX.

**Comment by m-holger** [comment]
To me a keyboard shortcut for moving pages makes sense. The advantage over cut and paste is that it makes the user intent clear - which would be valuable when there are multiple pastes and the page is the destination of outlines / links.

**Comment by dreua** [comment]
What are we currently using to rotate pages? Alt+Arrows sounds good to me if it isn't already taken by something else.

I haven't missed that feature but I'm not against merging a good PR. Needs some UX consideration imo.

**Comment by jeromerobert** [comment]
I guess that's gonna be difficult. `Gtk.IconView` is designed for drag & drop and copy/past, not for "moving" items.

**Comment by dreua** [comment]
*Let's give this 3 weeks. If nothing productive comes up, it should be closed and tagged `stale feature`.*

**Comment by m-holger** [comment]
There is no reason to not implement this as a cut/paste as far as the IconView is concerned.

If we want bookmarks/links to work, when duplicating pages the page objects will need to keep track of which page is the original (and therefore the destinations of existing links) and which one is the duplicate.

**Comment by dreua** [comment]
> If we want bookmarks/links to work, when duplicating pages the page objects will need to keep track of which page is the original (and therefore the destinations of existing links) and which one is the duplicate.

How is this related to keyboard shortcuts?

**Comment by m-holger** [comment]
@dreua

> How is this related to keyboard shortcuts?

I guess moving pages is completely unrelated to links, outlines and bookmarks. Perhaps mark my comments as off-topic.
