### ISSUE TITLE
Suggestion on improving Page Format functionality

### ISSUE THREAD

**Issue by MS-Windows** [pdfarranger/pdfarranger#470]
In Menu -> Edit -> Page Format, allow setting page size to a user-chosen combination (e.g. 210mmx297mm, ISO A4) to crop (or expand) pages. Users may choose how the original page will be placed on the cropped or expanded "canvas".
This functionality works like what "Resizing Canvas" does in Adobe Photoshop.
Will be a handy bonus for PDF Arranger. ;-)
![图片](https://user-images.githubusercontent.com/28992529/115829079-1b226300-a441-11eb-98f4-c4ef10cc33c1.png)

**Comment by MS-Windows** [comment]
Allowing minus values while cropping page(s) works just the way how page(s) are being expanded, isn't it?
(Currently it seems the values are minimum 0)

**Comment by angsch** [comment]
> Users may choose how the original page will be placed on the cropped or expanded "canvas".

Isn't this the same as allowing the user to add arbitrary margins to a page?

> Allowing minus values while cropping page(s) works just the way how page(s) are being expanded, isn't it?
(Currently it seems the values are minimum 0)

This is already on the feature wish list #267

**Comment by MS-Windows** [comment]
> > Users may choose how the original page will be placed on the cropped or expanded "canvas".
> 
> Isn't this the same as allowing the user to add arbitrary margins to a page?
> 
> > Allowing minus values while cropping page(s) works just the way how page(s) are being expanded, isn't it?
> > (Currently it seems the values are minimum 0)
> 
> This is already on the feature wish list #267

Sure!
#267 covers page extension, so #470 improvement suggestion remains only the user-spcified page size and how pdfarranger can handle scaling and positioning (9 anchors method or something like this).
For mixed h/v layout documents this might be another tweaking point.
Glad to see pdfarranger growing into a better free PDF tool.😀
