### ISSUE TITLE
"only pages can be inserted" save error

### ISSUE THREAD

**Issue by Manichaean** [pdfarranger/pdfarranger#478]
This refers to version 1.6.2 as provided by Ubuntu 21.04 repos. Importing two PDFs you then want to save as one lets you put in the name you want to call the new document, but then a window shows up saying "only pages can be inserted" and that's it.
I see there is a new version here. Perhaps that fixes the issue and could be uploaded to the Ubuntu 21.04 repos? Thank you for an incredible program.

**Comment by dreua** [comment]
I'm pretty sure that this is indeed already fixed. You could try the Flatpak to double check.

We can not upload anything into ubuntu repos, please ask the Ubuntu community/support about that. Pretty sure that the Debian package maintainers for PDF Arranger could update the package if they wanted to, at least that's what I do in my other role as package maintainer on Fedora Linux

**Comment by dreua** [comment]
I think this is all we can do here but please feel free to comment or reopen the issue if there's anything else.

**Comment by Manichaean** [comment]
I'll check again and ask Ubuntu to update their repos if it's not sorted. I love this program, and I wanted to thank you as well for making it. :)

**Comment by timrichardson** [comment]
Reported here: https://bugs.launchpad.net/ubuntu/+source/pdfarranger/+bug/1926289

**Comment by dreua** [comment]
This was probably triggered by updating pikepdf. See #427
