### ISSUE TITLE
Add symbolic icon

### ISSUE THREAD

**Issue by foreverxml** [pdfarranger/pdfarranger#479]
Today I was doing some tests for accessibility on my desktop, and I came across this:
![no symbolic icon for PDF arranger](https://user-images.githubusercontent.com/52264162/116578503-b8144e80-a8ce-11eb-9d11-f6ce521a8f8f.png)
It seems that this app is missing a symbolic icon. I checked the directory for the symbolic icon and found this:
![symbolic-not icon](https://raw.githubusercontent.com/pdfarranger/pdfarranger/main/data/icons/hicolor/scalable/apps/com.github.jeromerobert.pdfarranger.svg)
I'll try to design a new symbolic icon for this wonderful app. Cheers!

**Comment by foreverxml** [comment]
Update: I designed one! Here it is:
![symbolic icon](https://raw.githubusercontent.com/foreverxml/pdfarranger/main/data/icons/hicolor/symbolic/apps/com.github.jeromerobert.pdfarranger-symbolic.svg)
Any feedback? (should I add/remove some things?) Have a good day!

**Comment by foreverxml** [comment]
## First question:
Yes! You can find the PR [here](https://github.com/pdfarranger/pdfarranger/pull/480).
## Second question:
In the shell, you have the top panel:
![Screenshot from 2021-04-30 10-38-58](https://user-images.githubusercontent.com/52264162/116726383-6b994380-a9a0-11eb-8d02-0a13a20dc2cf.png)
The app menu next to Activities contains the symbolic icon.
![Screenshot from 2021-04-30 10-39-27](https://user-images.githubusercontent.com/52264162/116726386-6c31da00-a9a0-11eb-994c-ceb134c41e5b.png)
These icons are also used in the High Contrast icon set.

**Comment by kbengs** [comment]
I think it looks good, but it is quite different from the normal icon. Could/should it look more like the normal icon?

**Comment by foreverxml** [comment]
> I think it looks good, but it is quite different from the normal icon. Could/should it look more like the normal icon?

It does not have to look the same as the original, as shown by [Curtail](https://github.com/Huluti/Curtail). It does need to have similarities, so I am working on adding some similarities. I'll update the PR.
