### ISSUE TITLE
Other PDF / Paging / Scanning tools

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#481]
Recommended
- [paperwork](https://gitlab.gnome.org/World/OpenPaperwork/paperwork) (Great for document archival, features scanning, OCR, tagging, powerful full text search)
- [GNOME / Document Scanner · GitLab](https://gitlab.gnome.org/GNOME/simple-scan) (Best tool for manual duplex scanning imo)
- qpdf-cli
- scanimage (cli based scanning)

Not recommended
- [hellerbarde/stapler: A small utility making use of the pypdf library to provide a (somewhat) lighter alternative to pdftk](https://github.com/hellerbarde/stapler) (Command line only, based on PyPDF2)

I just wanted to collect and share those. Especially paperwork is quite impressive and a great tool for a "paperless (home-) office". Make sure you use the latest version (2.x)!

Maybe we could put this list in the Readme or a wiki page to guide users to the best program for their task.

**Comment by jeromerobert** [comment]
I think it's better to have this in the wiki. I would also prefer to do not mention "not recommended" tools.

**Comment by dreua** [comment]
> I think it's better to have this in the wiki. I would also prefer to do not mention "not recommended" tools.

Why? For not increasing their Google ranking or not pissing people off or something else?

**Comment by dreua** [comment]
Added to wiki https://github.com/pdfarranger/pdfarranger/wiki/Other-PDF,-Paging-or-Scanning-tools
I just listed pdf-stapler as "other" which is not as harsh as "not recommended" and added my opinion below. Would that be okay with you? (Feel free to edit to your liking.)
