### ISSUE TITLE
error: pikepdf.copy_foreign called with direct object handle

### ISSUE THREAD

**Issue by davebritton** [pdfarranger/pdfarranger#484]
Trying to combine a batch of pdf files I received a warning "forms and outlines are lost on saving." I did not click the box "Do not show this dialog again." Then I clicked "OK" and received the error message "pikepdf.copy_foreign called with direct object handle." I clicked OK. The program did not crash, but it did not save the file.

**Comment by davebritton** [comment]
@davebritton
pdfarranger /
pdfarranger


Describe the bug
----------------

A clear and concise description of what the bug is.

The program fails when combining multiple files under some unknown condition.

Trying to combine a batch of pdf files I received a warning "forms and outlines are lost on saving." I did not click the box "Do not show this dialog again." Then I clicked "OK" and received the error message "pikepdf.copy_foreign called with direct object handle." I clicked OK. The program did not crash, but it did not save the file.

To Reproduce
------------

Steps to reproduce the behavior:
1.  Go to + add file attached example pdf
2.  Click on 'Save as [test.pdf or any name]
3.  Scroll down to '....'
4.  See error" "forms and outlines are lost on saving."
5. See dialog box, Click "OK"
6. The file has not been saved

Expected behavior
-----------------

A clear and concise description of what you expected to happen.
A pdf file of the specified name should be saved.

Input files
-----------
See attached PDF.
The bug does not appear on some files
Check if the bug appear only with some PDF or image files. If the bug is specific to some files please attach one to the issue.


System and Versions
-------------------

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)
-  UBUNTU 20.04 distro version, then checked again by compiling from scratch per instructions 
-   pikepdf version and where you get it (distro package, pip, git, ...)
- Ubuntu 20.04 distro
-   OS name and version (e.g.: Windows 10, Fedora 33, ...)
- Ubuntu 20.04

    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

**Comment by davebritton** [comment]
On another computer with an older version of Ubuntu, 18.4, I have an older version of pdfshuffler 0.6.0 obtained from the Ubuntu distribution, that still works to save the attached example file.

**Comment by jeromerobert** [comment]
How did you install pikepdf 2.12.0 ? (Ubuntu only provide packages for 1.10 et 1.17)
