### ISSUE TITLE
Abnormally slow when there are too many pages

### ISSUE THREAD

**Issue by TUTUtu234** [pdfarranger/pdfarranger#492]
First of all, thank you for your work, but I found a little problem when using the software.
When the number of PDF pages is too large (about 1000 pages), we have to wait for a long time(**about several minutes**) for each addition. Is there a full scan for each addition? If so, could you consider optimizing it?
Thank you very much.

1.  Use the Add button in the upper left corner to add my first PDF , it is about 600+ pages
2.  add any other PDF file, it will take a long time to append the pages to the end, I don't think it needs to be that long at all.

System and Versions
Windows 10
i5 8400 
16GB RAM

**Comment by dreua** [comment]
For completeness sake: which version of PDF arranger are you running? We might have some unreleased improvements in the main branch, not sure though.

**Comment by kbengs** [comment]
Yes that is improved in main. If you like to test main you should be able to download the latest build here:
https://github.com/pdfarranger/pdfarranger/actions/runs/842421945
You need to be logged in to be able to download.

**Comment by TUTUtu234** [comment]
> For completeness sake: which version of PDF arranger are you running? We might have some unreleased improvements in the main branch, not sure though.

The version is 1.7.1, I download it because it's the latest release I've seen.

**Comment by TUTUtu234** [comment]
> Yes that is improved in main. If you like to test main you should be able to download the latest build here:
> https://github.com/pdfarranger/pdfarranger/actions/runs/842421945
> You need to be logged in to be able to download.

Thank you for your reply, but I am a little busy these days. I will test it the next time. Anyway, thank you for your work.
