### ISSUE TITLE
Impossible to save a modified PDF

### ISSUE THREAD

**Issue by xbesnard** [pdfarranger/pdfarranger#494]
Hi.
I report an incorrect behavior of pdfarranger.

I would like to keep only the first page of a PDF file using pdfarranger.
After removing the pages 2 to 8, I try to record the remaining page 1. 
I got an error message, without being in position to save my first page.
This behavior is always reproductible.
I provide enclosed:
 * The message box with the error message,
 * The properties of the pdf file.
I remain available for any further information. Thanks. Xavier
![2](https://user-images.githubusercontent.com/35624286/119839740-af7e5a80-bf04-11eb-86c0-78f776568477.png)
![1](https://user-images.githubusercontent.com/35624286/119839742-b0af8780-bf04-11eb-8717-045826fc08af.png)

**Comment by dreua** [comment]
This is clearly a bug report, please follow [the template](https://github.com/pdfarranger/pdfarranger/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Comment by dreua** [comment]
Probably duplicate of #478

**Comment by dreua** [comment]
Second try at #495
