### ISSUE TITLE
Scroll area gets too big if pages have different dimensions

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#505]
Describe the bug
----------------
Discovered trying to reproduce #501 

To Reproduce
------------

1.  Create / load a PDF with different page dimensions 
2. copy/paste to get a few pages so that scrollbar appears
3.  Scroll down to the end
4.  See unneccessary blank space

Expected behavior
-----------------

Scroll area should fit the PDF pages snugly.

System and Versions
-------------------

-   PDF Arranger 1.7.1

**Comment by Scafir** [comment]
Precision: I can only trigger this bug when the pdf is rendered with two columns or less.
