### ISSUE TITLE
Default directory in file chooser

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#508]
When a document is imported with the file chooser dialog, the path is stored. The next time you open the file chooser, you start in the very same directory.

**Question 1:** The path is stored on a per window basis. When you open a new window (ctrl + n), the path is reset to the default. Should the new window be treated in the same way as a freshly launched instance?

**Question 2:** The default directory is the home directory. Should PDF Arranger default to a path one level deeper into the file tree? On my system, evince defaults to _Documents_, gimp to _recently used_, shutter to _Pictures_. An alternative is a customisation option to set the default path similar to the keyboard shortcuts.

**Comment by dreua** [comment]
I'd be okay with a globally saved "last used path" which is always used. Would fit my use case best. But then again I mostly use drag and drop.
