### ISSUE TITLE
Distribution through winget (Windows Package Manager) 

### ISSUE THREAD

**Issue by alanlivio** [pdfarranger/pdfarranger#509]
Like choco, It may be interest pdfarranger support be installed by the new [Windows Package manager](https://github.com/microsoft/winget-cli)

**Comment by dreua** [comment]
What exactly cis the issue here? Who should do what?

**Comment by jeromerobert** [comment]
This is about doing a PR at https://github.com/microsoft/winget-pkgs. I don't think any of the PDF Arranger team will want to work on that. You could report this issue at winget-pkgs but they are already overwhelmed by new package requests. IMHO your best chance is to do the PR yourself.

**Comment by dreua** [comment]
Wow is Windows finally getting some kind of package manager? But on the other hand it looks more like Microsoft is building its own chocolatey... Anyway, the Teams is probably not going to work on it, but I'll help where I can. @alanlivio or any interested Windows users: please go ahead and submit this, feel free to tag me!

Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.

**Comment by dreua** [comment]
Someone seems to have taken care of that:
- https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/PDFArranger/PDFArranger
- https://winget.run/pkg/PDFArranger/PDFArranger

Should we add a link to the wiki page? Is winget-pkgs considered trustworthy similar to Linux distributions or is it more like an AUR/Copr where people can publish almost anything?

**Comment by jeromerobert** [comment]
We already have a link thanks to Repology.
