### ISSUE TITLE
Option to zoom to full page

### ISSUE THREAD

**Issue by madduck** [pdfarranger/pdfarranger#51]
Upon starting the programme, it would be nice if I had the option to make it zoom so as to display as much as possible of the first page, not just thumbnails.

**Comment by jeromerobert** [comment]
I won't work on that issue. I think that now that the zoom level is saved, it's not that useful. Anyway I leave the bug open in case that someone want to do it.

**Comment by Nokia808** [comment]
@jeromerobert 
Hi.
This issue is related to this closed issue https://github.com/jeromerobert/pdfarranger/issues/235
I will post a comment about this in issue https://github.com/jeromerobert/pdfarranger/issues/235 kindly, to see it.

**Comment by kbengs** [comment]
Evince use key f to zoom to full page, maybe we could use it also..

**Comment by kbengs** [comment]
I have now made something that zooms into full page and scrolls to the page when double-clicking on a page.
When double-clicking again it zooms back to set zoom level. 
Key f zooms to the page where cursor is. Pressing key f again zooms back to set zoom level. 

Does anybody argue against this behavior?

**Comment by jeromerobert** [comment]
Done in 613350f8b9027ab8963e23a5dd40f8bd25ac0b86. Thank you @kbengs .
