### ISSUE TITLE
Horizontal scrollbar appears when not necessary

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#512]
Describe the bug
----------------

Certain views make the horizontal scrollbar appear even when the entire page width is visible. A page can clip through the horizontal scrollbar.

To Reproduce
------------

1.  Load a page and adjust view so that the entire page is visible.
2.  Adjust window geometry: Shrink the height such that the bottom part of the page is cut off. Keep the width unchanged.

Expected behavior
-----------------
The horizontal scrollbar is not needed since no content is clipped. If the scrollbar is needed, the page should not cut through the horizontal scrollbar.

![image](https://user-images.githubusercontent.com/17718454/126867046-482f60d8-ca0d-4366-9e3f-ee6a43fd791c.png)

**Comment by angsch** [comment]
Thanks for checking, @kbengs. The scrollbar reliably appears on Xubuntu. I tried a VM with Ubuntu and there I cannot reproduce the problem. It's an odd one, I have not seen the scrollbar issue in any other software on Xubuntu. I will checkout earlier versions of PDF arranger tomorrow and see if the problem has always been present. In any case, if it is just a cosmetic problem on a single OS, I am happy to close the issue.

**Comment by jbergengh** [comment]
I have this issue on every PDF I load.  Running Linux Mint 20.2, PDF Arranger 1.7.1 flatpack installed from the Mint software manager.  It comes and goes when resizing the window.  The PDF pages overwrite the horizontal scroll bar, then pieces stay on the scrollbar when scrolling the PDF up and down.  The horizontal scrollbar is always visible even though I see no need for it regardless of window size or position.  The scrollbar itself is always the full width of the window so it doesn't function anyway.  Maybe removing the horizontal scrollbar is the solutio
![untitled  Dell inspiron-15-5559-laptop_reference guide_en-us  – PDF Arranger_001](https://user-images.githubusercontent.com/55407804/140002376-17abae3b-6d78-415d-b2db-cbba98fabfb7.png)
nl

**Comment by kbengs** [comment]
Could you test if this fixes the issue...? I did a test with Mint but could not reproduce it.
```
--- a/pdfarranger/pdfarranger.py
+++ b/pdfarranger/pdfarranger.py
@@ -804,6 +804,20 @@ class PdfArranger(Gtk.Application):
         if self.iconview.get_visible():
             self.update_iconview_geometry()
 
+        self.hide_horizontal_scrollbar()
+
+    def hide_horizontal_scrollbar(self):
+        """Hide horizontal scrollbar when not needed."""
+        sw_width = self.sw.get_allocated_width()
+        iv_width =  self.iconview.get_allocated_width()
+        hscrollbar = self.sw.get_hscrollbar()
+        if iv_width <= sw_width:
+            hscrollbar.hide()
+        else:
+            hscrollbar.show()
+
+        print(iv_width, sw_width, hscrollbar.get_visible())
```

**Comment by kbengs** [comment]
I can reproduce it in Mate but not in Chinnamon. The above fix works.

**Comment by jbergengh** [comment]
This is interesting.  I booted Mint 20 Cinnamon off a live USB stuck, installed 1.7.1 flatpack, and could not reproduce the issue.  Maybe something is broken in my current  Mint install.  Now I'm thinking of reinstalling Mint  because I use pdf arranger extensively and it would be worth it.
Before I do that, I'd like to try your patch.  Unfortunately I'm not a programmer and I don't know to apply the fix.  Can you help me with that?

**Comment by kbengs** [comment]
I'm not sure it's worth to test the patch. It's not fixing the real problem, only work around it. I hope a better way to do it is found. But if you want to test it you can follow the "Install from source" and "For developers" instructions on main page. Then in pdfarranger.py you would add the lines starting with +. I updated the code a bit.

It was a fresh install i tested that on. The issue has to do with the scrollbars. In Chinamon they are put on top of the iconview. In Mate they are put on the side, taking space from iconview.

**Comment by jbergengh** [comment]
Thanks kbengs,
I did as you said.  I installed from source and made the fixes as you described above.
The fix works perfectly!
The horizontal scrollbar is hidden when it is not needed.  The scrollbar appears when zooming in on a single PDF page just as it should.

**Comment by kbengs** [comment]
This should be better. @jbergengh Would you like to test this instead? (- lines need to be removed)
```
@@ -525,6 +525,7 @@ class PdfArranger(Gtk.Application):
         self.iconview.connect('key_press_event', self.iv_key_press_event)
 
         self.sw.add_with_viewport(self.iconview)
+        self.viewport = self.iconview.get_parent()
 
         self.model.connect('row-inserted', self.__update_num_pages)
         self.model.connect('row-deleted', self.__update_num_pages)
@@ -541,7 +542,7 @@ class PdfArranger(Gtk.Application):
         vscrollbar.connect('value_changed', self.vscrollbar_value_changed)
 
         # Define window callback function and show window
-        self.window.connect('check_resize', self.on_window_size_request)
+        self.window.connect_after('check_resize', self.on_window_size_request)
         self.window.show_all()
 
         # Change iconview color background
@@ -821,13 +822,13 @@ class PdfArranger(Gtk.Application):
             padded_cell_width = cell_width + 2 * item_padding
             min_col_spacing = 5
             min_margin = 11
-            iw_width = self.sw.get_allocation().width
+            vp_width = self.viewport.get_allocated_width()
             # 2 * min_margin + col_num * padded_cell_width
-            #  + min_col_spacing * (col_num+1) = iw_width
-            col_num = (iw_width - 2 * min_margin - min_col_spacing) //\
+            #  + min_col_spacing * (col_num+1) = vp_width
+            col_num = (vp_width - 2 * min_margin - min_col_spacing) //\
                       (padded_cell_width + min_col_spacing)
-            spacing = (iw_width - col_num * padded_cell_width - 2 * min_margin) // (col_num + 1)
-            margin = (iw_width - col_num * (padded_cell_width + spacing) + spacing) // 2
+            spacing = (vp_width - col_num * padded_cell_width - 2 * min_margin) // (col_num + 1)
+            margin = (vp_width - col_num * (padded_cell_width + spacing) + spacing) // 2
             if col_num == 0:
                 col_num = 1
                 margin = 6
```

**Comment by jbergengh** [comment]
I made the changes above and the horizontal scroll bar appears to be working as it should.  I don't see any difference between these last changes and the ones before.
Oddly, I'm getting some screen glitches when resizing the window.  I haven't noticed this in any other programs.  Not sure if it's related.
Here is a video (I hope I can upload video here).  It's a side-by-side comparison.  The one on the left was downloaded from source and installed  via pip3 install.  The one on the right has your latest changes shown above in the pdfarranger.py file which is being executed via python3 -m pdfarranger.  If you look closely at the two you can observe the horizontal scrollbar behavior as well as the odd screen glitches.

https://user-images.githubusercontent.com/55407804/140407530-49280420-feaa-4368-ac17-aa3a2b494992.mp4

**Comment by kbengs** [comment]
Thanks for testing and thanks for video. I have never seen the glitches before. But if it went away after a reboot maybe it's fine. Another thing I notice in Mate (and in the video) is that iconview flashes visible while you resize window. It is supposed to be hidden until you stop resizing window. I'll see if I find a fix for that too.

**Comment by jbergengh** [comment]
@kbengs, just a note of thanks for fixing this.  Everything is working flawlessly here and I am very, very happy.  I did have to reinstall Mint to get rid of the screen glitches in the video above.  I must have broken something along the line, but whatever it was is completely gone now.  Thanks again. I use PDF Arranger every day so I really appreciate the work you and everyone else associated with this project does.
