### ISSUE TITLE
[Question] Test file invalid?

### ISSUE THREAD

**Issue by mara004** [pdfarranger/pdfarranger#516]
This may be a strange issue, but I would like to enquire about your test file [test.pdf](https://github.com/pdfarranger/pdfarranger/blob/main/tests/test.pdf).
For a bit of background, I am developing a small application and did some tests with all PDFs in my home directory to ensure correct functionality. This also included the pdfarranger test file. I noticed several peculiarities that make me wonder whether the document in question might be invalid:
- None of the PDF boxes are defined, not even `/MediaBox`. I had never seen this before. Okular PDF reader falls back to ANSI A.
- The (Py)MuPDF library reports errors when opening the document (`mupdf: cannot find startxref`), as well as the Poppler library (`org.kde.okular.generators.pdf: [Poppler] "Error: No valid XRef size in trailer"`)

The file seems rather suspicious to me. May I ask which application and PDF writer library was used to create it? The XMP and docinfo metadata don't tell.

Thanks for your support.

**Comment by jeromerobert** [comment]
I wrote it from scratch using vim. Indeed, it's not valid. It's just very small and readable by pikepdf and poppler, which is what we need for tests.

**Comment by mara004** [comment]
Okay, thanks for the clarification. However, I am a bit doubtful whether it is a godd idea to use an invalid document for tests...
