### ISSUE TITLE
Error on pdf export "only pages can be inserted" on Ubuntu with Pdf Arranger 1.6.2

### ISSUE THREAD

**Issue by Valeryan24** [pdfarranger/pdfarranger#518]
Hi,

First thanks a lot for your amazing work on Pdf Arranger.

Since a few weeks, on Ubuntu 21.10 beta, I can't use it anymore : when I want to combine multiple pdf or export some pages from a document, after the Save dialog, I get an error message "only pages can be inserted" and nothing is saved.

There are normal pdf, nothing password protected, even with files printed to pdf directly from Ubuntu it doesn't work anymore. No problem on Windows.

It's still the version 1.6.2, I hoped Debian / Ubuntu would update it, I don't know if it's a known issue already corrected in 1.7 branch…

**Comment by jeromerobert** [comment]
https://github.com/pdfarranger/pdfarranger/issues?q=only+pages+can+be+inserted
