### ISSUE TITLE
Make Android version of this app/Port this app to Android

### ISSUE THREAD

**Issue by pronoymukherjeewritescode** [pdfarranger/pdfarranger#519]
Can you make a Android port for this app? (Port this cool app to Android)

**Comment by jeromerobert** [comment]
GTK do not run on Android, so no that's not possible.

**Comment by pronoymukherjeewritescode** [comment]
A python version

**Comment by dreua** [comment]
> A python version

What do you mean?

**Comment by jeromerobert** [comment]
You need DistUtilsExtra. It can be found herer: https://launchpad.net/python-distutils-extra

**Comment by jeromerobert** [comment]
See https://github.com/pdfarranger/pdfarranger#install-from-source for the list of all dependencies you'll have to install manually (i.e. which cannot be installed with pip)

**Comment by dreua** [comment]
@pronoymukherjeewritescode editing is for fixing small errors or, in rare cases, adding bits of information. Please do not change the whole issue because it is confusing for everyone and makes our answers worthless.
