### ISSUE TITLE
Appimage release?

### ISSUE THREAD

**Issue by PaulCombal** [pdfarranger/pdfarranger#521]
Hi,
Thank you for your work. Do you plan on releasing an Appimage binary of PDF Arranger? I think that would be awesome.
Thank you

**Comment by dreua** [comment]
No, there are no such plans. We already have Flatpak, pip and various distro packages.

**Comment by dreua** [comment]
https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html

Maybe it's not that hard, but I'm not sure whether I'll find the time for it anyway. Let us know if you want to work in a PR.

**Comment by mara004** [comment]
I wouldn't consider an AppImage so useful for pdfarranger. The AppImage format is primarily inteded for programs that are written in a compilable language like C++, but as Python is a scripting lanuage, it's really easy to [run pdfarranger from source](https://github.com/pdfarranger/pdfarranger#install-from-source).
Moreover, AppImages are (almost) self-contained, which means the binary you download has to bundle all dependencies and will thus be unnecessarily large.

**Comment by dreua** [comment]
Thanks for the input @mara004 , this sounds like it's not really worth the hassle to me. I'm assuming that no one is interested in working on this, but anyway:

Let's give this issue 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.
