### ISSUE TITLE
1.8.0 almost ready, please test !

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#525]
I think we fixed some stuff and added some features, it might be time for PDF Arranger 1.8, what do you (@pdfarranger) think?

**Comment by jeromerobert** [comment]
Yes, the time has come.

**Comment by angsch** [comment]
In late September/early October I will have time to resume working on tiling (#440), which should remove a good bunch of the current limitations of the booklet. Do you want this to go into 1.8?

**Comment by jeromerobert** [comment]
Well we have no dead line so we can wait until the end of october.

**Comment by vvillenave** [comment]
Hi guys,  
just for accessibility’s sake, could a 1.7.2 come out before that?  
I know a bunch of users who could really use it! :-)

**Comment by jeromerobert** [comment]
@smarquespt, @Vistaus, @milotype, @volkov0aa, @sicklylife-jp, @ovari, @MichelePezza, @emintufan, @albanobattistella, @hahnavi, @juanma1980, @juxuanu, @sveinki, @Ser82-png, @hugok79

Dear PDF-Arranger translators, the version 1.8.0 is almost ready. This time there are few changes on the UI side. If you want to update your translations, this is the right time as the sources will be quite stable during the next 2-3 weeks. The POT file is up to date. Thank you !

PS: I have notified everyone who has contributed at least once to the translation of PDF Arranger. If you don't want to be notified anymore for this, tell me so I can remove you from my list.

**Comment by jeromerobert** [comment]
Releases notes drafted

**Comment by juxuanu** [comment]
About translations: what's a "Booklet" and what does that refer to inside the app?

**Comment by jeromerobert** [comment]
> About translations: what's a "Booklet" and what does that refer to inside the app?

When printing, you may want that the first sheet contains the first and last pages, the second sheet contains the page 2 and n-1 and so on. So you can staple sheets in the middle to make a book.

**Comment by hugok79** [comment]
@jeromerobert @smarquespt 
Portuguese(Portugal) translation updated
https://github.com/pdfarranger/pdfarranger/pull/562

**Comment by ovari** [comment]
@jeromerobert can you please add all the source strings with blank translations to the hu.po file? Translations can then be added using the web browser. Thank you

**Comment by sveinki** [comment]
@ovari If you have the gettext-packages installed, you can download the new POT-file and issue this command:
`msgmerge -U pdfarranger-hu.po pdfarranger.pot` (this updates a file named pdfarranger-hu.po with current translation strings).
Having the PO-file on your computer permits using translation editors (PoEdit, Lokalize), filling your own translation memory, and using plenty of handy tools (spellcheck, diff, etc.).
In some projects I participate, it's the maintainers who run a script to update the PO-files when the POT-file changes, but in some other projects the consensus is that only translators should touch translation files.

**Comment by jeromerobert** [comment]
@ovari Done

**Comment by smarquespt** [comment]
@jeromerobert how can I test in windows? Is there any portable RC?

**Comment by jeromerobert** [comment]
@smarquespt They can be found in the [Github Actions tab](https://github.com/pdfarranger/pdfarranger/actions/).
Click the [latest `main` commit](https://github.com/pdfarranger/pdfarranger/actions/runs/1413272257) (or [your PR](https://github.com/pdfarranger/pdfarranger/actions/runs/1416798083)) and see [`pdfarranger-windows-portable-zip`](https://github.com/pdfarranger/pdfarranger/suites/4234597203/artifacts/109669420) at the bottom. Thank you !

**Comment by smarquespt** [comment]
> @smarquespt They can be found in the [Github Actions tab](https://github.com/pdfarranger/pdfarranger/actions/). Click the [latest `main` commit](https://github.com/pdfarranger/pdfarranger/actions/runs/1413272257) (or [your PR](https://github.com/pdfarranger/pdfarranger/actions/runs/1416798083)) and see [`pdfarranger-windows-portable-zip`](https://github.com/pdfarranger/pdfarranger/suites/4234597203/artifacts/109669420) at the bottom. Thank you !

Got it. Thanks

**Comment by jeromerobert** [comment]
Release this WE or the WE after.

**Comment by jeromerobert** [comment]
Done. I hope I didn't make a mistake. Let's reserve the end of the year for a possible 1.8.1.
