### ISSUE TITLE
[Wayland only] Copying/pasting pages does not work

### ISSUE THREAD

**Issue by mara004** [pdfarranger/pdfarranger#529]
Description
----------------

I cannot get the "Paste as odd/even" feature to work. When I cut pages and do "Paste as even pages" or "Paste as odd pages", it simply takes no effect - no pages are pasted.

To Reproduce
------------

1.  Import one or more documents
2.  Mark a group of pages
3.  Cut the pages (<kbd>Ctrl</kbd>+<kbd>X</kbd>)
4.  Focus a page, open the context menu and do `Paste Special` -> `Paste As Odd Pages` (or `Paste As Even Pages `)

Unfortunately there is no logging output to see what happens internally.

Expected behavior
-----------------

Pages should be pasted alternatingly, so that every other page is from the cut pages of the clipboard.

Input files
-----------

I used the standard PDFStitcher [test file](https://github.com/cfcurtis/pdfstitcher/raw/main/resources/testdoc.pdf), but the issue can be reproduced with any other PDF or images.

System and Versions
-------------------

-   Current PDF Arranger from git main (7e27da2), invoked with `python3 -m pdfarranger`
-   pikepdf 3.0.0 from pip (though I also experienced the issue with pikepdf 2)
-   KDE Neon User (based on Ubuntu Focal 20.04) with Plasma Wayland

This issue is a follow-up to #526, as suggested by @kbengs and @dreua (https://github.com/pdfarranger/pdfarranger/issues/526#issuecomment-914484849).
I think @camlafit is affected too, maybe they can provide additional information.

**Comment by jeromerobert** [comment]
I cannot reproduce it. My pikepdf version is 1.17.3 but pikepdf is not used at all here. 

The code reponsible for this feature is:
https://github.com/pdfarranger/pdfarranger/blob/7e27da2/pdfarranger/pdfarranger.py#L1229-L1256
https://github.com/pdfarranger/pdfarranger/blob/7e27da2/pdfarranger/pdfarranger.py#L1156-L1181

Could you try to add some `print()` here to find what's going on. I would start by printing `data` in `paste_pages_interleave`.

**Comment by mara004** [comment]
I added the prints as you suggested, but there was no output. Seems like that code isn't even called for me.

**Comment by mara004** [comment]
Ah, I found something out now: `data` is `None`. so it instantly returns.
I just had the prints put below where it had already returned.

**Comment by mara004** [comment]
Yep it's a Wayland exclusive issue. I just ran `GDK_BACKEND=xdg python3 -m pdfarranger` and there it works.

**Comment by jeromerobert** [comment]
https://gitlab.gnome.org/GNOME/gtk/-/issues/1874 :-(

**Comment by jeromerobert** [comment]
I would expect all clipboard based feature to be broken, not only paste as odd/even.

**Comment by mara004** [comment]
> I would expect all clipboard based feature to be broken, not only paste as odd/even.

Yeah, paste odd/even was just the only one I tried.
So we can only wait until the issue is addressed upstream, and recommend Wayland users to run pdfarranger as an XWayland instance for a workaround.

**Comment by mara004** [comment]
@camlafit Are you using Wayland, too?

**Comment by dreua** [comment]
Every now and then I give Wayland a try, a few days later stuff like this start biting me, I report a bug and go back to X11. I'm tempted to say it's not ready for production, but I probably shouldn't do that.

@mara004 just to make sure I get this right: Copy/Paste does not work at all, not even adding a PDF file from the file system (e.g. copy from nautilus)?
Could you try other Python+Gtk applications e.g. Meld or Zim whether their clipboards work on wayland?

**Comment by camlafit** [comment]
Hello

@mara004  I confirm this behavior. I use debian 11 with wayland and gnome-shell. 

Move from nautilus to pdfarranger work but not copy/paste. To note copy/paste in nautilus works.
copy/pate text from gedit to meld works (and vice versa also)

**Comment by mara004** [comment]
> Every now and then I give Wayland a try, a few days later stuff like this start biting me, I report a bug and go back to
> X11. I'm tempted to say it's not ready for production, but I probably shouldn't do that.

Plasma Wayland itself is quite stable, and I actually prefer it over Plasma X11 because there's no flickering. Qt also seems to be a bit ahead of GTK in terms of Wayland compatibility. However, there are indeed a lot of issues with specific apps that probably need to be fixed on a case-by-case basis. For me, the best solution currently is to use the Wayland session and resort to XWayland with apps that have issues.

> just to make sure I get this right: Copy/Paste does not work at all, not even adding a PDF file from the file system 
> (e.g. copy from nautilus)?
> Could you try other Python+Gtk applications e.g. Meld or Zim whether their clipboards work on wayland?

I can confirm the observations made by @camlafit:
* Internal copy/paste in PDF Arranger does not work
* Dragging and dropping a file from Dolphin does work, though
* In Meld, copying/pasting text works correctly (system clipboard interaction)

**Comment by mara004** [comment]
By the way: When running pdfarranger from source with `python3 -m pdfarranger` on Wayland, the icon is missing. On XWayland/X11 the icon appears correctly, though. Should I open a separate bug report about this?

**Comment by jeromerobert** [comment]
> Should I open a separate bug report about this?

No. There are many things that do not work properly when pdfarranger is not installed with pip (translations, command line help, ...). I do not concider that as bugs, just something that developers should keep in mind.

**Comment by mara004** [comment]
Ok, thanks you for clarifying this. I just asked because the KDE guys usually want separate bug reports for everything :)
Command-line help works for me, though. Why do translations not work when not installed? For pdfstitcher they do, and I think pdfarranger also uses gettext, right?

**Comment by mara004** [comment]
Ok, thanks you for clarifying this. I just asked because the KDE guys usually want separate bug reports for everything :)
Command-line help works for me, though.

**Comment by kbengs** [comment]
It looks like wayland don't support "arbitrary named clipboards"
https://bugzilla.gnome.org/show_bug.cgi?id=770333

So _SELECTION_PDFARRANGER does not work. Normal clipboard works. So it would be possible to fix this issue by using normal clipboard (same way as Windows does). I guess we should do that.
