### ISSUE TITLE
default pdf version?

### ISSUE THREAD

**Issue by xpseudonym** [pdfarranger/pdfarranger#539]
Is it possible to set the PDF output version?  Or, is there a config file anywhere - I've installed from Flathub
Thanks all.

**Comment by dreua** [comment]
No, not that I'm aware of.

**Comment by jeromerobert** [comment]
It's currently not possible but QPDF support it. See `--force-version` at https://qpdf.sourceforge.io/files/qpdf-manual.html#ref.advanced-transformation.

@xpseudonym What is your intent ? Why do you want to change the default PDF version ?

**Comment by xpseudonym** [comment]
Thanks @jeromerobert - to restore a file to its original condition

**Comment by mara004** [comment]
`pikepdf.Pdf.save(..., min_version=...)` should be possible. Would probably not be difficult to add.

**Comment by xpseudonym** [comment]
Thanks @mara004 
Morgan
