### ISSUE TITLE
Page gets resized instead of cropped

### ISSUE THREAD

**Issue by Amarok19** [pdfarranger/pdfarranger#550]
Describe the bug
----------------

When attempting to crop a page, it gets resized instead.

To Reproduce
------------

1.  Open a PDF file
2.  Select a page
3.  Open the "Page Format" dialog
4.  Set one of the text fields for cropping to some value, e.g. 60
5. Confirm, exiting the dialog.

Expected behavior
-----------------

The page gets cropped by specified amount.

Actual behavior
---------------

Page appears to be small - it is resized or the view is zoomed out, but likely the former. It is not cropped.

Input files
---------

[test.pdf](https://github.com/pdfarranger/pdfarranger/files/7388980/test.pdf) attached.

Screenshots
-----------

I can provide a video if needed.

System and Versions
-------------------

-   pdfarranger 1.7.1 (.msi package)
-   pikepdf version - not sure, but whatever is packaged with above ^
-   OS = Windows 10

Additional info
--------------

I also noticed that I cannot resize the page - when attempting to change the value in the text field for scale factor, it gets reset to 0 at first opportunity. Pressing The "+" button next to this field does nothing.

**Comment by Amarok19** [comment]
For the record - I just got a reproduction of this error and both "log" files only contain `stdout test` and `stderr test` lines, respectively. No more error messages logged.

**Comment by kbengs** [comment]
If you want to dig more into this you can:
1. copy `croputils.py`  into `C:\Users\USER\AppData\Local\Programs\pdfarranger\lib\pdfarranger`
2. add `print('s', s)` to line 68 in `croputils.py` (so that is prints the result of `s = locale.format_string("%.8g", self.get_adjustment().get_value())`)
3. try to reproduce the issue. 
4. Close application and see what is in `pdfarranger_stdout.txt`

**Comment by Amarok19** [comment]
Hmmm...
`stdout test
s 0
s 0
s 0
s 0
s 0
s 0
s 0
s 0`

**Comment by kbengs** [comment]
I think locale.format fails and therefore it try to set scale factor to 0%

Here would be some more ideas.

```
@@ -54,6 +54,7 @@ class _LinkedSpinButton(Gtk.SpinButton):
 
     def __init__(self, minval, maxval, step, page=None):
         Gtk.SpinButton.__init__(self)
+        self.set_numeric(True)  # 1
         self.set_digits(20)
         self.set_width_chars(9)
         self.connect("output", self.__output)
@@ -63,7 +64,11 @@ class _LinkedSpinButton(Gtk.SpinButton):
 
     def __output(self, _user_data):
         """ output signal handler to remove unneeded 0 """
-        s = locale.format("%.8g", self.get_adjustment().get_value())
+        s = locale.format_string("%.8g", self.get_adjustment().get_value())  # 2
+        print('a', self.get_adjustment().get_value())  # 4
+        print('s', s, len(s))
+        print(locale.getlocale())
+        print('')
         self.get_buffer().set_text(s, len(s))
         return True
```
Does this fix the problem? If not you could also try to comment out the self.connect line

**Comment by dreua** [comment]
> I also noticed that I cannot resize the page - when attempting to change the value in the text field for scale factor, it gets reset to 0 at first opportunity. Pressing The "+" button next to this field does nothing.

Does this mean the scale factor is pre-filled with 0 and you can't change it? Then that's our bug. If I manually set the field to 0 my results match yours. The field should be pre-filled with 100 and adjustable between 0.5 and 20000.
Can you toggle the radio button to width / height? Does it change the behavior of the input field?

**Comment by Amarok19** [comment]
I'll have to allocate some time to this and sit down to really gather some more particular info. I think this bug deserves a reopen. One thing I noticed about this is that it seems to occur only if I open a PDF from the "Open with..." option in Windows 10 context menu in its file manager. It seems to work fine when opening the app first and then using the built-in file opening dialog.

I'll check the code snippet from @kbengs and try to find an answer to questions asked by @dreua when I have some time to look at this properly.

**Comment by Amarok19** [comment]
Hm, interesting. This time again only opening the PDF through the "Open with..." path causes problems (by which I mean that when running the program itself, it runs fine), but this time it's not cropping that works weird - it's this error:
![image](https://user-images.githubusercontent.com/9848795/147712082-2be5faa2-4d42-4964-bc65-54d78061d32d.png)

**Comment by ksetlak** [comment]
Tried on a different Windows machine and got this:
[pdfarranger_stderr.txt](https://github.com/pdfarranger/pdfarranger/files/7795866/pdfarranger_stderr.txt)

**Comment by Amarok19** [comment]
Tried on a different Windows machine and got this:
[pdfarranger_stderr.txt](https://github.com/pdfarranger/pdfarranger/files/7795873/pdfarranger_stderr.txt)

**Comment by jeromerobert** [comment]
For the *Open With* issue, qpdf cannot be loaded. 
- you mixed multiple version of PdfArranger with incompatible libraries
- OR an other program (not related to PdfArranger) installed some mingw64 dll to c:\windows\system32 and they are conflicting with the one packaged with PDF Arranger
- OR an other program (not related to PdfArranger) added it's library folder to the global %PATH% environment variable.
Note that those 3 reasons are quite similar. You can try to play with *Dependency Walker* to find why qpdf cannot be loaded.

For the *pdfarranger_stderr.txt* issue:
* You are using a old `pdfarranger.py` with a new `pdfarranger.ui`. `self.progress_bar` has been removed in  06e037715408946c34ce2db3574564db26cf88ae (after 1.7.1 and before 1.8.0). You can check that your `pdfarranger.ui` does not contains any `progressbar`. Did you manually mixed 2 versions of PDF Arranger ?
* Following issues are have the same root cause: a old `pdfarranger.py` not compatible with other PDF Arranger files.

**Comment by Amarok19** [comment]
OK, so in first case I messed stuff up. I tried to get pdfarranger run from and IDE so that I can hook it up to a debugger and take a closer look at what is happening inside - trying to figure out what I have to do to make it run in Windows using system environment I made a spaghetti out of my environment, so I think it's best to not pay attention to that case...

Second case: Yup! My bad! Here's stdout after cleaning it up:
[pdfarranger_stdout.txt](https://github.com/pdfarranger/pdfarranger/files/7795961/pdfarranger_stdout.txt)

**Comment by Amarok19** [comment]
For contrast, a log for the exact same actions, but on a PDF opened using the in-app "Open file" dialog:
[pdfarranger_stdout.txt](https://github.com/pdfarranger/pdfarranger/files/7795972/pdfarranger_stdout.txt)

**Comment by jeromerobert** [comment]
Could you:
* Get <https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls>
* Start PDF Arranger with Open with then `listdlls64.exe -u pdfarranger.exe > dllopenwith.txt`
* Start PDF Arranger normally then `listdlls64.exe -u pdfarranger.exe > dllopenfile.txt`
* Find the differences between both (eventually past both here)

**Comment by ksetlak** [comment]
Unfortunately, diff shows that these files are the same...
`InputObject       SideIndicator
-----------       -------------
.\dllopenfile.txt =>
.\dllopenwith.txt <=
[dllopenwith.txt](https://github.com/pdfarranger/pdfarranger/files/7796070/dllopenwith.txt)
[dllopenfile.txt](https://github.com/pdfarranger/pdfarranger/files/7796071/dllopenfile.txt)
`

**Comment by Amarok19** [comment]
Unfortunately, the files are the same:
`InputObject       SideIndicator
-----------       -------------
.\dllopenfile.txt =>
.\dllopenwith.txt <=`
[dllopenwith.txt](https://github.com/pdfarranger/pdfarranger/files/7796073/dllopenwith.txt)
[dllopenfile.txt](https://github.com/pdfarranger/pdfarranger/files/7796074/dllopenfile.txt)

**Comment by jeromerobert** [comment]
> Unfortunately, the files are the same:

No, `libffi-7.dll` is missing in `dllopenwith.txt`, that's suspect. Could you redo the same without the `-u` flag ?

**Comment by Amarok19** [comment]
Sorry for my ultra sluggish response! Here it goes:
[dllopenwith.txt](https://github.com/pdfarranger/pdfarranger/files/7888410/dllopenwith.txt)
[dllopenfile.txt](https://github.com/pdfarranger/pdfarranger/files/7888411/dllopenfile.txt)
Looks like the problem may be caused by pdfarranger using a version of `libffi-7.dll` installed with mitmproxy.

**Comment by Amarok19** [comment]
Uninstalling mitmproxy caused the issue to stop occurring. Is there any elegant way to shield pdfarranger from loading dlls in such a "random" way in certain scenarios?

**Comment by dreua** [comment]
That would be great, a lot of windows issues here seem to be related to loading of the wrong libraries.

**Comment by jeromerobert** [comment]
Well observed !

I just checked that mitmproxy add it's bin directory to the %PATH% global variable. There is nothing reasonable we can do for that. You should be able to make mitmproxy and PDF Arranger work well together by cleaning your environment variables after installing mitmproxy.

If I wanted to mess around I would suggest to add PDF Arranger to the global `%PATH%` and copy it's libraries to `c:\windows\system32` so we would have a chance to break mitmproxy and Tesseract 😈.
