### ISSUE TITLE
file name or Characters not permitted

### ISSUE THREAD

**Issue by visjble** [pdfarranger/pdfarranger#571]
Document gets corrupted, according to staples.com
----------------

I use staples.com for printing pdfs. It seems like when I save a pdf using PDF arranger I am no longer able to upload it to Saples and I get an error (see attached)

To Reproduce
------------

1.  Download sample pdf https://archive.org/details/ritchiesfabulaef00ritc_0/mode/2up
2. Open file in PDF arranger and save as different name
3.  go to https://www.staples.com/services/printing/copies-documents-printing/ and choose 'professional printing' to upload file
RESULT: error, cannot read file name. see attached pic

-Ubuntu 20
- donwloaded your program from the default ubuntu software option
- 
![Screenshot from 2021-11-04 11-38-23](https://user-images.githubusercontent.com/8854071/140401008-5a93cf69-07a2-41bc-9f86-4471a7a31281.png)

**Comment by jbergengh** [comment]
Downloading the sample PDF and then uploading it to Staples, without using PDF Arranger at all, yields the same result for me.

**Comment by dreua** [comment]
> Downloading the sample PDF and then uploading it to Staples, without using PDF Arranger at all, yields the same result for me.

Confirmed.

I don't see how this is related to PDF Arranger, it's either a corrupted source file or a bug in staples.com.
