### ISSUE TITLE
Allow user to set UI language

### ISSUE THREAD

**Issue by midaspt** [pdfarranger/pdfarranger#578]
While running the Windows version of **PDFArranger**, there is no way apparent for an user to change the UI language.

While my Windows is English, my system locale isn't `en-US` because I don't live there...

But **PDFArranger** is picking up the system locale to set the program UI language -- which makes it awkwardly run in a language different from the underlying Windows OS.

An easy way to remedy this could be to make it obey a dedicated key in the "`[preferences]`" section of its '`config.ini`' file, like this:

`language=en`

I am aware of the following workaround for translators, but it doesn't seem suitable for common Windows users.

> You may test different languages with `LANG=xx_YY python3 -m pdfarranger`

**Comment by dreua** [comment]
(Just for reference: I've got a [similar issue filed against Nextcloud](https://github.com/nextcloud/desktop/issues/111) since 2018 - gained a lot of up-votes and "+1"s but that's about it :laughing:)

**Comment by kbengs** [comment]
If you are using windows and want pdfarranger to use english, you can remove the translation folder:
`....pdfarranger\share\locale\fi` (to remove the finnish translation)

**Comment by ovari** [comment]
Can the `User Interface Language` be changed with GNU/Linux operating systems? Thank you

**Comment by kbengs** [comment]
In Linux you should/might be able to start pdfarranger with `LANGUAGE=hu pdfarranger` (for me that will only translate some strings for some reason)
Setting language in config.ini will only work in Windows as it is done now. It is probably possible to make it work in Linux also, but I don't know how.

**Comment by ovari** [comment]
[Xournal++](https://github.com/xournalpp/xournalpp) and [Jami](https://jami.net/) allow for changing the UI language on GNU/Linux with the program's GUI. Perhaps their code repositories can help?

Should another issue be created, like `GNU/Linux Allow user to set UI language`?

Thank you

**Comment by kbengs** [comment]
Yeah, you could open a new issue for that. And add those links. :+1:
