### ISSUE TITLE
Wrong export on "Split pages" and "Duplicate"

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#579]
Describe the bug
----------------

The preview in PDF Arranger is fine, but the export is broken

To Reproduce
------------

1.  Insert empty page / import a PNG / import a PDF
2.  Select a page and "Split pages" with default settings
4.  Save to PDF
5.  Open PDF

Expected behavior
-----------------

Export should match preview

Input files
-----------

Any, even "empty page"

Screenshots
-----------
![Screenshot_20211115_230736](https://user-images.githubusercontent.com/15114715/141860683-78fe368d-427d-48f6-a02a-e4aaef43900c.png)

Exported PDF in Evince:
![Screenshot_20211115_230810](https://user-images.githubusercontent.com/15114715/141860722-3f59db1f-00c6-456b-a276-29efe1e9e873.png)

[test2.pdf](https://github.com/pdfarranger/pdfarranger/files/7541942/test2.pdf)

System and Versions
-------------------

-   PDF Arranger 1.8.0 Flatpak: https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/26
-   pikepdf 4.0.1

**Comment by dreua** [comment]
1. Sorry I don't have time to fix this right now
2. Please test a fix also on a duplicated page to make sure that works, too.

**Comment by jeromerobert** [comment]
I reproduce the issue with pikepdf 3.2.

**Comment by jeromerobert** [comment]
Given a blank page with that mediabox: 0.0, 0.0, 595.275591, 841.889764 ,when splitting then exporting I get (in `_mediabox`):

* Page 1 mediabox before crop: 0.0, 0.0, 595.275591, 841.889764
* Page 1 mediabox after crop: 0.0, 0.0, 297.6377955, 841.889764 (valid)
* Page 2 mediabox before crop: 0.0 0.0 297.637795 841.889764 (*NOT VALID*)
* Page 2 mediabox after crop: 148.8188975, 0.0, 297.637795, 841.889764

It looks like even if we use `copy_foreign` before modifying the mediabox the crop on the first page is also applied on the second page (so the second page get 2 crops). This remind me something, I think we already had this bug.

**Comment by jeromerobert** [comment]
It looks like #141 is back. All action that duplicate pages are broken.

**Comment by jeromerobert** [comment]
Reported to pikepdf: https://github.com/pikepdf/pikepdf/issues/271

**Comment by jeromerobert** [comment]
I can make it work by re-adding the `copy.copy` workaround and use pikepdf 2.7. I cannot find how to make it work with pikepdf 3.2 and 4.0 as `copy.copy` trigger an exception.

**Comment by dreua** [comment]
Many thanks @jeromerobert , this works great. Here is a flatpak build in case someone wants to test even more: https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/27#issuecomment-978018985
