### ISSUE TITLE
Release 1.8.1

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#595]
Hey @pdfarranger team,
I think you fixed some not so tiny bugs (big thank you!) in 1.8.0 and it would be nice to ship a fixed 1.8.1 release. Would you agree or rather wait a little longer?

@jeromerobert would you be so kind to take care of that or would you like someone else to be on release duty?

**Comment by kbengs** [comment]
Would be nice to get more information on #550 and #592 But they can always be fixed later. 1.8.0 has a quite bad bug so I think we should not wait too long.

**Comment by jeromerobert** [comment]
I'll do it on friday.

**Comment by jeromerobert** [comment]
Done
