### ISSUE TITLE
Undo always reset the current export file

### ISSUE THREAD

**Issue by jeromerobert** [pdfarranger/pdfarranger#597]
Describe the bug
----------------

Undo always reset the current export file.

To Reproduce
------------

1.  Import a file
2.  Save and set an export file
3.  Move a page
4.  Undo
5.  Save

Expected behavior
-----------------

The file should be saved to the same file as step 2. Instead we have to choose a new file name.

System and Versions
-------------------

All version & system since 1.5.2. Culprit commit is fc0749689de57583483c95cfb8441bc17858e889

`undo.Manager.__set_state` always call `model.clear` which trigger `PdfArranger.reset_export_file` through the `row-deleted` signal.

**Comment by kbengs** [comment]
I think the only time export file should be reset is when using the "close" action. I had some ideas for it in
https://github.com/kbengs/pdfarranger/commits/import-export-changes
