### ISSUE TITLE
gi.repository.GLib.Error: poppler-quark: PDF document is damaged (4)

### ISSUE THREAD

**Issue by hongyi-zhao** [pdfarranger/pdfarranger#603]
On Ubuntu 20.04.3 LTS, I installed `img2pdf` and `pdfarranger` as follows:

```
$ sudo apt install pdfarranger img2pdf
```
Then I try to import/open an image file directly with `pdfarranger` according to the description [here](https://github.com/pdfarranger/pdfarranger#install-from-source):

```
In addition, PDF Arranger supports image file import if img2pdf is installed.
```
But I meet the following problem:

```
$ pdfarranger 1.jpg 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 278, in do_open
    a.addpages(f.get_path())
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 1290, in addpages
    pdfdoc = PDFDoc(filename, self.app.tmp_dir)
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 1256, in __init__
    self.document = Poppler.Document.new_from_file(uri, None)
gi.repository.GLib.Error: poppler-quark: PDF document is damaged (4)
```
Any hints for this problem will be highly appreciated.

Regards,
HZ

**Comment by kbengs** [comment]
Ubuntu 20.04 have pdfarranger version 1.4.2 in the repository. img2pdf support was added in 1.6.0. To have the latest version you can install pdfarranger with pip according to install instructions [here ](https://github.com/pdfarranger/pdfarranger)
