### ISSUE TITLE
Wrong looking window theme on Ubuntu MATE

### ISSUE THREAD

**Issue by FabioPedretti** [pdfarranger/pdfarranger#610]
The look on Ubuntu MATE (currently on 21.10/impish) is wrong, it has a different window decoration, and eventually (i.e. sometime it appears, sometime it just has a single decoration, still differently themed) a double window decoration.
See the screenshot with a correct looking application (Atril PDF Viewer) vs. PDF Arranger.
PDF Arranger is the only application having this issue.
I remember some older versions looked fine (possibly a regression from #87, but I am not sure this is the exact culprit).

System and Versions
-------------------

-   PDF Arranger version and where you get it: 1.8.0 (jammy package I backported to impish in [my PPA](https://launchpad.net/~oibaf/+archive/ubuntu/test/+packages?field.name_filter=pdfarranger))
-   pikepdf version and where you get it: 3.2.0 (jammy package I backported to impish in [my PPA](https://launchpad.net/~oibaf/+archive/ubuntu/test/+packages?field.name_filter=pikepdf))
-   OS name and version: Ubuntu MATE (currently on 21.10/impish)

![pdfarranger](https://user-images.githubusercontent.com/3390837/148578132-d372030d-9e5a-4c0b-9dbc-caf0fcc2862d.png)

Thanks for developing pdfarranger! :1st_place_medal:

**Comment by jeromerobert** [comment]
See https://bugs.launchpad.net/ubuntu-mate/+bug/1854383
