### ISSUE TITLE
PDF Crop function does not work

### ISSUE THREAD

**Issue by gaochuanchao** [pdfarranger/pdfarranger#611]
Is it possible for me to choose which page area to crop?

**Comment by dreua** [comment]
Please explain that on more detail / add screenshots.

**Comment by gaochuanchao** [comment]
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/22146315/149468979-d0eec8b7-7e5b-4a85-83ed-e61790ffa9fa.png">
for example, for this image, is it possible for me to use my mouse to choose the content that i want to crop?

**Comment by gaochuanchao** [comment]
[picture_test.pdf](https://github.com/pdfarranger/pdfarranger/files/7868636/picture_test.pdf)
the corresponding pdf is attached.

**Comment by dreua** [comment]
Don't just add a screenshot, use the graphic to explain what exactly you want to achieve. Cropping means cutting off from the edge, I get the impression that you have a different understanding of that word. You can define how much you want to cut off from each edge in percent, mouse selection is not possible.

**Comment by jeromerobert** [comment]
@gaochuanchao If you mean graphically select on page which zone you want to keep and remove after the crop, no it's not possible. The cropped area (the zone you want to remove) can only be defined by entering the margin size. More general PDF Arranger has no way to interact at page content level.

**Comment by jeromerobert** [comment]
@gaochuanchao To work at page content level, you should use Inkscape.

**Comment by gaochuanchao** [comment]
> 

Thanks for the reply.
