### ISSUE TITLE
pdfarranger crashes on "Open with" for certain files

### ISSUE THREAD

**Issue by efkuester** [pdfarranger/pdfarranger#617]
OS: Windows 7 (fully updated)
pdfarranger versions: 1.8.1 and 1.8.2

When opening some (but not all) pdf files by right clicking on the file and choosing "Open with", then "PDF Arranger", the file will apparently load, but then a message appears saying "pdfarranger.exe has stopped working A problem has caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." No further information is given, only a "close program" button. This behavior does not occur in version 1.7.1.

I attach an example of a file for which this behavior occurs. This file was created from a scanned multipage PDF file that was subsequently split into smaller files using PDFsam Basic version 4.2.10 for Windows.
[23_PDFsam_SKM_C65922011717110.pdf](https://github.com/pdfarranger/pdfarranger/files/7891248/23_PDFsam_SKM_C65922011717110.pdf)
.

**Comment by dreua** [comment]
Does it work with other files?

**Comment by dreua** [comment]
I didn't loon closely earlier: Microsoft stopped supporting Windows 7 two years ago, I don't see why we should support it in our spare time. Please try upgrading it and see if that fixes your issue.

**Comment by jeromerobert** [comment]
MSYS2 style support Windows 7 so there is a chance that it works. The reason for the crash is likely the same than for #550 or #598. You have installed an application which pollute others either by modifying the global `%PATH%`or `%PYTHONPATH%` variables, either by installing libraries in `c:\windows\system32`.

**Comment by efkuester** [comment]
Sorry for my delay in responding---I had eye surgery that made working on this problem a challenge. Thanks for the hint given in issue #550 about the dlls; following the suggestion to use ListDlls, I found that the only difference between opening pdfarranger directly and using "Open with" when right clicking a pdf file is that two different versions of the file "libzstd.dll" are invoked. In the case of opening pdfarranger directly, the libzstd.dll in the pdfarranger program directory is used. In the case of "open with" (from the Double Commander file window, incidentally), the libzstd.dll in the Double Commander program directory is used. In fact, a search revealed that there are 9 copies of this dll in various places on my hard drive, associated with 7 different programs:

PDF Arranger (v 1.8.2): File date 5/15/2021, File size 976.4K
Double Commander (v 1.0.5beta): File date 10/15/2021, File size 651.0K
GIMP (v 2.10.30): File date 5/15/2021, File size 950.9K
gnuplot (v 5.2 patchlevel 8): File date 12/2/2019, File size 732.7K
Inkscape (v. 1.1.2): File Date 1/21/2022, File size 810.9K
TeX Studio (v 4.2.3, Qt5): File date 4/17/2022, File size 1011.5K
Paperwork (v 2.1.1-14): File Date 4/3/2022, File size 810.9K

If the Double Commander version of the file is what is causing the problem, I am unwilling to uninstall DC because I find it a very useful program. Can you suggest another workaround for this issue?

One last note: if I use "Open with" on a pdf file in Windows Explorer file manager, the behavior is unpredictable. Most of the time pdfarranger will crash as it does when using Double Commander, but on rare occasions it will work properly. I'm guessing this has to do with whatever version of libzstd.dll was invoked most recently by another program and still resides in memory somewhere.

**Comment by jeromerobert** [comment]
As you can see here https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications Windows start searching DLL in the current folder. If there is an incompatible DLL in the current folder it will crash. At PDF Arranger level we cannot control how python and GTK loads it's libraries.

What might work would be to change the current folder before running the python interpreter. Unfortunately, I have no idea how to do that. On most operating systems, changing the [current folder](https://en.wikipedia.org/wiki/Working_directory) without user action is considered a bug but on Windows, users (or developers) don't seem to care.

A dirty workaround could be creating a `.bat` or `.ps` or `.cmd` where you change the current folder to the PDF Arranger folder and start PDF Arranger. Then use that script as "Open With".

**Comment by dreua** [comment]
I wonder whether "Open With" does not have the "Start in" set properly (or not at all). I believe we hat these issues with the regular program start as well until we set "Start in" to the correct directory.
