### ISSUE TITLE
Automatic merging with complex rules

### ISSUE THREAD

**Issue by ahmedfarrag17** [pdfarranger/pdfarranger#628]
Hello!I've been looking for a fast way to merge 2 pdf documents into one. but not manually!

What I am trying to do is the following: I have 2 pdf documents (with hundreds of pages), A and B. I simply want to set rules like: Page 1, 2, 3 from pdf A, followed by page 5,6 from pdf B, then P. 4,5 from pdf A, followed by P. 7,8 from pdf B. etc. etc. 

Then when I execute these instruction, the merged pdf will have the pages arranged exactly how I put them.

If not available, what is the nearest approach to achieve it with this tool?

Thank you! 🙏🏽 I need it so bad

**Comment by jeromerobert** [comment]
So, A1, A2, A3, B5, B6, A4, A5, B7, B8 ? Sorry I don't see the logic. Could you write the algorithm ?

**Comment by dreua** [comment]
PDF Arranger can automatically merge two documents by taking alternating pages but that's it. (See the "Paste Special" menu.) Of course you can achieve any merge rule if you are willing to drag and drop the pages by hand.

I'm not sure what exactly your rule is but I guess you would need someone with basic programming skills to write a short script. For example, Python with the pikepdf library (which PDF Arranger uses internally) should work fine. (I'm sure there are other solutions for other languages. Maybe CLI-Tools like pdftk or Qpdf could support this, but you may need to list all the pages explicitly.)

(Jerome was faster sending his comment.)

**Comment by ahmedfarrag17** [comment]
> So, A1, A2, A3, B5, B6, A4, A5, B7, B8 ? Sorry I don't see the logic. Could you write the algorithm ?


I just made an Example.
The rule will depend on the pdf I want to create.
What happens is that I often have to read 2 textbooks of the same subject. What I want to do is to have (at the end, After reading them) a single "Textbook" that has pages taken from both of the textbooks, but obviously I will put the pages in a logical order (for ex. If pdf A explains a concept in pages 5 and 6 and pdf B explains it in 10 and 11. I will do A5-A6-B10-B11).

So my job is to annotate the sequence while I am reading the textbooks.
And at the end. I create a Single pdf with my sequence. 

The problem is that those pdf files may have hundreds of pages. So It will take a lot to arrange pages manually with drag &drog.
To avoid this I am looking for a tool (I thought this one could do it!) where I input my sequence with this approach (or a similar one): A5-A6-B11-B12-B13-A8-A9-B100 or whatever!!
(Maybe I write it down in a .txt file that communicates with pdfArranger and it creates my desired pdf).

Did you get it?
It would save me hours. (Unfortunately I have 0 Coding knowledge :( that's why I am looking for an existing tool for it).

**Comment by ahmedfarrag17** [comment]
> PDF Arranger can automatically merge two documents by taking alternating pages but that's it. (See the "Paste Special" menu.) Of course you can achieve any merge rule if you are willing to drag and drop the pages by hand.
> 
> I'm not sure what exactly your rule is but I guess you would need someone with basic programming skills to write a short script. For example, Python with the pikepdf library (which PDF Arranger uses internally) should work fine. (I'm sure there are other solutions for other languages. Maybe CLI-Tools like pdftk or Qpdf could support this, but you may need to list all the pages explicitly.)
> 
> (Jerome was faster sending his comment.)

Thank you for your answer! 
Unfortunately I don't know how to code. But allow me to explain better what I am exactly looking for with a clear practical example.


The rule will depend on the pdf I want to create.
What happens is that I often have to read 2 textbooks of the same subject. What I want to do is to have (at the end, After reading them) a single "Textbook" that has pages taken from both of the textbooks, but obviously I will put the pages in a logical order (for ex. If pdf A explains a concept in pages 5 and 6 and pdf B explains it in 10 and 11. I will do A5-A6-B10-B11).

So my job is to annotate the sequence while I am reading the textbooks.
And at the end. I create a Single pdf with my sequence. 

The problem is that those pdf files may have hundreds of pages. So It will take a lot to arrange pages manually with drag &drog.
To avoid this I am looking for a tool (I thought this one could do it!) where I input my sequence with this approach (or a similar one): A5-A6-B11-B12-B13-A8-A9-B100 or whatever!!
(Maybe I write it down in a .txt file that communicates with pdfArranger and it creates my desired pdf).

Did you get it?
It would save me hours. (Unfortunately I have 0 Coding knowledge :( that's why I am looking for an existing tool for it).

**Comment by dreua** [comment]
Have a look [QPDF documentation's section on page selection](https://qpdf.readthedocs.io/en/stable/cli.html#page-selection-options), maybe you can take note of the pages in a format that can be fed into qpdf. I'd recommend renaming the PDFs so that they have very short names. :wink: 
Alternatively you could open multiple PDF Arranger windows and drag the pages into a new (empty) Window was you go. Don't forget to save every now and then!
