### ISSUE TITLE
UserWarning: The metadata field /Trapped with value 'pikepdf.Name("/False")' has no XMP equivalent, so it was discarded

### ISSUE THREAD

**Issue by md-work** [pdfarranger/pdfarranger#633]
Simply opening and saving this PDF triggers an error message.
[Deutsche-Bahn_German-Railway_Ticket.pdf](https://github.com/pdfarranger/pdfarranger/files/8133447/Deutsche-Bahn_German-Railway_Ticket.pdf)

Error:
```
/usr/lib/python3/dist-packages/pikepdf/models/metadata.py:324: UserWarning: The metadata field /Trapped with value 'pikepdf.Name("/False")' has no XMP equivalent, so it was discarded
```
_(GUI displays the part "UserWarning ... was discarded")_

&nbsp;

System and Versions
-------------------

-   PDF Arranger version: 1.6.2-1 (Debian-11.1)
-   pikepdf version: 1.17.3+dfsg-5 (Debian-11.1)
-   OS name and version: Debian-11.1 (x86_64)

You can simply use a Debian-11.1 live cd for testing.
https://cdimage.debian.org/mirror/cdimage/archive/11.1.0-live/amd64/iso-hybrid/debian-live-11.1.0-amd64-xfce.iso
Run to install pdfarranger: `sudo apt install pdfarranger`

**Comment by kbengs** [comment]
This is a (non critical) warning message saying that a metadata value has been discarded. The exported file still looks fine doesn't it? This message is very common. I have been working on a improved dialog that more clear would say that this is only a warning.

**Comment by dreua** [comment]
Just did a quick test with 1.8.2: Same error message but the resulting file looks fine.

**Comment by ferengi82** [comment]
would be nice if there was an option to disable this warnings.

**Comment by kbengs** [comment]
In 1.9.2 it is possible.
![image](https://user-images.githubusercontent.com/60842129/209939470-3e3748d6-071d-4b26-885b-e545d7842f14.png)
You can install latest pdfarranger with pip with the instructions here:
https://github.com/pdfarranger/pdfarranger#install-from-source

**Comment by ferengi82** [comment]
thx for the info, I hope that I can convince my admins to install the new version.

**Comment by kbengs** [comment]
The warning in the title of this issue is about the metadata (the type of data you can see in the "Edit properties" dialog) which was lost when the pdf metadata was saved to the newer xmp format.

The underlying libraries qpdf and pikepdf does support  preserving of links in some situations. But the way pdfarranger handles pages they are unfortunately lost. @m-holger recently commented in #462 that there is hope for preserving of links in pdfarranger in the future.
