### ISSUE TITLE
Import large PDF not rendering 

### ISSUE THREAD

**Issue by pit65** [pdfarranger/pdfarranger#636]
Import large PDF 56000x10000 px not rendering picture.
Only see white rectangle.

https://files.fm/u/fankfu2xm

Tested on Slackware64 15.0 and MX Linux.

**Comment by kbengs** [comment]
I confirm this bug. I also see that Evince will not render this PDF either. Okular does render and also Sumatra PDF.

**Comment by dreua** [comment]
I confirm the white rectangle, but I wonder whose bug this is. The PDF shows as...

*white rectangle* in:
- Firefox
- Gimp (but Import preview looks good)
- PDF Arranger (uses poppler)
- Evince (uses poppler)
- Libreoffice Draw
- Inkscape

*visible plan* in:
- Okular (uses poppler?!)
- Chroium (after a few seconds of waiting time)

**Comment by pit65** [comment]
also:
XnwiewMP -good
Xpdf           -good
pdfshuffle   - not
geeqi          - not
display (IM)  - good
chromium    -  good

In my old  Slackware14.2  pdfshuffle  render OK, but in newer 15 not render.

**Comment by dreua** [comment]
I wonder whether that PDF is just hughe or maybe damaged. Did something try to open it on Windows / Adobe Reader?

**Comment by pit65** [comment]
this is just jpg scan 2.4x0.45 meters 600 DPI converted by imagemagick to PDF.
It is not demaged.
You can unwrap original jpg raster as it is :
`pdfimages -j xxx.pdf   1`
check it and wrap it up  again to pdf for example by pdfarranger.
PIL do not allow it giving error about to many pixels (fork bomb) so add line 
```
from PIL import Image, ImageCms
**Image.MAX_IMAGE_PIXELS = None**
```
to a file /usr/lib64/python3.9/site-packages/pikepdf/models/image.py
You can now import  jpg to pdfarranger and export it to pdf.
This pdf open in xpdf and rendering picture properly but in pdfaranger not (white rectangle )

**Comment by dreua** [comment]
So you modified pdfimages / pikepdf to create that PDF and are now complaining that it is not supported by PDF Arranger (and a lot of other viewers)?
Please make sure that your PDF is actually valid, there may be a reason why pikepdf didn't accept it in the first place.

Until proven otherwise, I'll assume that PDF is broken / not compliant to the standards. Some viewers may be more relaxed and show it anyway but that does not mean that everyone needs to support it.

**Comment by dreua** [comment]
You may, however, create a feature request about this in pdfimages: There should be a way to properly create a PDF if this size, I think I've seen PDFs where the images was included not in one piece but broken down into smaller tiles. (Just guessing here.)

If you do so, please post a link to that new issue here.

**Comment by jeromerobert** [comment]
According to pit65 and my tests the bug report or feature request should be addressed to Poppler not to pdfimages.

**Comment by dreua** [comment]
For Firefox / pdf.js there is an issue here: https://github.com/mozilla/pdf.js/issues/6741
For poppler: https://gitlab.freedesktop.org/poppler/poppler/-/issues/511

Doesn't look like there's a fix in sight, unfortunately. Maybe all the architecture-companies should consider raising some money to get some OSS developers to fix this?
