### ISSUE TITLE
Windows package for 1.8.2 version seems to be broken

### ISSUE THREAD

**Issue by jurask** [pdfarranger/pdfarranger#644]
When I start pdfarranger on windows 10, I just get error message. It seems the windows package is missing some libraries. See attached image for more info.
![obrazek](https://user-images.githubusercontent.com/33560094/157205051-f2af0152-1c4e-449b-aeac-880465e657ae.png)

**Comment by dreua** [comment]
I'd guess the last part translates to "The specified procedure could not be found."
This is usually not a broken package but a common problem on Windows. To quote @jeromerobert:
> The reason for the crash is likely the same than for #550 or #598. You have installed an application which pollute others either by modifying the global `%PATH%`or `%PYTHONPATH%` variables, either by installing libraries in `c:\windows\system32`.

**Comment by dreua** [comment]
I'm closing this as duplicate, let us know if you need any more help.
