### ISSUE TITLE
Errors and crashes due to loading of the wrong DLL on Windows

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#645]
We get bug reports about this on a regular basis. I am creating this meta-issue to collect those and have a place to discuss whether we can do something about that.

- #550 Open With: "cx_Freeze: Python error in main script" / "ImportError: pikepdf's extension library failed to import"
- #598 Open With: "cx_Freeze: Python error in main script" / "ImportError: DLL load failed while importing etree: The specified procedure could not be found"
- #617 Open With: "pdfarranger.exe has stopped working A problem has caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."
- #644 Regular start: "cx_Freeze: Python error in main script" / "ImportError: DLL load failed while importing _gi: [Foreign language, translation is probably: The specified procedure could not be found.]"

Other older issues about Windows' DLL loading. I guess they have been fixed in 1.7.0:
- #122 
- #176
- #300 
- #316 
- #380 (duplicate of #316)

Just looking at the issue numbers, I see a gap between 380 and 550, so I believe the first issue has been fixed, at least to some degree. Now I wonder if we can fix the remaining issue: It seems to be most common when using "Open with" and having other applications using the same libraries installed.

PS: Feel free to edit this post.

**Comment by kbengs** [comment]
`ctypes.windll.kernel32.SetDefaultDllDirectories(0x1000)`
Before import of pikepdf seems to fix the tesseract issue

https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-setdefaultdlldirectories

Idea is from here:
https://github.com/numpy/numpy/wiki/windows-dll-notes
https://github.com/hanjohn/numpy/commit/1fcb19492c5a262baed79669c21410257bd34295

**Comment by jeromerobert** [comment]
Excellent ! I didn't know it was possible to change that after the process has been started. This will annihilate the effect of user's `PATH` and should fix all those bugs.

The only problem that will remain is the case of files installed in system32. But as far as I remember we had only one bug in this case.

**Comment by kbengs** [comment]
Yes files in system32 might still be a problem. But I think it should be more unlikely that too.

I have tried to reproduce problems with mitmproxy and double commander but haven't seen any issues with them (not before the patch or after). I will make a PR when I have tested some more.
