### ISSUE TITLE
pdfarranger installed 'successfully', yet no way to run it

### ISSUE THREAD

**Issue by simong1080** [pdfarranger/pdfarranger#646]
OS: Linux topkek 5.4.0-104-generic # 118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

After running `pip3 install --user --upgrade https://github.com/pdfarranger/pdfarranger/zipball/main
`
get this warning:
```
Installing collected packages: lxml, pikepdf, python-dateutil, pdfarranger
  WARNING: The script pdfarranger is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed lxml-4.8.0 pdfarranger-1.9.0.dev1 pikepdf-5.0.1 python-dateutil-2.8.2
```
Added `export PATH=/Library/Frameworks/Python.framework/Versions/3.8/bin:$PATH
`
to `~/user/.bashrc`, (per https://stackoverflow.com/a/63442682) reinstalled with above `pip3` command, yet situation remains the same.

Even trying to run` /root/.local/bin/pdfarranger `as superuser in terminal doesn't work

**Comment by jeromerobert** [comment]
> WARNING: The script pdfarranger is installed in '/root/.local/bin' which is not on PATH.

`pip install` must not be run as root (unless you are building a docker image).

> Added export PATH=/Library/Frameworks/Python.framework/Versions/3.8/bin:$PATH

This is for MacOS, you are running Ubuntu

> Even trying to run/root/.local/bin/pdfarrangeras superuser in terminal doesn't work

Because root does not have access to the X11 server (by default).

As you are running Ubuntu 20.04, you'll also have to read https://github.com/pdfarranger/pdfarranger/issues/638.
