### ISSUE TITLE
Add printing support

### ISSUE THREAD

**Issue by thelazy6** [pdfarranger/pdfarranger#647]
For productivity reasons, please add printing support directly out of the application. It will save a lot of use-time if you don't need to use an external application just for printing.

**Comment by dreua** [comment]
I don't think we are going to do that, the unix philosophy is one tool for one job and there is already a lot of tools for printing PDFs. Furthermore I'm worried that maintaining this (especially on Windows) may create a stream of issue reports that we don't really want to deal with here. That's just my gut feeling about printing, haven't done any research tbh.

If you want to improve your recurring workflows I would recommend using keyboard-shortcuts and maybe (especially on Linux) some scripting. It should, for example, be not too hard to hack something together which watches a directory for changes and prints any PDF saved there with default options. (Or options defined by a pattern in the filename in case you need different profiles or such.) Voila, your save option is your new print option :wink: 

*Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.*

**Comment by jeromerobert** [comment]
It's seems simple to implement and do not require additional dependencies, so let's keep it on the TODO list. See https://stackoverflow.com/questions/28325525/python-gtk-printoperation-print-a-pdf

**Comment by Techwolf** [comment]
This feature would be handy for me. Right now, I have a PDF that I edited out some un-needed pages for printing. I now have to save it and figure out what program would be best to use for printing. Currently, that is the browser. I use ungoogle-chromium built from source. (Gentoo user here) If nothing else, be able to configure an "Open in <program>" would be a nice workaround for the full feature print dialog that may be "easy to say, hard to do" feature.

**Comment by logari81** [comment]
I kind of share dreua's viewpoint, so maybe Techwolf's suggestion about an "Open in ..." feature, would be a good solution.

If it is decided to implement printing though, looking at the gtk-print-preview-command might also be useful, like here:
https://help.gnome.org/users/gnumeric/stable/sect-printing-preview.html.en
