### ISSUE TITLE
Dark theme on Windows?

### ISSUE THREAD

**Issue by Tamarindo94** [pdfarranger/pdfarranger#657]
I was wondering if there's a way to enable the dark theme on Windows through the config.ini file

**Comment by jeromerobert** [comment]
No it's not possible through config.ini.

Google give me this: https://stackoverflow.com/questions/36464010/change-gtk3-look-on-windows.

The PDF Arranger windows zip is contains only a minimal GTK. You may need to install PDF Arranger in MSYS2 to make this Stackoverflow post work. Reading https://github.com/pdfarranger/pdfarranger/blob/main/Win32.md will help.

If you can make it work I could update the PDF Arranger zip from your feedback.

**Comment by Tamarindo94** [comment]
Thanks for your reply! I'll look into it

**Comment by SiddharthSharma16923** [comment]
there is a way to have dark theme in every app that you ever used without fretting with any code  
first set themes of all your apps to white theme  
go to windows color filter settings , set it to inverted greyscale  , enable ctrl+win+c shortcut  
bro use dark mode as a tool  
whenever you are in a dark place, smash ctrl+win+c  
  
isnt it kinda stupid to code down dark modes into apps? , what you think?

**Comment by yw4z** [comment]
im also intrested with dark theme on portable version

i found https://stackoverflow.com/questions/16740949/gtk-cssprovider-how-do-id-based-selectors-work-in-gtk3

PDFarranger\share\pdfarranger\pdfarranger.ui file contains all required ids for CSS

if you allow importing from CSS. i can create CSS files for dark and light themes

**Comment by jeromerobert** [comment]
You may also try this instead of patching: https://github.com/pdfarranger/pdfarranger/issues/742#issuecomment-1279707356

**Comment by yw4z** [comment]
sorry but didnt understand how to apply that on windows

**Comment by jeromerobert** [comment]
It will be clear once you have installed PDF Arranger from source (see https://github.com/pdfarranger/pdfarranger/blob/main/Win32.md).

**Comment by Mitch037** [comment]
Any chance we can get built-in Dark Mode/Theme in PDF Arranger? It would be really useful. I use lots of apps and all of them have dark-mode enabled.

**Comment by dreua** [comment]
@Mitch037 We absolutely do feature a dark theme and it works beautifully on Linux. What we currently don't feature is a developer who fixes all those incompatibilities we have on that platform.

**Comment by kbengs** [comment]
If no one is eager to fix this I can do it. I actually did a test yesterday and was able to have dark theme on Windows.

**Comment by Gitoffthelawn** [comment]
@kbengs Would love it! Thanks!

**Comment by kbengs** [comment]
If someone want to test a zip/msi can be found here:
https://github.com/pdfarranger/pdfarranger/actions/runs/3732775335
If Windows is set to dark pdfarranger should be dark.

**Comment by yw4z** [comment]
it works ok for me on latest windows 10 ltsc, only weird thing shadows under pages rendered as grey and page border is black.
it could be same as light theme. otherwise it looks great. also great to have an option to choose color theme on preferences. thanks for your effort
