### ISSUE TITLE
Add page numbers

### ISSUE THREAD

**Issue by indigoviolet** [pdfarranger/pdfarranger#662]
Thank you for this fantastic tool.

Page numbering would be a really useful feature since we are merging/joining pdfs. Here is an example UI from https://avepdf.com/paging-pdf:

![image](https://user-images.githubusercontent.com/114010/165463559-3ded089c-ad08-4325-8d61-dd1d54950e84.png)

**Comment by dreua** [comment]
Sounds like a useful feature but I'm not sure if someone of the team is going to work on it. I'm open to discuss options in case someone wants to work on this.

As always in such cases: Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.
