### ISSUE TITLE
Unable to find disk in drive error on file open (Windows driver issue)

### ISSUE THREAD

**Issue by marcogaio** [pdfarranger/pdfarranger#666]
Just installed version 1.8.2 on Win7 64bit.
When i try to open a file, throw this error:
![Schermata da 2022-05-03 12-50-29](https://user-images.githubusercontent.com/7048664/166441021-06558317-f613-4b2a-bfaa-a9a57a9410e4.png)

Literally: Unable to find disk in drive. Insert disk in drive \Device\HardDisk1\DR1.

Thanks.

**Comment by marcogaio** [comment]
OK, sorry, it was the `I:` disk associated with a malfunctioning device/driver; disabled the driver now the program works as expected.

Still i keep the bug open, because i think the program have to behave a bit better on windows failing drivers...

Sorry.

**Comment by dreua** [comment]
I'm not sure we can do anything about this here. What better behavior would you expect? Do other Windows programs deal with this better / differently?

**Comment by marcogaio** [comment]
Other windows program never noticed the mulfunctioning device/driver, while pdfarranger popups this error, and was not able to open files (so the problem is blocking).

But, really, i don't know how to trigger it...

**Comment by angsch** [comment]
Do you get the issue no matter if you use the keyboard shortcut (Ctrl + O) or import via the graphical user interface?

**Comment by dreua** [comment]
I'm sorry I don't think there is anything we can reasonably do about this. At any rate, this is most likely not a bug in PDF Arranger but in the Gtk library we use for file selection.

You are running Windows 7 which is no longer supported by its vendor (Microsoft), I don't think the developers of Gtk and PDF Arranger have the resources to fix this in our spare time. Do let us know in case this is reproducible on a supported operating system.
