### ISSUE TITLE
Booklet generation incorrect on specific PDF

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#681]
Describe the bug
----------------

The position of individual pages in the Generate Booklet feature is off for certain PDFs.

To Reproduce
------------

1.  Import tests/test.pdf
2.  Split the first page.
3.  Generate booklet from the first two pages

Screenshots
-----------

![image](https://user-images.githubusercontent.com/17718454/173662018-d8300cc1-ce53-4e09-9604-0adbf6ddd287.png)

Interestingly, if both pages of test.pdf are split and the middle pages are removed, the result is as expected.

![image](https://user-images.githubusercontent.com/17718454/173662576-60fc536e-1238-47ff-b870-63747afded51.png)

**Comment by angsch** [comment]
Another case of https://github.com/pdfarranger/pdfarranger/issues/579?

**Comment by jeromerobert** [comment]
Well seen. In https://github.com/pdfarranger/pdfarranger/commit/5e58d3e9534d3823017cfd58baebb6709f645637 I only fixed `export_doc`. `generate_booklet` needs the same fix that is, have the new PDF file adopt the original page *before* applying the transforms. I'm on it.
