### ISSUE TITLE
Crash when opening 50MB 108 page pdf

### ISSUE THREAD

**Issue by Terminalator** [pdfarranger/pdfarranger#688]
Please forgive any lack of correct formatting as I'm not used to submitting bug reports.

I scanned a "multi-session" 108 page pdf doc on a Fujitsu ix500 with a Win 7 VM. I thought I'd be able to dissect it in pdfarranger but turns out it crashed every time I open this particular file. The feedback from terminal is this:

`python: ../cairo/src/cairo-error.c:68: _cairo_error: Assertion (backtick here)_cairo_status_is_error (status)' failed.
Aborted (core dumped)`

I'm using a fully updated Arch Linux install and have this problem only on this file. Any others I tried (including Win 7 VM ones) appear to work fine. I can't attach the file as it if full of personal documents.

Again, apologies if this report is not formatted properly or is missing required info.

**Comment by Terminalator** [comment]
Raised a bug report correctly

**Comment by dreua** [comment]
New ticket is #689 
For future reference: You can also edit an existing issue using the three-dot-menu in the top right cornern.
