### ISSUE TITLE
Add bookmarks of files so combined

### ISSUE THREAD

**Issue by ghost** [pdfarranger/pdfarranger#690]
Action: combine some pdfs into 1  
Expectation: there shall be 10 bookmarks(in the resulting pdf) with the filename of the 10 pdf files so used  
and this shall be a default behavior

**Comment by SiddharthSharma16923** [comment]
more suggestions , but not really important for functionality (there are workarounds for them  but would love to see them)  
1. sort files dragged into pdfarranger acccording to the sorting of source (workaround is to use import button)  
- how about sort by selection (in the order of selection is made in the import panel) , this would kill a lot of fret (workaround is to rename every file and prefix them with alphabets or numbers and then name sort and import , , another is to drag in order ....but if sort by order of selection was there it would kill all this fret)
3. a progress bar? (no please no , i hate progress bars(they are just addictive and dont add to any functionality), a Time Estimate is Needed , with a throbber , i am unable to tell , that if pdf arranger is dead or not, bcz of large files )  
  
these are totally my personal opinions , no offence

**Comment by kbengs** [comment]
> files dragged from explorer are not sorted at all

They seem to be in some kind of order: The one you click when you start the drag will be the first one inserted in pdfarranger. After that they will follow in same order. So if you want them in same order as in Windows Explorer you need to start the drag by clicking on the first (top-left) item in Explorer.

> a progress bar

Would this be when importing files? Are you using 1.8.2? The main branch has some speed improvement when importing files. Also the behavior when saving is improved so it should not give the impression that the app has frozen when saving large files.

**Comment by dreua** [comment]
I don't think that would be a useful feature without the possibility to edit bookmarks, so that would be needed to be implemented first.
