### ISSUE TITLE
Incompatible with qpdf 11 / pikepdf 6

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#716]
I pushed an update of the Flatpak with qpdf 11 and pikepdf 6 which failed, see #715. (It is now reverted to the older versions.)

Those are really fresh so this is not super urgent but we should have a look at it and probably release a compatible version before those versions are picked up by the distributions.

Developers can install and run the broken version like this:

```
flatpak update --commit=7b6b43edae3f8fadde8cc076a8b650cff650f795796f32f921aefb3f363ce180 com.github.jeromerobert.pdfarranger
```

```
$ flatpak run com.github.jeromerobert.pdfarranger 
Gtk-Message: 19:11:25.978: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:11:25.979: Failed to load module "pk-gtk-module"
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 976, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/app/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 160, in wrapper
    func(*args, **kwargs)
  File "/app/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 1050, in save
    exporter.export(self.pdfqueue, to_export, file_out, mode, m)
  File "/app/lib/python3.9/site-packages/pdfarranger/exporter.py", line 177, in export
    new_page = pdf_output.copy_foreign(current_page)
NotImplementedError: Use pikepdf.Pdf.pages interface to copy pages from one PDF to another.
```

The error message appears as soon as you try to save anything (e.g. "Insert blank page", Ctrl+S).

**Comment by dreua** [comment]
I should have read the release notes: https://github.com/pikepdf/pikepdf/blob/master/docs/releasenotes/version6.rst :facepalm:

**Comment by jeromerobert** [comment]
Good shot. This is too delicate for 1.9. It will be for 1.10 (or 1.9.1 if we have many requests).

**Comment by jeromerobert** [comment]
More likely 1.9.1 as Arch Linux is already affected by this bug.

**Comment by ksaadDE** [comment]
I think this is fixed. A few seconds ago I got the "pikepdf.pdf.pages" error. After installing the repo using pip it did work. So I guess it is this fix. It broke after sysupdate a few days ago.

**Comment by ArchangeGabriel** [comment]
FTR, I’ve backported the fix in Arch.

**Comment by dreua** [comment]
Here is a testbuild of the current main in case someone wants to check it out:
https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/112

> Build [111637 successful](https://buildbot.flathub.org/#/builders/32/builds/111637) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/109246/com.github.jeromerobert.pdfarranger.flatpakref
> ```
