### ISSUE TITLE
Split Pages and Create Booklet Fails

### ISSUE THREAD

**Issue by flywire** [pdfarranger/pdfarranger#720]
Describe the bug
----------------

A [document](https://github.com/pdfarranger/pdfarranger/files/9592821/Rain-Harvesting-Handbook-AU-Issue-2-2021-web.pdf) of A4 cover and back sheet with A3 pages appears to split into A4 sheets successfully but fails to successfully reform into a booklet.

The second and third last page are alternately reproduced on the left side.

To Reproduce
------------

1.  Open the linked document
2.  Select page 2 to second last page (page 61)
3.  Split Pages 2 columns
4.  Select page 2 to second last page, Generate Booklet

Expected behavior
-----------------

Document to be reconstructed as original.

Input files
-----------

Document is linked in description.

Screenshots
-----------

System and Versions
-------------------

PDF Arranger V1.9.0, Win10 from GitHub release.
-   It uses libqpdf 10.4.0, pikepdf 4.3.1, GTK 3.24.31 and Python 3.9.7.

**Comment by jeromerobert** [comment]
We had issues with duplicate/split pages in previous versions (depending of the version pikepdf) but it seems different this time. If we put the split aside we reproduce the bug:

* Select page 2 to second last page (page 61)
* Split Pages 2 columns
* Save to a new file and check (with okular or evince) that it's good
* Restart PDF Arranger and import the file with splitted pages
* Select all pages, generate a booklet
* See the mess 😕

Tested with both 4.3.1 and 6.0.1.

**Comment by jeromerobert** [comment]
I introduced this bug in 5101510e 😬
