### ISSUE TITLE
merge in command line

### ISSUE THREAD

**Issue by shawn8888** [pdfarranger/pdfarranger#728]
I was wondering if PDFArranger supports command line merge.  Something like pdfarrange a.pdf+b.pdf to c.pdf
I would like to write a DOS batch file to merge multiple PDF files. 
Thanks!

**Comment by dreua** [comment]
That is possible using the [Qpdf CLI](https://qpdf.readthedocs.io/en/stable/cli.html). Since we are using the qpdf library under the hood, it would be pointless to re-implement such functionality in PDF Arranger, wouldn't it?
