### ISSUE TITLE
PDF Arranger 1.9.x is not dark with Adwait dark theme on XFCE4

### ISSUE THREAD

**Issue by RbnJrg** [pdfarranger/pdfarranger#742]
I don't know why but suddenly dark themes are not working with PDFArranger under Linux.  Maybe something linked with the last Python update?

**Comment by dreua** [comment]
To quote our bug issue template:

System and Versions
-------------------

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)

**Comment by jeromerobert** [comment]
Could you try to downgrade to 1.8.x and see if dark theme is back ?

**Comment by dreua** [comment]
Reproducible with Flatpak on my older Fedora 35, works on my Fedora 36. `flatpak-bisect` indeed narrowed that down to the 1.9.0 update. Not reproducible when installed with pip from the same machine :shrug:

**Comment by RbnJrg** [comment]
> Could you try to downgrade to 1.8.x and see if dark theme is back ?

I downgrade to the previous version (that it worked fine) and now, it also doesn't accept the dark theme.

**Comment by dreua** [comment]
How did you install PDF Arranger? (There are different ways as indicated in my first response here.)

**Comment by RbnJrg** [comment]
> To quote our bug issue template:
> ## System and Versions
> 
>     * PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)

Sorry.  It's PDFArranger 1.9.1.1 with libqpdf 11.1.1, pikepdf 6.1.0, GTK 3.24.34 y Python 3.10.7. I downloaded it from the oficial repository of Arch Linux version 5.15.71-1-lts.

**Comment by RbnJrg** [comment]
> The only change which can affect style is the use of libhandy. It was added between 1.8.2 and 1.9.0 by @oscfdezdz . He is using a dark theme and fixed it in #649 which is 1.9.0 and 1.9.1. So if you still have the issue with 1.8.2 it means that the bug is not on our side but more likely in GTK.

Many thanks for your time. Now I have downgraded to version 1.8.2 and dark theme is ok!; it is work as expected.

**Comment by jeromerobert** [comment]
Not nice. It means that issue comes from libhandy. Could be related to this: https://github.com/pdfarranger/pdfarranger/blob/76a8131/pdfarranger/pdfarranger.py#L312-L318
But Arch libhandy is now 1.8.0 which is more than enough. So I don't know.

**Comment by jeromerobert** [comment]
@RbnJrg could you try this patch with 1.9.1 and report any suspect error message in the console ?

```patch
--- a/pdfarranger/pdfarranger.py
+++ b/pdfarranger/pdfarranger.py
@@ -309,13 +309,9 @@ class PdfArranger(Gtk.Application):
         self.uiXML = b
         self.window = self.uiXML.get_object("main_window")
         if Handy:
-            try:
-                Handy.StyleManager.get_default().set_color_scheme(
-                    Handy.ColorScheme.PREFER_LIGHT
-                )
-            except AttributeError:
-                # This libhandy is too old. 1.5.90 needed ?
-                pass
+           Handy.StyleManager.get_default().set_color_scheme(
+                Handy.ColorScheme.PREFER_LIGHT
+            )
             # Add an intermediate vertical box
             box = Gtk.Box()
             box.props.orientation = Gtk.Orientation.VERTICAL
```

**Comment by RbnJrg** [comment]
> Not nice. It means that issue comes from libhandy. Could be related to this: https://github.com/pdfarranger/pdfarranger/blob/76a8131/pdfarranger/pdfarranger.py#L312-L318 But Arch libhandy is now 1.8.0 which is more than enough. So I don't know.

The version of libhandy installed in my system is 1.8.0-1 and was installed on Sep 17. The curious thing is that PDFArranger worked fine (that is, the dark theme was there) until yesterday when I update the system and libhandy remained unchanged, but dark theme disapeared.

**Comment by RbnJrg** [comment]
Well, I tried the patch and nothing. No error message in the console and PDFArranger started fine. I don't know but maybe this statement:

Handy.ColorScheme.PREFER_LIGHT

shouldn't be:

Handy.ColorScheme.PREFER_DARK.

**Comment by oscfdezdz** [comment]
Which DE are you using? FreeDesktop's dark style preference is supported from GNOME 42, KDE 5.24 and elementary OS 6.1 as far as I know. I have not seen any problems between Handy and themes either.

**Comment by RbnJrg** [comment]
> Which theme are you using ?

Dark Adwaita, but I also tried with all others dark themes and the result is the same.

**Comment by RbnJrg** [comment]
I don't know if this can help you. I downloaded and installed the package Themix/Oomox theme designer and I build a custom dark theme, similar to Adwaita and PDFArranger (1.9.1) accepted that custom dark theme. The themes generated by Oomox are GTK themes (also Adwaita is a GTK theme) but it seems that PDFArranges likes themes made with Oomox while refuses Adwaita Dark. And, as I said, both are GTK themes.

**Comment by jeromerobert** [comment]
Ok I can reproduce the bug. PDF Arranger does not honor the Adwait dark theme.

**Comment by RbnJrg** [comment]
> Ok I can reproduce the bug on Debian. PDF Arranger does not honor the Adwait dark theme.

And PDFArranger it doesn't accept Qogir-dark either (another GTK theme). But very probably if you find a fix por Adwaita, it will work for all kind of dark themes.

**Comment by oscfdezdz** [comment]
You can try https://gitlab.gnome.org/exalm/color-scheme-simulator, if it works it means Handy implementation only handles FreeDesktop preference and since XFCE does not support it, it will not work with legacy behavior. Although, it could probably coexist with https://docs.gtk.org/gtk3/property.Settings.gtk-application-prefer-dark-theme.html if we handle it.

After installing Color Scheme Simulator to change from light to dark theme or vice versa you need to run `gsettings set org.gnome.gitlab.exalm.Impatience color-scheme "prefer-dark"` or `gsettings set org.gnome.gitlab.exalm.Impatience color-scheme "prefer-light"`.

**Comment by RbnJrg** [comment]
> You can try https://gitlab.gnome.org/exalm/color-scheme-simulator, if it works it means Handy implementation only handles FreeDesktop preference and since XFCE does not support it, it will not work with legacy behavior. Although, it could probably coexist with https://docs.gtk.org/gtk3/property.Settings.gtk-application-prefer-dark-theme.html if we handle it.
> 
> After installing Color Scheme Simulator to change from light to dark theme or vice versa you need to run `gsettings set org.gnome.gitlab.exalm.Impatience color-scheme "prefer-dark"` or `gsettings set org.gnome.gitlab.exalm.Impatience color-scheme "prefer-light"`.

I installed the package you said and nothing; PDFArrager is not accepting dark adwaita. I tried by running the commands you indicated in the console and I tried with the GUI that comes with  Color Scheme Simulator and nothing worked.

**Comment by jeromerobert** [comment]
`Handy.StyleManager.get_default().set_color_scheme(Handy.ColorScheme.PREFER_DARK)` does work but we need a way to know if the current theme is dark or not.

`Gtk.Settings.get_default().get_property("gtk-application-prefer-dark-theme")` return `False` with Adwaita Dark. Do we have an other way to know that we are using a dark theme ?

**Comment by jeromerobert** [comment]
May be with `Gio.Settings` and `org.gnome.desktop.interface` / `color-scheme` ?

**Comment by jeromerobert** [comment]
2 possibilities:
- Removing libhandy (which I still don't know what it aims to provide)
- Add a key to configure dark vs light theme in the `config.ini` file. More than a workaround for this issue, it will allow user to use a dark theme in PDF Arranger on a light desktop.

**Comment by jeromerobert** [comment]
My bad, this is working:

```
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
```

XFCE4 does not update *gsettings* but only *xsettings* that's why the user must manually enter that command.
