### ISSUE TITLE
[CI] Update RPM building image

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#743]
This is still based on Fedora 33, I'll need to update that. Ideally automate that to rebuild the image every 6 months or so.

**Comment by dreua** [comment]
Manually done for now. I might look into automation at another time.

Latest run is green (note the "fc36" part in the packages once you downloaded and extracted the artifacts): https://github.com/pdfarranger/pdfarranger/actions/runs/3185225379

Some notes to future-me:

Images: https://hub.docker.com/repository/registry-1.docker.io/dreua/pdfarranger-docker-rpm/tags?page=1&ordering=last_updated
Dockerfiles: https://github.com/jeromerobert/pdfarranger-docker-ci

```
cd git/pdfarranger-docker-ci/rpmbuild/
docker build -t docker.io/dreua/pdfarranger-docker-rpm .
docker tag docker.io/dreua/pdfarranger-docker-rpm:latest dreua/pdfarranger-docker-rpm:1.9

podman login -u dreua docker.io
# Don't use your email here, it never worked and will never work -.-
docker push dreua/pdfarranger-docker-rpm:1.9
docker push dreua/pdfarranger-docker-rpm:latest
```

**Comment by dreua** [comment]
Downside of automation: It looks like there is no way without the need to put store my Dockerhub-credentials in the CI... Probably not worth the hassle.

**Comment by jeromerobert** [comment]
For Github Action usage https://ghcr.io would probably be better than Docker Hub.
