### ISSUE TITLE
Clickable links (hypertext links)

### ISSUE THREAD

**Issue by STVGecko** [pdfarranger/pdfarranger#749]
Hello, thanks for the application.

If I hover over a link in a PDF, can you add the ability to highlight it and to open it (example shortcut: Ctrl+left-click on the link)

**Comment by dreua** [comment]
I don't understand the use case here. PDF arranger is not intended as a viewer but only to rearrange, combine and split PDFs. If you want clickable links, use any PDF viewer out there, it will be better for viewing PDFs anyway. Please try the shortcut you are suggesting, it's already taken and in good use for this application.
