### ISSUE TITLE
Wrong page format of previously splitted pages

### ISSUE THREAD

**Issue by wiznews** [pdfarranger/pdfarranger#750]
Describe the bug
----------------

Wrong crop of PDF with previously splitted pages. The preview looks fine, but the saved PDF is messed-up with the previous page splitting.

It seems that the problem is related to: [For discussion / feedback] option to crop only content #477

To Reproduce
------------

1.  Open the PDF (the attached file: [problematic_pdf.pdf](https://github.com/pdfarranger/pdfarranger/files/9883282/problematic_pdf.pdf))
2.  Click on Page Format (you can choose "select all", but with the single page problem is the same)
3.  Choose: left: 12%, right 12%, top: 5%, bottom: 5%, then click OK
4.  Save or export the resulting PDF

Expected behavior
-----------------

The pages should be cropped.

Input files
-----------

[resulting_pdf.pdf](https://github.com/pdfarranger/pdfarranger/files/9883279/resulting_pdf.pdf)
[problematic_pdf.pdf](https://github.com/pdfarranger/pdfarranger/files/9883282/problematic_pdf.pdf)

Screenshots
-----------

![exported_pdf](https://user-images.githubusercontent.com/933693/198403011-ca9d3a17-e0c0-459b-a14a-740306014441.jpg)
![preview_after_the_format_changes](https://user-images.githubusercontent.com/933693/198403024-04730148-c548-4f6d-a72e-820474671bd5.jpg)
![splitted_pdf](https://user-images.githubusercontent.com/933693/198403035-6b659774-f98f-4e2e-abcd-ef870abcdf3c.jpg)
![original_pdf](https://user-images.githubusercontent.com/933693/198403043-beebe7f8-d737-46f6-8487-0193d6e0ffe1.jpg)

System and Versions
-------------------

-   PDF Arranger 1.9.1-windows-portable
-   Downloaded from GitHub
-   Windows 7 Professional, 64-bit

**Comment by jeromerobert** [comment]
Reproduced with current master, libqpdf 11.1.1, pikepdf 6.0.0+dfsg, GTK 3.24.34, Python 3.10.8. Thanks.

**Comment by jeromerobert** [comment]
Actually there is no need to crop. The bug can be seen by just openning the document and saving it.

**Comment by jeromerobert** [comment]
This is document have CropBox larger than MediaBox (see [PDF specification §7.7.3.3](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf)).

[PDF specification §14.11.2.1](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf) says:

*The crop, bleed, trim, and art boxes shall not ordinarily extend beyond the boundaries of the media box.*

but also:

*If they do, they are effectively reduced to their intersection with the media box.*

And we currently do no do that :-/. We always assume that CropBox is smaller than MediaBox. This should be easy to fix.
