### ISSUE TITLE
booklet doesn't format correctly

### ISSUE THREAD

**Issue by hezdog** [pdfarranger/pdfarranger#751]
There are no options to help with booklet construction and it doesn't format it correctly for reading. Pages are in the completely wrong order and the cover and last page are not on the same sheet as they would be in booklet form.

**Comment by hezdog** [comment]
I am trying to format a PDF for printing and the booklet constructor does not have any options to help with this.

**Comment by jeromerobert** [comment]
I'm sorry about that. May be you could tell us what the problem is.

**Comment by dreua** [comment]
Please add some screenshots so we can understand the issue. I believe the booklet creator is not really guiding you through the process but it should work if you think about it and add empty pages when necessary.

Closing this issue as there has been no response for some time, but we can reopen it if new information comes in.
