### ISSUE TITLE
Multi-page document splitting (feature request)

### ISSUE THREAD

**Issue by petaflot** [pdfarranger/pdfarranger#758]
Describe the bug
----------------

PDFArranger is great to merge files ; to split them, no so.

To Reproduce
------------

Go to a print shop with a pile of papers, ask them to scan it. They will either scan individual pages into a PDF file each (more expensive), or give you a PDF file containing all the pages.

It is likely that there will be multiple documents possibly unrelated to each other, some of which may be multiple pages.

Expected behavior
-----------------

A helper to split a document into sub-documents ; it should insert a clearly visible separator between two pages, possibly allowing the user the specify a filename for the sub-document.

There should be a way to specify file naming format with values such as auto-increment index, start-stop page number, original file name, current date..

Once the user is happy with the way the document is split (possibly inserting pages from another source), a button to save everything should... save everything.

Input files
-----------

any multi-page document

Screenshots
-----------

![pdfa_split](https://user-images.githubusercontent.com/32837871/202854100-f17ab5fd-d181-4438-acbe-1ad2c319c25e.png)

System and Versions
-------------------

All

**Comment by kbengs** [comment]
Have you tried to have two (or more) pdfarrranger windows open? You could drag the pages you want to have in one document, then save them, then close (ctrl+W) and continue with next document.

Adding markers as you suggest is not possible in iconview. The feature would need to be implemented in gtk iconview first.

**Comment by petaflot** [comment]
I have considered it, but:

- just thinking about it my mouse wrist already hurts. I personally have severe back and misc joint issues which make it unrealistic ; I know I'm not the only one and sparing such pains to those who don't have it already would be nice
- I feel like crying when I think of the the effort needed to manually type in file names while making sure I don't overwrite anything, don't leave blank indexes (not an issue in _my_ case, but for others?)

Instead of markers as suggested above, how about inserting dummy pages that act as markers?

![pdfa_x](https://user-images.githubusercontent.com/32837871/202893723-5b5d48f7-dade-4e2c-9cbf-9ca2b2b00fb2.png)

Using a "random" color to mark sub-documents would be very nice, too, I suppose no too hard to implement in gtk iconview (unless it's already a feature, which would surprise me)

**Comment by kbengs** [comment]
This is a bit interesting idea. But I am not convinced this feature would make the export workflow easier.  Automatic document naming is one thing, but I guess many would not be happy with the names and rename them later anyway.


>   select "make this selection a document" (a keyboard shortcut would definitely help)

ctrl + e and then type a name. After that you could delete the pages so you know they are done.

> view this page fullsize

double-click or f. You might need 1.9.1 for this, don't remember.

**Comment by petaflot** [comment]
> double-click or f. You might need 1.9.1 for this, don't remember.

oh nice. seems so obvious :-/ how did I miss that

> Automatic document naming is one thing, but I guess many would not be happy with the names and rename them later anyway.

that's why many programs support variables in file naming (grip for instance, or simply strftime)

exporting a selection would do, though. ideally, there are as few keystrokes / mouse clicks involved as possible:

click first page, press+hold shift key, click last page, release shift key, ctrl+e, enter (to confirm the name), that's _it_. the save dialog - allows specifying the filename -  can do auto-increment (like xsane does).

**Comment by kbengs** [comment]
A index, which counts up for every export, which is added to the suggested filename when exporting would make sense imo.

For example:
pikepdf-001.pdf (on first export)
pikepdf-002.pdf (on second export)

That should improve the multi-export workflow. I suggest we do that small change and close this issue with that.

#723 might also ad a useful feature for you @petaflot
