### ISSUE TITLE
New Feature request Context Menu Quick Combine , And my previous request

### ISSUE THREAD

**Issue by ghost** [pdfarranger/pdfarranger#759]
i'll keep it short 
1. A context menu entry of pdfarranger , with ability to select multiple files , and dump the combined file , in the same folder , without any user interaction , popups or anything
2. add bookmark of individual files so combined ( i requested this previously , even adobe acrobat has added this now )
3. bruh why not use adobe acrobat then? = the answer through question = 'bRuH why not delete this whole repo and go climb mt.everest on your last trip instead'?

**Comment by kbengs** [comment]
1. #760 will allow you to: select pages, export with ctrl + e, press enter to confirm the suggested filename. If you are a Windows user you can download and test zip or msi: https://github.com/pdfarranger/pdfarranger/actions/runs/3524803661

**Comment by dreua** [comment]
Requestor seems to have deleted their Github account, therefore I'll just close this.
