### ISSUE TITLE
editing a file, "save" acts like "save as" the first time

### ISSUE THREAD

**Issue by petaflot** [pdfarranger/pdfarranger#769]
Describe the bug
----------------

when editing a single document, "save" should never prompt for the file name if it exists

To Reproduce
------------

- open a single, existing PDF document
- rotate a page (or don't do anything, same-same)
- ctrl+s or save button
- "save as" dialog opens (at least correct filename is selected!)
- click save
- "file already exists, overwrite?" dialog opens
- click replace

Expected behavior
-----------------

the file should be saved without any prompt for the filename, no prompt to overwrite. just save it

System and Versions
-------------------
PDF Arranger-1.9.1
pikepdf-6.2.1
libqpdf-11.1.1
OS: Gentoo 2.9

**Comment by jeromerobert** [comment]
See #65 and #100
