### ISSUE TITLE
Installation via Winget or Chocolatey

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#780]
Has someone tried those on Windows? Is it any better in terms of Signature warnings or anything?

**Comment by dreua** [comment]
#778 triggered me to think about ways to improve the windows installation experience. Ideally that would be none of our concern but I too have lots of friends and family on Windows -.-

**Comment by dreua** [comment]
Another idea would be to accept donations specifically for Code signing certs and fixing stuff for Windows since 🤔

**Comment by jeromerobert** [comment]
I did not tried but I'm almost sure they use our unmodified packages, else kbeng would not have been the first to notice that Win32.md was broken.

Yet, they may pass options to `msiexec` to silent the warning or they may use the zip file.

People do whatever they want of their time, but I will personally not bother with donations or Windows certificates.

I also have friends and family using Windows and I was happy when carlos22 did the intial port. My Windows user are happy with the package as it is so I don't plan to improve it. Maintaining it is already difficult enough.

Again I'll be happy if someone would take the lead of the Windows stuff or just improve it.

**Comment by dreua** [comment]
I just tried winget and it installs and upgrades fine and silently. It seems to prefer user installation, so no uac is necessary. I added links to winget and it's PDF Arranger spec in #509 .

For now, I think winget is fine for me. Thanks for your input!
