### ISSUE TITLE
Automatic document numbering on export

### ISSUE THREAD

**Issue by petaflot** [pdfarranger/pdfarranger#782]
Describe the bug
----------------

following on Multi-page document splitting (feature request) #758 

the counter starts when pdfarranger is started, and just increments every time pages are exported.

this is typically a problem when:

- opening a large document
- exporting a bunch of pages
- close the document
- re-open the document at a later time to finish the work
- exporting pages again : the counter will start at zero again, every time pages are exported the filename needs to be corrected

Expected behavior
-----------------

set the counter to the value specified by the user, overriding the previous value if necessary

xsane does it right

**Comment by kbengs** [comment]
Yes the xsane behavior is even better. :-) I am working on this.
