### ISSUE TITLE
Portable application cannot open

### ISSUE THREAD

**Issue by limelect** [pdfarranger/pdfarranger#784]
Describe the bug
----------------
Portable application cannot open
![Screenshot - 18_12_2022 , 10_07_54](https://user-images.githubusercontent.com/4199131/208288103-4fcda835-fa2f-4af9-852f-8509f739f309.jpg)

To Reproduce
------------

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

Expected behavior
-----------------

Input files
-----------

Check if the bug appear only with some PDF or image files. If the bug is specific to some files please attach one to the issue.

Screenshots
-----------

System and Versions
-------------------

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)
-   pikepdf version and where you get it (distro package, pip, git, ...)
-   OS name and version (e.g.: Windows 10, Fedora 33, ...)

**Comment by limelect** [comment]
P.S there is no Z on my disk

**Comment by kbengs** [comment]
This sounds like https://github.com/pdfarranger/pdfarranger/issues/380 and https://github.com/pdfarranger/pdfarranger/issues/645

One possibility:
Open windows system settings and search for "path". Then "Edit the system environment variables". Then "Environment variables". Then in "User variables" select "Path" and edit. See what you have in the list. On my machine I had to remove "C:\Program Files\Tesseract-OCR" from the list. You might have something else that conflicts there. Does that help you?

**Comment by jeromerobert** [comment]
There is an issue with your system. We already wrote a lot about that in this issue tracker. See for exemple #645 which link most issues. See `listdlls` in #550. Tesseract and mintmproxy are known to conflict with pdfarranger and cause that issue.

**Comment by limelect** [comment]
Sorry I will delete no time to play

**Comment by dreua** [comment]
Strange, there seems to be no "Report as Spam / Advertisement" on Github -.-
