### ISSUE TITLE
Add option to create Table of Contents

### ISSUE THREAD

**Issue by TheTrio** [pdfarranger/pdfarranger#795]
This would be really handy when merging PDFs. 

Having a Table of Contents with a link to the start of the individual PDFs would be a nice to have. 

Something like this 

![image](https://user-images.githubusercontent.com/10794178/210169377-3c6e3504-8548-40d2-a4cd-d477fceb638b.png)

(This image is from https://www.sejda.com/merge-pdf)

The names can be derived from the individual pdf files. 

What do you think?

**Comment by dreua** [comment]
I think that this is not a core feature of PDF Arranger, I don't think someone from the team is going to implement it for you.

But if someone wants to implement it they should speak up here, I'm open to discuss this and help where I can.

- Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.

**Comment by TheTrio** [comment]
I see there's #462 which is very similar in purpose. Reading the discussion there makes me think implementing this is not trivial.

**Comment by dreua** [comment]
Yes, I believe almost all the trivial things are already implemented ;)
Tbh I believe it is unlikely that this feature will be implemented, should have mentioned that in the first comment, sorry.

**Comment by TheTrio** [comment]
Yeah there are too many gotchas. I'll close this for now.

**Comment by m-holger** [comment]
@jberkenbilt  fyi re future features
