### ISSUE TITLE
Help with modifying

### ISSUE THREAD

**Issue by DenBru456** [pdfarranger/pdfarranger#796]
Describe the bug
----------------

To Reproduce
------------

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

Expected behavior
-----------------

Input files
-----------

Check if the bug appear only with some PDF or image files. If the bug is specific to some files please attach one to the issue.

Screenshots
-----------

System and Versions
-------------------

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)
-   pikepdf version and where you get it (distro package, pip, git, ...)
-   OS name and version (e.g.: Windows 10, Fedora 33, ...)
How can I modify open source code and then install it?

**Comment by DenBru456** [comment]
How to modify open source code(downloaded) and then install it on windows or ubuntu?

**Comment by jeromerobert** [comment]
Moved to #798
