### ISSUE TITLE
Horizontal scrolling doesn't work when pressing Shift along with Scroll Wheel

### ISSUE THREAD

**Issue by galgogergo** [pdfarranger/pdfarranger#811]
Describe the bug
----------------

Back in 1.8.7 (? - I believe) I could scroll horizontally while I pressed Shift while I was scrolling with the mouse wheel. Now it doesn't work, it only scrolls vertical. 

It would be great if this feature returned! (lot of times I have to zoom into files that contain exported CAD drawings and I need to be able to navigate in any direction. It used to work before, don't know what happened.)

System and Versions
-------------------

- **PDF Arranger version**: 1.9.2, downloaded from GitHub, portable version.
- From the About menu: libqpdf 10.4.0, pikepdf 4.3.1, GTK 3.24.31 and Python 3.9.7 (downloaded the portable version, with these included)
- OS name and version:
**Edition:** Windows 10 Pro
**Version:** 22H2
**Install date:** ‎2021. ‎05. ‎21.
**build nr.** 19045.2364; Windows Feature Experience Pack 120.2212.4190.0

**Comment by kbengs** [comment]
I didn't know that was possible before. But yes I see it was possible in 1.8.2. It is possible to fix this. Thanks for reporting.

**Comment by dreua** [comment]
@kbengs Thank you for the quick fix!
