### ISSUE TITLE
Refactoring `mem_at_limit`

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#817]
I wanted to fix this CodeQL issue but I don't understand why the if/return part in this function is not at the end. In my mind it would make sense to check the memory limit *after* it has been calculated. 

If this is indeed intended behavior I'd like to see a little hint in the docstring or as comment :wink: 

https://github.com/pdfarranger/pdfarranger/blob/07aa4b790a8d227eb24510a2c3105c99fd1414ea/pdfarranger/core.py#L538-L546

Tracking issue for:
- [ ] https://github.com/pdfarranger/pdfarranger/security/code-scanning/2

**Comment by kbengs** [comment]
It's done that way for best performance. Once the limit is hit there is no need to continue to do the `self.mem_usage` add calculation. I do not know how much speed is gained that way. But for sure it is something. :-)

**Comment by dreua** [comment]
I see, but it will check based on the previous value, calculate the new mem_usage and not check that. (The next call to mem_at_limit will.) It probably makes sense if you understand the logic calling this function but just looking at the function alone it doesn't.

**Comment by dreua** [comment]
I'll just trust you on that and add a return False to the end, should be equal to the implicit return None ;)

**Comment by dreua** [comment]
It's now included with return False in #818. Thanks for the input!

**Comment by kbengs** [comment]
Yes it will overrun the mem limit by one thumbnail. It could be more clear written/documented I agree.
