### ISSUE TITLE
Virus findings by Virustotal

### ISSUE THREAD

**Issue by felix32257** [pdfarranger/pdfarranger#822]
Virustotal flags the portable version with 2 virus findings.

----------------

I doubt that malware is packaged here but who am I to judge the findings of specialized companies?

Download the portable version and let it run throught virustotal.com. You will have 2 findings: Antiy-AVL (Trojan/Win64.Agent) and Zillya (Downloader.IcedId.Win64.145).

------------

1.  Download the protable version
2.  Go to virustotal.com
3.  Upload the freshly downloaded portable version
4.  See virus findings

Expected behavior: No malware findings.

System and Versions
-------------------

-   PDF Arranger portable version 1.9.2 from Github/pdfarranger
-   Windows 11

**Comment by dreua** [comment]
It doesn't show any findings to me: https://www.virustotal.com/gui/url/4cb17a8ae475a54e4f107371845a8b421bb8581bb2e299269f74150b0b5a6bcb/detection
Maybe someone on your PC infected it before you could upload it? (Not sure that's still what viruses do, tbh, but it seems possible.)
Can you share a link or checksum of your file? Please *do not* upload your file here in case it is actually infected.

**Comment by dreua** [comment]
This is weird: Pasting the download link into virustotal shows no findings but actually downloading and uploading the zip does. Still most likely false positives but we shall have a look at it.

**Comment by dreua** [comment]
I tried some older versions and the windows version of Meld for comparison, all had the occasional match in virus total. (The latest version of Zim didn't.) Considering these are not big or very well known companies (both scanners you mention don't have an English Wikipedia page) I think it is safe to assume these are false positives.

If you like additional peace of mind and/or better scan results feel free to submit the file as "false positive" to the scanners detecting it. Autohotkey's forum has a [guide](https://www.autohotkey.com/boards/viewtopic.php?t=62266) on how to do that, it may be outdated though.

(Jerome was slightly faster but I'm going to leave my comment here anyway.)

**Comment by felix32257** [comment]
Thank you everyone! Yes the url doesn't trigger. Weird... Tried from Android as well, same results. My Windows machine shouldn't be infected and locally installed AV doesn't find anything either. So it's probably a false positive, yes. Thanks!
