### ISSUE TITLE
Support file Attaching

### ISSUE THREAD

**Issue by pr-apes** [pdfarranger/pdfarranger#827]
Since pikepdf [allows embedding files](https://pikepdf.readthedocs.io/en/latest/topics/attachments.html#attaching-files-to-a-pdf), it would be great that PDF Arranger would enable them too.

As a suggestion, when a PDF document contains embedded files, it would be great that the catalog contains [`/PageMode /UseAttachments`](https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf#search=UseAttachments).

Congratulations for your excellent work and many thanks for your help.

**Comment by dreua** [comment]
Tbh I've never seen this feature of PDF in use. I'm not going to implement it but maybe someone else will?

Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.

**Comment by dreua** [comment]
Closibg this as announced to keep our issues clean. Ftr, I think this should be doable without too much effort but at least for me its not high priority because the feature is really not used that often.

**Comment by kbengs** [comment]
No there is no documentation. But the steps are:
1. Fork pdfarranger (press the fork button in top right corner on github page)
2. Git pull you fork to your computer
3. Do the changes on the files on your computer
4. Add the changes to a commit
5. Push the branch to your github page
6. Open a pull request from your github page

It's as simple as that. :-) Are you familiar with git?

**Comment by jeromerobert** [comment]
@pr-apes IMHO there are 2 parts in this job:
- First what is related to the PDF it self. This is implemented with PikePDF and mostly in `export.py`. You could prototype something outside of PDF Arranger using only PikePDF. This is probably the easiest part of the job.
- Second the UI stuff. How you would display, or add attached file in the UI, This is GTK and probably the most difficult part of the job.
