### ISSUE TITLE
PDF arranger does not save the text layer

### ISSUE THREAD

**Issue by SokolovskyMaxim** [pdfarranger/pdfarranger#830]
After saving an edited document with a text layer, pdf arranger deletes the text layer

**Comment by dreua** [comment]
Having an exanple file usually saves us a lot of time and greatly increases the chances of us helping you with this issue. (That's why we ask for it in the bug report template.)

**Comment by dreua** [comment]
Closing for lack of response, we can always reopen if more information comes in.
