### ISSUE TITLE
Unable to remove "PDF Arranger"

### ISSUE THREAD

**Issue by cesces36** [pdfarranger/pdfarranger#834]
Error Message:
OS: Ubuntu 22.04.

Ubuntu Software: PDF Arranger.  click on trash icon.
enter : Authorization Code,
Error Message:
Unable to remove "PDF Arranger"
The following packages have unmet dependencies.  { nothing else shown in the message }

Can't trash?

How do I trash "Pdf Arranger ?

**Comment by kbengs** [comment]
That works fine on my machine. (pdfarranger 1.8.2, deb file) 

`sudo apt remove pdfarranger` in a terminal might give you more hints what is wrong with your installation.

**Comment by kbengs** [comment]
Closing this as it is likely not an issue in pdfarranger
