### ISSUE TITLE
Please enable PDF Arranger to add text to PDF documents

### ISSUE THREAD

**Issue by ovari** [pdfarranger/pdfarranger#837]
## Describe the feature request

Please enable PDF Arranger to add text (eg Pages Numbers, Date/Time, Filename) to PDF documents.

### Location
1. Margin, the text could be located at: Top, Left, Right, Bottom
2. If Top or Bottom margin, the text could be located at: Left, Center, Right
3. If Left or Right margin, the text could be located at: Bottom, Center, Top

### Text
Sample text could be `Page X of Y`.

What do you think?

Thank you

**Comment by jeromerobert** [comment]
Presented like this, I think that it's more a text processing feature than a feature for PDF Arranger. This opens the door to so many parameters (the text itself, fonts, exact text placement, etc.) that it makes me dizzy.

But thanks to the recent awesome work of kbengs (#530, #832) PDF Arranger now support adding overlay/underlay. Currently it only work for a single page, but if we manage to enable it for multiple pages (it should not be that difficult), what you ask for could be done the following way:

- Create an overlay PDF document with the text you want (where you want, and with the font you want) using your preferred text processor
- Import both overlay and target PDF in PDF Arranger
- Select the range of pages matching the overlay, cut them
- Past as overlay (or underlay) to the target PDF

This would also enable other scenario like:
- adding a logo on each pages
- adding a "Draft" watermarking
- hide a foot print text behind a white rectangle

**Comment by jeromerobert** [comment]
Implemented by kbengs in #839. It works like a charm.
