### ISSUE TITLE
Split/Crop page with mouse selection

### ISSUE THREAD

**Issue by BarbzYHOOL** [pdfarranger/pdfarranger#842]
Hello, awesome little tool

I used it to crop a PDF to avoid wasting my ink but it's not really made for this, so I had to guess the split % (60%). What about allowing to select it with the mouse?

Or just remove extra stuff, not split the page

Thanks for the work

**Comment by kbengs** [comment]
Was implemented in #954

**Comment by BarbzYHOOL** [comment]
cool, it's released on the flatpak?

**Comment by kbengs** [comment]
No it's not yet released. It will be in 1.11

**Comment by carlcorder** [comment]
Hello, thank you so much for creating this tool! I was hoping to test out the split page with mouse selection functionality so I downloaded the latest main build from here: https://github.com/pdfarranger/pdfarranger/actions/runs/7357279970

When I right click on a pdf I'm able to open the standard "Split Pages" dialogue box but I'm not sure exactly how to perform the mouse selection for creating the splits?

Thank you kindly for any advice / direction you can give :)

**Comment by dreua** [comment]
I don't think this has been implemented for "Split pages".

**Comment by carlcorder** [comment]
Well that would explain it! Thanks for responding.

**Comment by HubKing** [comment]
With this new feature, can I specify the cropping region only on one page and apply it to all or multiple selected pages? The PDF files I have the same layout for all pages in the same file, and they have top/bottom headers/footers that I don't need to print. If I have to repeat specifying the region with the mouse on each page, it will be time-consuming and tedious.

**Comment by kbengs** [comment]
Yes, the dialog will show the first page, when you click ok it will apply the same percent crop on all selected pages. So if the pages had the same size they will be cropped equally.
