### ISSUE TITLE
Can't change language when the program is set to Hebrew

### ISSUE THREAD

**Issue by yorai1212** [pdfarranger/pdfarranger#849]
Just installed the software, it's in Hebrew and there's not "preferences" option anywhere. Cannot find a way to change the language to English.

**Comment by dreua** [comment]
In order to help you efficiently we need some more information, the [issue template](https://github.com/pdfarranger/pdfarranger/issues/new?assignees=&labels=&template=bug_report.md&title=) is usually a good place to start.

The output of `locale` would also be helpful in your case.

It is likely that there is something wrong with your system, not PDF Arranger. Did you ever set (parts of) your system to hebrew or is this completely random?

**Comment by yorai1212** [comment]
> In order to help you efficiently we need some more information, the [issue template](https://github.com/pdfarranger/pdfarranger/issues/new?assignees=&labels=&template=bug_report.md&title=) is usually a good place to start.
> 
> The output of `locale` would also be helpful in your case.
> 
> It is likely that there is something wrong with your system, not PDF Arranger. Did you ever set (parts of) your system to hebrew or is this completely random?

I have looked at the bug template, but this isn't a bug most likely, so I don't know how to use it.

The timezone on my PC is set to Israel, yes, maybe that's why it autodetcted that I wanted Hebrew as the language.

Locale, as in the folder Locale in folder "pdfarranger"? I can put it in a RAR file and share it via a site like PixelDrain.

**Comment by dreua** [comment]
Forget about the locale, thats a tool in Linux, not helpful when you are on Windows.

**Comment by kbengs** [comment]
1.9.2 does not have the preferences dialog. (it has been implemented later)

Here you can find instructions on how to set language in 1.9.2:
https://github.com/pdfarranger/pdfarranger/tree/1.9.2#set-custom-language-in-windows

Or if you like to install a msi built from the main branch (which has the dialog):
https://github.com/pdfarranger/pdfarranger/actions/runs/4717821797

**Comment by yorai1212** [comment]
> 1.9.2 does not have the preferences dialog. (it has been implemented later)
> 
> Here you can find instructions on how to set language in 1.9.2: https://github.com/pdfarranger/pdfarranger/tree/1.9.2#set-custom-language-in-windows
> 
> Or if you like to install a msi built from the main branch (which has the dialog): https://github.com/pdfarranger/pdfarranger/actions/runs/4717821797

Oh I see, how did you get to that page though? I'm not very keen in GitHub, I just now tried going into the actions page and searching for "language", but nothing came up.

Either way, I cannot find any config file.
![image](https://user-images.githubusercontent.com/32553260/233148243-ef225f37-076b-40e8-9882-8026a32eebb7.png)
This is what came out when searching for "config". No ini file.

**Comment by kbengs** [comment]
If you installed the app in the default place you should find the ini here:
C:\Users\username\AppData\Roaming\pdfarranger\config.ini

The releases page has a "tag" link which goes to the README:
![image](https://user-images.githubusercontent.com/60842129/233154406-2595ddd8-d7c4-4984-b2c5-b190b13ba435.png)

**Comment by yorai1212** [comment]
I see.

About the config, the folder should look like this, right?
![image](https://user-images.githubusercontent.com/32553260/233163056-5a61da7d-6a51-4ae9-b3e3-e569fdacdd71.png)
I did install it in the default location that the software gave me, but I just can't find any config file.
Should I uninstall it and try downloading the portable version?

**Comment by kbengs** [comment]
The screenshot above is from the folder where pdfarranger is installed. For the non-portable version you should look for the config file here:
 `C:\Users\username\AppData\Roaming\pdfarranger\config.ini`
You will find some more info here:
https://github.com/pdfarranger/pdfarranger/tree/1.9.2#customization-of-keyboard-shortcuts

**Comment by kbengs** [comment]
@yorai1212 if you like to test there is a msi here:
https://github.com/pdfarranger/pdfarranger/actions/runs/4772024153
Which hopefully by default use same language as Windows does.
If you test it you should remove any changes you did to config.ini

**Comment by yorai1212** [comment]
Oh I see, I think I'll stick with the portable for now!
Thank you very much for the help nonetheless and sorry for the confusion I caused.
