### ISSUE TITLE
Shortcut for "Edit properties"

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [pdfarranger/pdfarranger#864]
Describe the bug
----------------

It will save time to have a shortcut for " Edit properties " action

Expected behavior
-----------------

maybe "Ctrl+E" will be fine

System and Versions
-------------------

-   PDF Arranger :1.8.2,1.9+

**Comment by dreua** [comment]
E is for export so that's a no.
I think I've seen i or j but lets check first what other programs use, evince, okular, eye of GNOME (image viewer) and maybe Gimp, Nautilus. Let's hope there is some kind of standard.
