### ISSUE TITLE
Undo history dialog / Action log

### ISSUE THREAD

**Issue by JunglePredator** [pdfarranger/pdfarranger#872]
2 feature requests:

Join Pages - literally the opposite of split pages; just joining 2 or more images vertically or horizontally on a single page with no white space.

Action Log - a optional gui window that lists all actions taken & highlights the current 'state' of the pdf so we know how many undos or redos we want.

**Comment by angsch** [comment]
> Join Pages - literally the opposite of split pages; just joining 2 or more images vertically or horizontally on a single page with no white space.

This was introduced one month ago via https://github.com/pdfarranger/pdfarranger/pull/847

**Comment by dreua** [comment]
Thank you for your feature request. Unfortunately, it looks like no one is going to work on it, therefore I'm closing this as "stale feature" in order to keep a better overview in our issue tracker.
If anyone wants to work on this feel free to comment or reopen.
