### ISSUE TITLE
[Arch] community merged into extra repository

### ISSUE THREAD

**Issue by j5k** [pdfarranger/pdfarranger#873]
Please update all urls.

https://archlinux.org/news/git-migration-announcement/
https://archlinux.org/news/git-migration-completed/

**Comment by jeromerobert** [comment]
Done:

* https://github.com/pdfarranger/pdfarranger/wiki/Binary-packages/_history
* https://github.com/pdfarranger/pdfarranger/wiki/Binary-packages/_compare/c937ee070247192c0605fbd369daf9e339d1a517...04f16e6d42e1ad9d10139931ad1234fea5f2defb
