### ISSUE TITLE
Bug: Overly long field in properties causes  window to become too wide

### ISSUE THREAD

**Issue by JunglePredator** [pdfarranger/pdfarranger#877]
A slight, but not truly a problem, bug:

In a pdf that had a 'subject' property of well over a paragraph cause odd behaviour in the edit properties window.

The 'ok' & 'cancel'  buttons were way way way off screen & attempting to shrink the 'edit properties' window caused it to disappear & not be possible to refocus.

2 work arounds were: hit escape to close the window even though it wasn't in focus & to carefully drag the window to the left until the 'ok' & 'cancel' buttons became visible. If the window was accidentally maximised you have to start again.

**Comment by jeromerobert** [comment]
Thank you. It's not only "subject" but all fields. We should prevent the window to extend and just add ellipsis for long text.
