### ISSUE TITLE
Verify app

### ISSUE THREAD

**Issue by ovari** [pdfarranger/pdfarranger#892]
It would be great to have this app as a verified app on [Flathub](https://flathub.org/apps/com.github.jeromerobert.pdfarranger).

Can this app please be [verified on Flathub](https://flathub-docs.vercel.app/docs/for-users/verification)?

Possible code pointers at https://github.com/flathub/eu.betterbird.Betterbird/issues/80

Thank you

**Comment by jeromerobert** [comment]
Done
