### ISSUE TITLE
Changing the marked page does not change the shown page (FR: follow the selection)

### ISSUE THREAD

**Issue by rwiesbach** [pdfarranger/pdfarranger#896]
Describe the bug
----------------

When a page outside of the current screen is selected/marked, the shown page is still the previous one

To Reproduce
------------
Open PDF. Arrange zoom and window size such that the is only one column of pages. click on page one. Use cursor down to change the selected/marked page until the selected page is not shown on the screen

Expected behavior
-----------------
pdfarranger scrolls down to page n+1, page 1 is no longer visible.

use case: browse all pages of a pdf and remove the irrelevant ones. I'd like to show the pages one after the other by clicking "next" (cursor) or "del" accordingly

Input files
-----------

all (seems like)

Screenshots
-----------
none

System and Versions
-------------------

-   PDF Arranger 1.6.2, debian apt
-   pikepdf version and where you get it (distro package, pip, git, ...): unknown
-   OS name and version: debian 11

**Comment by rwiesbach** [comment]
I'm sorry. I just noticed that debians pdfarranger 1.6.2 is 2.5 years old and that 1.9.2 does exactly what I requested here. 

Would be nice to know which version did change this behavior, but ticket can be closed.

**Comment by kbengs** [comment]
Scrolling when moving cursor with keyboard arrows was fixed in 1.7.0

Scrolling when deleting pages is fixed in main and will be in 1.10.0 which is planned to be released in July
