### ISSUE TITLE
Display OS in about dialogue

### ISSUE THREAD

**Issue by flywire** [pdfarranger/pdfarranger#909]
It would be useful to add OS to the about screen so users can copy/paste the info into bug reports

**Comment by dreua** [comment]
It would also be good to know if it is a flatpak.

**Comment by flywire** [comment]
The About form does not allow all information to be selected at the same time so rearranging the form could fix most of this issue. Consider a button to ensure appropriate info is copied consistently, like LibreOffice as shown below:

```
[Seems App name should be included]
Version: 7.5.4.2 (X86_64) / LibreOffice Community
Build ID: 36ccfdc35048b057fd9854c757a8b67ec53977b6
CPU threads: 8; OS: Windows 10.0 Build 19044; UI render: Skia/Raster; VCL: win
Locale: en-AU (en_AU); UI: en-GB
Calc: threaded
```

![image](https://github.com/pdfarranger/pdfarranger/assets/11288701/ab907fb1-36a7-47b4-8b41-f94b8cea732f)

**Comment by dreua** [comment]
Ftr, this is how it looks inside a flatpak:
```
sh-5.1$ cat /etc/os-release 
NAME=GNOME
VERSION="44 (Flatpak runtime)"
VERSION_ID=44
ID=org.gnome.Platform
PRETTY_NAME="GNOME 44 (Flatpak runtime)"
BUG_REPORT_URL="https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/new"
HOME_URL="https://www.gnome.org/"
```

There is also the `/app/` directory but I guess getting the PRETTY_NAME or  whatever should be sufficient. I am, however, not sure if someone will find the time to work on this. Ideally there would be better support for this in Gnome itself or some library, not much point in each application implementing it itself, is there?
