### ISSUE TITLE
Can't open page context menu via keyboard

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#915]
While translating and testing accelerators I noticed that I can no longer open the context menu (right click) of a page without using the mouse. Tried the context menu key (between right super and ctrl), different F-keys, also with modifiers. I guess this was possible in a previous release but I rarely use this feature so it might have vanished anywhere between PDF Arranger versions or Gnome / OS updates.

Any pointers appreciated, once I find the time I might test older versions :thinking:

**Comment by jeromerobert** [comment]
I couldn't find any version where the keyboard shortcut to open the popup menu worked. It tested both the menu key and shift+F10. In Thunar only shift+F10 is working.

**Comment by jeromerobert** [comment]
I'll add `Shift+F10` and the hability to change it in the configuration file. If you want to use the key between `Alt` and right `Ctrl`, the name is `Multi_key`.
