### ISSUE TITLE
[Snap] Cannot open files

### ISSUE THREAD

**Issue by Francis4344** [pdfarranger/pdfarranger#924]
PDF Arranger 1.9.2
Ubuntu-Mate 22.04

Installed with snap.
I opened one file; closed it and now I cannot open any pdf. 
That is, I click on a pdf file but it does not open. 
I removed the package and reinstalled. No difference.

**Comment by dreua** [comment]
We do not offer a snap. Is Ubuntu distributing PDF Arranger as snap? Can you try running it from command line and paste any output?

**Comment by jeromerobert** [comment]
https://snapcraft.io/pdfarranger
https://github.com/soumyaDghosh/pdfarranger-snap

@soumyaDghosh Could you have a look ?

**Comment by soumyaDghosh** [comment]
The snap was recently transferred to me & I got no time to look into the listing details. Sorry for giving the upstream repo link there as the developer website. That's done by the previous maintainer. Now coming to the issue, the snap has nothing new. It gets all the same error. There was only one time when I got some errors in the terminal. 

```
  File "/snap/pdfarranger/25/usr/lib/python3.10/dist-packages/pdfarranger/pdfarranger.py", line 1098, in on_action_open
    self.on_action_new(filenames=chooser.get_filenames())
  File "/snap/pdfarranger/25/usr/lib/python3.10/dist-packages/pdfarranger/pdfarranger.py", line 1085, in on_action_new
    app_info.launch(launch_files, launch_context)
gi.repository.GLib.GError: g-exec-error-quark: Failed to execute child process “gio-launch-desktop” (No such file or directory) (8)
```

This showed up when I's trying to open a pdf, when another one was already open. I need logs to further look into.
