### ISSUE TITLE
Panel where to see the selected page

### ISSUE THREAD

**Issue by tom-vb** [pdfarranger/pdfarranger#939]
When ordering pages, it would be very useful to have a panel in which to see the selected page enlarged. Like for example the Faststone image viewer have.

thanks,
best regards

**Comment by kbengs** [comment]
Have you found out that you can double-click a page to zoom into that page? Double-clicking again will return to the old zoom. You can also use key "f".

**Comment by tom-vb** [comment]
Yes, I found, but it is uncomfortable and not practical, in my humble point of view

**Comment by tom-vb** [comment]
What I mean is that from the point of usability it is not hergonomic.. You have to make 4 clicks, two to zoom and two to return to where you were, apart from losing the "focus" as the screen changes and then you have to refocus and center your eyes in the screen. On the other hand, with a panel (better if it is adjustable in size and location) you have it with a single click, without losing focus and attention. From the programming point of view it is an easy improvement to implement and that I am sure can serve many users and make Pdfarranger a better software.

**Comment by dreua** [comment]
Thank you for your feature request. Unfortunately, it looks like no one is willing to work on it, therefore I'm going to close this "stale feature" in order to keep a better overview in our issue tracker. If anyone wants to work on this feel free to comment or reopen.
