### ISSUE TITLE
shortcut for cutting white space

### ISSUE THREAD

**Issue by aabolo** [pdfarranger/pdfarranger#946]
Can the software add a shortcut key for cutting white space manually?
For example, press ctrl+PageUp to adjust the upper space in a small range, and press ctrl+shift+PageUp to adjust the upper space in a large range.

**Comment by kbengs** [comment]
I am currently working on selecting crop with mouse selection:
![Crop margins](https://github.com/pdfarranger/pdfarranger/assets/60842129/0f5ce00d-89e4-4cac-b8f5-ea784f2bc9d9)

Would that make the feature request obsolete?

**Comment by aabolo** [comment]
Looking forward to this feature, thank you.
I am a Chinese user and I found that some pages could not be edged successfully with the automatic edging function, so I still need to manually edging.

**Comment by kbengs** [comment]
Closing this as the dialog above was implemented.
