### ISSUE TITLE
Github Action rpmbuild image need to be rebuild

### ISSUE THREAD

**Issue by jeromerobert** [pdfarranger/pdfarranger#972]
Indeed this is failing to install `*.mo` files:

```
podman run -v $PWD:$PWD -w $PWD docker.io/dreua/pdfarranger-docker-rpm bash -c "yum install -y gettext python3-devel python3-setuptools python3-wheel python3-pip && pip install -v ."
```

while

```
podman run -v $PWD:$PWD -w $PWD docker.io/fedora:38 bash -c "yum install -y gettext python3-devel python3-setuptools python3-wheel python3-pip && pip install -v ."
```
succeed. That's surprising because https://github.com/pdfarranger/pdfarranger-docker-ci/blob/main/rpmbuild/Dockerfile doesn't contain anything odd.

_Originally posted by @jeromerobert in https://github.com/pdfarranger/pdfarranger/issues/965#issuecomment-1722261184_
            
            
And if I rebuild https://github.com/pdfarranger/pdfarranger-docker-ci/blob/main/rpmbuild/Dockerfile from source it also works. So it's definitly a transient bug in Fedora. @dreua will just have to rebuild and push a new image to fix the issue.

_Originally posted by @jeromerobert in https://github.com/pdfarranger/pdfarranger/issues/965#issuecomment-1722264999_

**Comment by dreua** [comment]
Done, sorry I'm currently unable to do much here.
