### ISSUE TITLE
Wrong drop locations in a right-to-left locale

### ISSUE THREAD

**Issue by zeldi123** [pdfarranger/pdfarranger#978]
my windows language is set to hebrew, which is a right to left written language, so many things are sorted that way (my start menu for example is on the bottom right)
this is causing wried behevior with how dragging pages inside the software works...
my first page is the top right, and going left and down from there,

**the bug:**
if i drag page X to the left side of the last page, according to the way the pages are displayed on my screen it should now be the last page (X), but instead the program is reading "left side of last page" as "1 page before the last page"

can that either be fixed to also arrange based on the display order,
or add an option/ force it to be left to right like english?

**Comment by kbengs** [comment]
I guess it would be possible to force the app to use left to right order. Would the app be usable for you then? 
Is the bug you describe the only weird thing you notice? Does it for example make sense that the start menu is on bottom right?

**Comment by dreua** [comment]
Reproducible on Linux, even if it is not translated: `LANG=ar_DZ.UTF-8 pdfarranger`

Not sure whether that is a bug in Iconview or some of our drag and drop handling :thinking:

**Comment by kbengs** [comment]
![Screenshot_20230923_182125](https://github.com/pdfarranger/pdfarranger/assets/60842129/78ca809d-ed11-43cd-8e52-9e11105ca069)
@zeldi123 is this a correct page order in your language?

**Comment by zeldi123** [comment]
![Screenshot_20230923_182125](https://github.com/pdfarranger/pdfarranger/assets/60842129/78ca809d-ed11-43cd-8e52-9e11105ca069)
@zeldi123 is this a correct page order in your language?

_Originally posted by @kbengs in https://github.com/pdfarranger/pdfarranger/issues/978#issuecomment-1732342180_
            Yes that is the correct page layout for my language and how its showing for me, 

if the app will have an option to force it to a left to right order that will be the best fix IMO - because the whole UI is in english so a user will understand that the order is like in english (which is left to right)

**Comment by dreua** [comment]
Have you Trier setting the language to english in the settings?

**Comment by zeldi123** [comment]
yes, didnt help still page 1 is the top right and if i drag a page to the left side (and see the marking that the UI gives) of a page it will "spawn" at the right side in the layout (so dragging page 1 to between 3 and 4, will place it between 2 and 3 and thats my problem...  i dont care if ill have to drag it to the left or right side of the page, just so its consistent with how the page are layed out)

**Comment by kbengs** [comment]
@zeldi123 a zip/msi can be found here if you like to test and report if this work as you expect:
https://github.com/pdfarranger/pdfarranger/actions/runs/6421450779

**Comment by zeldi123** [comment]
> @zeldi123 a zip/msi can be found here if you like to test and report if this work as you expect: https://github.com/pdfarranger/pdfarranger/actions/runs/6421450779
> 
> > This fixes:
> > ```
> > * Drag and drop of pages
> > 
> > * Dragging in a file
> > 
> > * Selecting pages by clicking and dragging mouse
> > 
> > * Navigating and selecting with keyboard arrows
> > ```

this verstion works great thank you :)
(only tested on my language, not sure if its messing english OS now or anything,
for me its great)
