### ISSUE TITLE
pdfarranger==1.1.1 not found and is required by the application

### ISSUE THREAD

**Issue by mattadori** [pdfarranger/pdfarranger#982]
Launching pdfarranger from terminal gives the following error:

`pkg_resources.DistributionNotFound: The 'pdfarranger==1.1.1' distribution was not found and is required by the application`

System and Versions
-------------------

-   PDF Arranger version: 1.8.2 installed by apt
-   pikepdf 8.4.1 installed via pip
-   OS name and version: Ubuntu 22.04 LTS

**Comment by dreua** [comment]
That doesn't really make sense to me, could it be leftovers from a previous installation? Is the message above the whole error message?
Try `which pdfarranger` and `cat $(which pdfarranger)` and paste the full output here, maybe it gives us a hint of what is going wrong here.
Would running it via `python -m pdfarranger` work?

**Comment by mattadori** [comment]
Solved.
`which pdfarranger` resulted in `$HOME/.local/bin/pdfarranger`. I removed it and reinstalled pdfarranger from apt.

Thanks!
