### ISSUE TITLE
Where are the latest nightbuild windows builds?

### ISSUE THREAD

**Issue by webiix** [pdfarranger/pdfarranger#984]
Hello Folks.

Where can I find the latest nightly windows build?
The latest version I can see is the 1.10.0.

I tried to build from the source code, but I got several errors (despite all dependencies being installed). Maybe I need to setup a linux box to create the windows binaries and msi files?

Cheers.

**Comment by dreua** [comment]
> Nightly builds for Microsoft Windows can be found in the [Github Actions tab](https://github.com/pdfarranger/pdfarranger/actions/workflows/install.yml?query=branch%3Amain+event%3Apush+is%3Asuccess). Click the latest `main` build and see `pdfarranger-windows-portable-zip` and `pdfarranger-windows-installer-msi` at the bottom. You must be authenticated on Github.

Copied from the Wiki

**Comment by webiix** [comment]
> > Nightly builds for Microsoft Windows can be found in the [Github Actions tab](https://github.com/pdfarranger/pdfarranger/actions/workflows/install.yml?query=branch%3Amain+event%3Apush+is%3Asuccess). Click the latest `main` build and see `pdfarranger-windows-portable-zip` and `pdfarranger-windows-installer-msi` at the bottom. You must be authenticated on Github.
> 
> Copied from the Wiki

I already checked the wiki. When I click "main" there isn't any packages at the bottom (and I am authenticated has I am replying to this message).

**Comment by dreua** [comment]
https://github.com/pdfarranger/pdfarranger/actions/runs/6208430514

**Comment by dreua** [comment]
I see those instructions are not ideal, don't click on main but on the bold heading above it. Feel free to edit the wiki with a better wording. That surely is confusing for someone who never used github actions, sorry.

**Comment by dreua** [comment]
I don't think anyone here is involved with scoop, just found this as the source for the PDF Arranger package: https://github.com/ScoopInstaller/Extras/blob/master/bucket/pdfarranger.json

We could make the CI upload the binaries somewhere I guess, but we'd probably need some kind of hosting space for it which allows for public downloads.

**Comment by dreua** [comment]
A second repository with github releases would work for that. So it should be doable but I don't know if anyone here is willing to do the legwork. And someone else would need to take care of the scoop side, I really don't know how that works.

**Comment by KraXen72** [comment]
couldn't the scoop manifest point to github CI build artifacts of nightlies?

**Comment by dreua** [comment]
Sorry for the late reply. Unlike releases the artifacts are only downloadable if you are authenticated on github, therefore I was thinking about another repo serving those as releases. There could be other options like the scoop systems having a token to access artifacts.
I don't feel like learning the workings scoop but I'm happy to help from the PDF Arranger side if you or anyone needs help to make this work. Otherwise I'd say we close this as resolved. Feel free to reopen/comment if there is anything else.

**Comment by dreua** [comment]
I also reworded the wiki page to hopefully make it easier to download nightlies for future users. Thanks for the feedback!
